# Generated by Django 6.0 on 2025-12-14 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('work_date', models.DateField(db_index=True, verbose_name='Work Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('break_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Break Duration (minutes)')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Break Start Time')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Break End Time')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Needs Revision')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('admin_adjusted_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Override calculated hours (admin only)', max_digits=5, null=True, verbose_name='Admin Adjusted Hours')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('billing_week_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Billing Week Year')),
                ('billing_week_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Billing Week Number')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_logs', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='projects.projectassignment', verbose_name='Assignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='employees.employeeprofile', verbose_name='Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='projects.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Work Log',
                'verbose_name_plural': 'Work Logs',
                'ordering': ['-work_date', '-start_time'],
                'unique_together': {('employee', 'project', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkLogPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('photo', models.ImageField(upload_to='worklogs/photos/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='Caption')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='Photo Taken At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='worklogs.worklog', verbose_name='Work Log')),
            ],
            options={
                'verbose_name': 'Work Log Photo',
                'verbose_name_plural': 'Work Log Photos',
                'ordering': ['created_at'],
            },
        ),
    ]
