# Generated by Django 6.0 on 2025-12-26 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_allowancetype'),
        ('worklogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLogAllowance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('custom_allowance_name', models.CharField(blank=True, default='', help_text='If allowance_type is empty, provide a custom name', max_length=100, verbose_name='Custom Allowance Name')),
                ('hours', models.DecimalField(decimal_places=2, help_text='How many hours this allowance applies to', max_digits=5, verbose_name='Hours')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('allowance_type', models.ForeignKey(blank=True, help_text='Select from predefined allowances, or leave empty for custom', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_log_entries', to='employees.allowancetype', verbose_name='Allowance Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('work_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='worklogs.worklog', verbose_name='Work Log')),
            ],
            options={
                'verbose_name': 'Work Log Allowance',
                'verbose_name_plural': 'Work Log Allowances',
                'ordering': ['created_at'],
            },
        ),
    ]
