# Generated by Django 6.0 on 2025-12-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_gratuity'),
        ('worklogs', '0002_worklogallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='location_override',
            field=models.CharField(blank=True, default='', help_text='Manual address if project location is empty', max_length=300, verbose_name='Location Override'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='customers.service', verbose_name='Service Type'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='customers.outfolder', verbose_name='Supervisor'),
        ),
    ]
