# Generated by Django 6.0 on 2025-12-27 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0003_worklog_location_override_worklog_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worklogallowance',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Who added this allowance (employee or admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_allowances', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AddField(
            model_name='worklogallowance',
            name='added_by_admin',
            field=models.BooleanField(default=False, help_text='If True, this allowance appears in company invoice only, not in employee payslip', verbose_name='Added by Admin'),
        ),
    ]
