# Generated by Django 6.0 on 2025-12-27 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_add_per_service_surcharges_and_custom_allowances'),
        ('employees', '0009_employeeprofile_can_add_allowances_and_more'),
        ('projects', '0002_add_supervisors_m2m'),
        ('worklogs', '0004_add_admin_tracking_to_allowances'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('scheduled_start_time', models.TimeField(blank=True, null=True, verbose_name='Expected Start Time')),
                ('scheduled_end_time', models.TimeField(blank=True, null=True, verbose_name='Expected End Time')),
                ('location_notes', models.TextField(blank=True, default='', verbose_name='Location/Address Notes')),
                ('supervisor_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Supervisor Phone')),
                ('supervisor_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Supervisor Email')),
                ('special_instructions', models.TextField(blank=True, default='', verbose_name='Special Instructions')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Actual Start Time')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Actual End Time')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Break Start Time')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Break End Time')),
                ('employee_notes', models.TextField(blank=True, default='', verbose_name='Employee Notes')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='employees.employeeprofile', verbose_name='Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='projects.project', verbose_name='Project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='customers.service', verbose_name='Service Type')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='customers.outfolder', verbose_name='Supervisor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('work_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_shift', to='worklogs.worklog', verbose_name='Created Work Log')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-scheduled_date', 'scheduled_start_time'],
            },
        ),
    ]
