# Generated by Django 6.0 on 2025-12-28 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0006_add_datetime_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worklog',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'Work Log', 'verbose_name_plural': 'Work Logs'},
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together=set(),
        ),
    ]
