# Generated by Django 6.0 on 2025-12-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0007_alter_worklog_options_alter_worklog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='breaks',
            field=models.JSONField(blank=True, default=list, help_text='Array of break periods [{start: HH:MM, end: HH:MM}, ...]', verbose_name='Breaks'),
        ),
    ]
