# Generated by Django 6.0 on 2026-01-10 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_add_website_field'),
        ('employees', '0012_add_overtime_threshold'),
        ('projects', '0003_projectshifttemplate_projectplannedday_and_more'),
        ('worklogs', '0010_add_end_billing_week_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('work_date', models.DateField(db_index=True, help_text='The date of this work entry', verbose_name='Work Date')),
                ('planned_start_time', models.TimeField(blank=True, help_text='Scheduled start time from shift template', null=True, verbose_name='Planned Start Time')),
                ('planned_end_time', models.TimeField(blank=True, help_text='Scheduled end time from shift template', null=True, verbose_name='Planned End Time')),
                ('actual_start_datetime', models.DateTimeField(blank=True, help_text='When employee actually started working', null=True, verbose_name='Actual Start')),
                ('actual_end_datetime', models.DateTimeField(blank=True, help_text='When employee actually finished working', null=True, verbose_name='Actual End')),
                ('breaks', models.JSONField(blank=True, default=list, help_text='Array of break periods [{start: HH:MM, end: HH:MM}, ...]', verbose_name='Breaks')),
                ('break_duration_minutes', models.PositiveIntegerField(default=0, help_text='Total break time in minutes', verbose_name='Break Duration (minutes)')),
                ('location_override', models.CharField(blank=True, default='', help_text='Manual address if project location is empty', max_length=300, verbose_name='Location Override')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('in_progress', 'In Progress'), ('draft', 'Draft'), ('pending', 'Pending Approval'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='planned', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('cancellation_reason', models.TextField(blank=True, default='', verbose_name='Cancellation Reason')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('admin_adjusted_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Override calculated hours (admin only)', max_digits=5, null=True, verbose_name='Admin Adjusted Hours')),
                ('billing_week_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Billing Week Year')),
                ('billing_week_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Billing Week Number')),
                ('end_billing_week_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Billing Week Year')),
                ('end_billing_week_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='End Billing Week Number')),
                ('agency', models.ForeignKey(blank=True, help_text='If employee is from an external agency', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='employees.agency', verbose_name='Agency')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_entries', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='employees.employeeprofile', verbose_name='Employee')),
                ('legacy_shift_assignment', models.ForeignKey(blank=True, help_text='Link to original ShiftAssignment (for migration tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_entries', to='projects.shiftassignment', verbose_name='Legacy ShiftAssignment')),
                ('legacy_worklog', models.ForeignKey(blank=True, help_text='Link to original WorkLog (for migration tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_entries', to='worklogs.worklog', verbose_name='Legacy WorkLog')),
                ('planned_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_work_entries', to='customers.outfolder', verbose_name='Planned Supervisor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_entries', to='projects.project', verbose_name='Project')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='customers.service', verbose_name='Service Type')),
                ('shift_template', models.ForeignKey(blank=True, help_text='The shift pattern this entry is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_entries', to='projects.projectshifttemplate', verbose_name='Shift Template')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Work Entry',
                'verbose_name_plural': 'Work Entries',
                'ordering': ['-work_date', '-actual_start_datetime'],
                'indexes': [models.Index(fields=['employee', 'work_date'], name='workentry_emp_date_idx'), models.Index(fields=['work_date', 'status'], name='workentry_date_status_idx'), models.Index(fields=['project', 'work_date'], name='workentry_proj_date_idx'), models.Index(fields=['status', 'submitted_at'], name='workentry_pending_idx'), models.Index(fields=['billing_week_year', 'billing_week_number'], name='workentry_billing_idx'), models.Index(fields=['employee', 'status', 'work_date'], name='workentry_mobile_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'work_date', 'shift_template'), name='unique_employee_date_shift')],
            },
        ),
    ]
