# Generated by hand for data migration
# Migration: 0012_migrate_existing_data.py

from django.db import migrations


def migrate_worklog_and_shiftassignment_data(apps, schema_editor):
    """
    Migrate existing data from ShiftAssignment and WorkLog to unified WorkEntry.
    
    Strategy:
    1. First, migrate WorkLogs that are linked to ShiftAssignments (merged records)
    2. Then, migrate orphan ShiftAssignments (planning-only, no actual work recorded)
    3. Finally, migrate orphan WorkLogs (manual entries without planning)
    
    This ensures no data is lost and all records are properly tracked.
    """
    WorkLog = apps.get_model('worklogs', 'WorkLog')
    WorkEntry = apps.get_model('worklogs', 'WorkEntry')
    ShiftAssignment = apps.get_model('projects', 'ShiftAssignment')
    
    migrated_count = 0
    errors = []
    
    # ==========================================================================
    # STEP 1: Migrate WorkLogs with linked ShiftAssignments
    # ==========================================================================
    
    linked_worklogs = WorkLog.objects.filter(shift_assignment__isnull=False).select_related(
        'employee', 'project', 'shift_assignment__planned_day__shift_template',
        'shift_assignment__planned_day__supervisor', 'shift_assignment__agency',
        'supervisor', 'service', 'approved_by'
    )
    
    for worklog in linked_worklogs:
        try:
            assignment = worklog.shift_assignment
            planned_day = assignment.planned_day
            template = planned_day.shift_template
            
            WorkEntry.objects.create(
                # Core links
                employee=worklog.employee,
                project=worklog.project,
                agency=assignment.agency,
                
                # Planning fields
                shift_template=template,
                work_date=worklog.work_date or planned_day.date,
                planned_start_time=template.start_time if template else None,
                planned_end_time=template.end_time if template else None,
                planned_supervisor=planned_day.supervisor,
                
                # Actual work fields
                actual_start_datetime=worklog.start_datetime,
                actual_end_datetime=worklog.end_datetime,
                breaks=worklog.breaks if worklog.breaks else [],
                break_duration_minutes=worklog.break_duration_minutes or 0,
                service=worklog.service,
                location_override=worklog.location_override or '',
                
                # Status - use WorkLog status (more accurate)
                status=worklog.status,
                
                # Timestamps
                confirmed_at=assignment.confirmed_at,
                cancelled_at=assignment.cancelled_at,
                cancellation_reason=assignment.cancellation_reason or '',
                submitted_at=worklog.submitted_at,
                approved_at=worklog.approved_at,
                approved_by=worklog.approved_by,
                rejection_reason=worklog.rejection_reason or '',
                
                # Notes
                notes=worklog.notes or '',
                admin_notes=worklog.admin_notes or '',
                admin_adjusted_hours=worklog.admin_adjusted_hours,
                
                # Billing
                billing_week_year=worklog.billing_week_year,
                billing_week_number=worklog.billing_week_number,
                end_billing_week_year=worklog.end_billing_week_year,
                end_billing_week_number=worklog.end_billing_week_number,
                
                # Legacy tracking
                legacy_worklog=worklog,
                legacy_shift_assignment=assignment,
                
                # Timestamps from BaseModel
                created_at=worklog.created_at,
                created_by=worklog.created_by,
            )
            migrated_count += 1
        except Exception as e:
            errors.append(f"WorkLog {worklog.id}: {str(e)}")
    
    print(f"Step 1: Migrated {migrated_count} linked WorkLogs")
    
    # ==========================================================================
    # STEP 2: Migrate orphan ShiftAssignments (no WorkLog)
    # ==========================================================================
    
    # Get IDs of already migrated assignments
    migrated_assignment_ids = list(
        WorkEntry.objects.filter(legacy_shift_assignment__isnull=False)
        .values_list('legacy_shift_assignment_id', flat=True)
    )
    
    orphan_assignments = ShiftAssignment.objects.exclude(
        id__in=migrated_assignment_ids
    ).select_related(
        'employee', 'planned_day__shift_template__project',
        'planned_day__supervisor', 'agency'
    )
    
    orphan_count = 0
    for assignment in orphan_assignments:
        try:
            planned_day = assignment.planned_day
            template = planned_day.shift_template
            project = template.project
            
            # Map ShiftAssignment status to WorkEntry status
            status_map = {
                'planned': 'planned',
                'confirmed': 'confirmed',
                'cancelled': 'cancelled',
                'no_show': 'no_show',
                'completed': 'approved',  # Completed means work was done
            }
            entry_status = status_map.get(assignment.status, 'planned')
            
            WorkEntry.objects.create(
                # Core links
                employee=assignment.employee,
                project=project,
                agency=assignment.agency,
                
                # Planning fields
                shift_template=template,
                work_date=planned_day.date,
                planned_start_time=template.start_time,
                planned_end_time=template.end_time,
                planned_supervisor=planned_day.supervisor,
                
                # No actual work fields (this was just planned)
                actual_start_datetime=None,
                actual_end_datetime=None,
                breaks=[],
                break_duration_minutes=0,
                
                # Status
                status=entry_status,
                
                # Timestamps
                confirmed_at=assignment.confirmed_at,
                cancelled_at=assignment.cancelled_at,
                cancellation_reason=assignment.cancellation_reason or '',
                
                # Notes
                notes=assignment.notes or '',
                
                # Legacy tracking
                legacy_shift_assignment=assignment,
                
                # Timestamps from BaseModel
                created_at=assignment.created_at,
                created_by=assignment.created_by,
            )
            orphan_count += 1
        except Exception as e:
            errors.append(f"ShiftAssignment {assignment.id}: {str(e)}")
    
    print(f"Step 2: Migrated {orphan_count} orphan ShiftAssignments")
    
    # ==========================================================================
    # STEP 3: Migrate orphan WorkLogs (no ShiftAssignment - manual entries)
    # ==========================================================================
    
    orphan_worklogs = WorkLog.objects.filter(
        shift_assignment__isnull=True
    ).select_related(
        'employee', 'project', 'supervisor', 'service', 'approved_by'
    )
    
    manual_count = 0
    for worklog in orphan_worklogs:
        try:
            WorkEntry.objects.create(
                # Core links
                employee=worklog.employee,
                project=worklog.project,
                agency=None,  # Manual entries don't have agency
                
                # No planning fields (manual entry)
                shift_template=None,
                work_date=worklog.work_date,
                planned_start_time=None,
                planned_end_time=None,
                planned_supervisor=worklog.supervisor,
                
                # Actual work fields
                actual_start_datetime=worklog.start_datetime,
                actual_end_datetime=worklog.end_datetime,
                breaks=worklog.breaks if worklog.breaks else [],
                break_duration_minutes=worklog.break_duration_minutes or 0,
                service=worklog.service,
                location_override=worklog.location_override or '',
                
                # Status
                status=worklog.status,
                
                # Timestamps
                submitted_at=worklog.submitted_at,
                approved_at=worklog.approved_at,
                approved_by=worklog.approved_by,
                rejection_reason=worklog.rejection_reason or '',
                
                # Notes
                notes=worklog.notes or '',
                admin_notes=worklog.admin_notes or '',
                admin_adjusted_hours=worklog.admin_adjusted_hours,
                
                # Billing
                billing_week_year=worklog.billing_week_year,
                billing_week_number=worklog.billing_week_number,
                end_billing_week_year=worklog.end_billing_week_year,
                end_billing_week_number=worklog.end_billing_week_number,
                
                # Legacy tracking
                legacy_worklog=worklog,
                
                # Timestamps from BaseModel
                created_at=worklog.created_at,
                created_by=worklog.created_by,
            )
            manual_count += 1
        except Exception as e:
            errors.append(f"Manual WorkLog {worklog.id}: {str(e)}")
    
    print(f"Step 3: Migrated {manual_count} manual WorkLogs")
    
    # ==========================================================================
    # SUMMARY
    # ==========================================================================
    
    total = migrated_count + orphan_count + manual_count
    print(f"\n{'='*60}")
    print(f"MIGRATION COMPLETE")
    print(f"{'='*60}")
    print(f"Total WorkEntry records created: {total}")
    print(f"  - From linked WorkLogs: {migrated_count}")
    print(f"  - From orphan ShiftAssignments: {orphan_count}")
    print(f"  - From manual WorkLogs: {manual_count}")
    
    if errors:
        print(f"\nWarnings ({len(errors)}):")
        for error in errors[:10]:  # Show first 10
            print(f"  - {error}")
        if len(errors) > 10:
            print(f"  ... and {len(errors) - 10} more")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all WorkEntry records.
    Original WorkLog and ShiftAssignment records are preserved via legacy links.
    """
    WorkEntry = apps.get_model('worklogs', 'WorkEntry')
    count = WorkEntry.objects.count()
    WorkEntry.objects.all().delete()
    print(f"Reversed migration: Deleted {count} WorkEntry records")


class Migration(migrations.Migration):
    
    dependencies = [
        ('worklogs', '0011_create_workentry_model'),
        ('projects', '0003_projectshifttemplate_projectplannedday_and_more'),  # Latest projects migration
    ]
    
    operations = [
        migrations.RunPython(
            migrate_worklog_and_shiftassignment_data,
            reverse_code=reverse_migration,
        ),
    ]
