# Generated by Django 6.0 on 2026-01-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0013_delete_legacy_tables'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workentry',
            name='unique_employee_date_shift',
        ),
    ]
