# Generated by Django 6.0 on 2026-07-28 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0015_add_allowances_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEntryPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('photo', models.ImageField(upload_to='worklogs/photos/%Y/%m/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, default='', help_text='Optional description of the photo', max_length=200, verbose_name='Caption')),
                ('photo_type', models.CharField(choices=[('before', 'Before Work'), ('during', 'During Work'), ('after', 'After Work'), ('other', 'Other')], default='after', max_length=20, verbose_name='Photo Type')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='Taken At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_work_photos', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='worklogs.workentry', verbose_name='Work Entry')),
            ],
            options={
                'verbose_name': 'Work Entry Photo',
                'verbose_name_plural': 'Work Entry Photos',
                'ordering': ['taken_at'],
            },
        ),
    ]
