# Generated by Django 6.0 on 2026-08-30 18:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0014_agency_btw_number_agency_city_agency_contact_email_and_more'),
        ('worklogs', '0016_add_customer_role_and_work_entry_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_paid', models.BooleanField(default=True, help_text='Paid leave still accrues wages on the payslip.', verbose_name='Is Paid')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requires Approval')),
                ('max_days_per_year', models.PositiveIntegerField(blank=True, help_text='Leave blank for no annual cap.', null=True, verbose_name='Max Days Per Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text='e.g. "Week 34 2026" or "Augustus 2026".', max_length=120, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid At')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Payroll Period',
                'verbose_name_plural': 'Payroll Periods',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total Hours')),
                ('base_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Base Pay')),
                ('surcharge_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Surcharge Pay')),
                ('allowance_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Allowance Pay')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wallet advances repaid in this period, and any manual deductions.', max_digits=10, verbose_name='Deductions')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Gross Pay')),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross pay minus deductions. Payroll tax is handled by the external payroll provider, not by this system.', max_digits=10, verbose_name='Net Pay')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('paid', 'Paid')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='employees.employeeprofile', verbose_name='Employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payrollperiod', verbose_name='Payroll Period')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayslipLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hr.payslip', verbose_name='Payslip')),
                ('work_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslip_lines', to='worklogs.workentry', verbose_name='Work Entry')),
            ],
            options={
                'verbose_name': 'Payslip Line',
                'verbose_name_plural': 'Payslip Lines',
                'ordering': ['work_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, default='', verbose_name='Review Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employeeprofile', verbose_name='Employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype', verbose_name='Leave Type')),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_leavereq_employe_1b7929_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='hr_leaverequest_end_after_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='hr_payrollperiod_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('start_date', 'end_date'), name='hr_payrollperiod_unique_range'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('period', 'employee'), name='hr_payslip_unique_employee_per_period'),
        ),
        migrations.AddConstraint(
            model_name='payslipline',
            constraint=models.UniqueConstraint(fields=('payslip', 'work_entry'), name='hr_payslipline_unique_entry_per_payslip'),
        ),
    ]
