# Generated by Django 6.0 on 2025-12-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_make_financial_fields_optional'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to='customers.outfolder', verbose_name='Assigned Supervisors'),
        ),
    ]
