# Generated by Django 6.0 on 2026-09-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_ancillary_to_goods_sold_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequiredcertificate',
            options={'ordering': ['certificate_type_id'], 'verbose_name': 'Project Required Certificate', 'verbose_name_plural': 'Project Required Certificates'},
        ),
    ]
