import os
import sys
import django
import random
from django.core.files import File

# Set up Django environment
sys.path.append('/Users/mustafa/Desktop/ProTotaalService/CKMServices/Backend')
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from apps.customers.models import Customer
from apps.worklogs.models import WorkEntry, WorkEntryPhoto

# Image paths generated by AI
logo_path = "/Users/mustafa/.gemini/antigravity-ide/brain/39ddc760-b99a-4402-bedd-eea88ffa105e/customer_logo_uvastgoed_1785345908023.png"
photo1_path = "/Users/mustafa/.gemini/antigravity-ide/brain/39ddc760-b99a-4402-bedd-eea88ffa105e/work_construction_site_1785345857040.png"
photo2_path = "/Users/mustafa/.gemini/antigravity-ide/brain/39ddc760-b99a-4402-bedd-eea88ffa105e/work_plumbing_1785345873269.png"
photo3_path = "/Users/mustafa/.gemini/antigravity-ide/brain/39ddc760-b99a-4402-bedd-eea88ffa105e/work_painting_1785345890367.png"

work_photos = [
    (photo1_path, 'after', 'Cleaned up construction site'),
    (photo2_path, 'after', 'New plumbing installed'),
    (photo3_path, 'during', 'Painting in progress'),
]

customer = Customer.objects.filter(company_name='U Vastgoed').first()
if customer:
    print("Updating Customer Logo...")
    with open(logo_path, 'rb') as f:
        customer.logo.save('uvastgoed_logo.png', File(f), save=True)
    print("Logo updated!")

    entries = WorkEntry.objects.filter(project__customer=customer)
    print(f"Found {entries.count()} work entries. Adding photos...")
    
    count = 0
    for entry in entries:
        # Give ~30% of entries a photo
        if random.random() < 0.3:
            photo_info = random.choice(work_photos)
            
            with open(photo_info[0], 'rb') as f:
                photo_obj = WorkEntryPhoto(
                    work_entry=entry,
                    photo_type=photo_info[1],
                    caption=photo_info[2]
                )
                photo_obj.photo.save(os.path.basename(photo_info[0]), File(f), save=False)
                photo_obj.save()
            count += 1
            
    print(f"✅ Successfully added photos to {count} work entries!")
else:
    print("U Vastgoed customer not found!")
