# Generated by Django 6.0 on 2025-12-14 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('email_digest', models.BooleanField(default=False, help_text='Send daily digest instead of individual emails', verbose_name='Daily Email Digest')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp Notifications')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp Number')),
                ('quiet_hours_enabled', models.BooleanField(default=False, verbose_name='Quiet Hours Enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours Start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Quiet Hours End')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('notification_type', models.CharField(choices=[('credentials_created', 'Credentials Created'), ('profile_submitted', 'Profile Submitted'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('project_assigned', 'Project Assigned'), ('project_unassigned', 'Project Unassigned'), ('project_completed', 'Project Completed'), ('worklog_submitted', 'Work Log Submitted'), ('worklog_approved', 'Work Log Approved'), ('worklog_rejected', 'Work Log Rejected'), ('advance_requested', 'Advance Requested'), ('advance_approved', 'Advance Approved'), ('advance_rejected', 'Advance Rejected'), ('wallet_updated', 'Wallet Updated'), ('invoice_generated', 'Invoice Generated'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('certificate_expiring', 'Certificate Expiring'), ('certificate_expired', 'Certificate Expired'), ('system', 'System Notification'), ('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert')], db_index=True, max_length=30, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Reference Type')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='Reference ID')),
                ('action_url', models.CharField(blank=True, default='', max_length=500, verbose_name='Action URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push Sent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
