# Generated by Django 6.0 on 2025-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('employees', 'Employees'), ('worklogs', 'Work Logs'), ('certificates', 'Certificates'), ('invoices', 'Invoices'), ('projects', 'Projects'), ('wallet', 'Wallet'), ('system', 'System')], db_index=True, default='system', help_text='Category for grouping in UI', max_length=20, verbose_name='Category'),
        ),
    ]
