# Generated by Django 6.0 on 2026-09-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('credentials_created', 'Credentials Created'), ('profile_submitted', 'Profile Submitted'), ('profile_approved', 'Profile Approved'), ('profile_rejected', 'Profile Rejected'), ('project_assigned', 'Project Assigned'), ('project_unassigned', 'Project Unassigned'), ('project_completed', 'Project Completed'), ('worklog_submitted', 'Work Log Submitted'), ('worklog_approved', 'Work Log Approved'), ('worklog_rejected', 'Work Log Rejected'), ('advance_requested', 'Advance Requested'), ('advance_approved', 'Advance Approved'), ('advance_rejected', 'Advance Rejected'), ('wallet_updated', 'Wallet Updated'), ('invoice_generated', 'Invoice Generated'), ('invoice_sent', 'Invoice Sent'), ('invoice_paid', 'Invoice Paid'), ('invoice_overdue', 'Invoice Overdue'), ('credit_note_issued', 'Credit Note Issued'), ('supplier_invoice_due', 'Supplier Invoice Due'), ('vat_deadline', 'VAT Filing Deadline'), ('vat_requires_review', 'VAT Requires Review'), ('vat_period_finalized', 'VAT Period Finalized'), ('certificate_expiring', 'Certificate Expiring'), ('certificate_expired', 'Certificate Expired'), ('system', 'System Notification'), ('info', 'Information'), ('warning', 'Warning'), ('alert', 'Alert')], db_index=True, max_length=30, verbose_name='Type'),
        ),
    ]
