# Generated by Django 6.0 on 2026-09-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'ordering': ['user_id'], 'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preferences'},
        ),
    ]
