# Generated by Django 6.0 on 2025-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('company_name', models.CharField(default='Pro Totaal Service', max_length=200)),
                ('company_emails', models.JSONField(blank=True, default=list, help_text="List of company emails, e.g. [{'label': 'Info', 'email': 'info@company.nl'}]")),
                ('company_phones', models.JSONField(blank=True, default=list, help_text="List of company phone numbers, e.g. [{'label': 'Main', 'number': '+31 20 123 4567'}]")),
                ('company_address', models.TextField(default='Businesspark 10, Amsterdam')),
                ('week_starts_on', models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', help_text='Day the work week starts on', max_length=10)),
                ('week_start_hour', models.CharField(default='06:00', help_text='Hour the work week starts (HH:MM format)', max_length=5)),
                ('default_break_minutes', models.PositiveIntegerField(default=30, help_text='Default break duration in minutes')),
                ('notify_new_employee', models.BooleanField(default=True)),
                ('notify_pending_approvals', models.BooleanField(default=True)),
                ('notify_weekly_summary', models.BooleanField(default=False)),
                ('notify_certificate_expiry', models.BooleanField(default=True)),
                ('certificate_expiry_days', models.PositiveIntegerField(default=30)),
                ('smtp_enabled', models.BooleanField(default=False, help_text='Enable email sending via Gmail SMTP')),
                ('smtp_email', models.EmailField(blank=True, default='', help_text='Gmail address for sending emails', max_length=254)),
                ('smtp_password', models.CharField(blank=True, default='', help_text='Gmail App Password (not regular password)', max_length=100)),
                ('notification_recipients', models.JSONField(blank=True, default=list, help_text="List of emails to receive notifications, e.g. ['admin@company.nl']")),
                ('email_on_employees', models.BooleanField(default=True, help_text='Send email for employee-related notifications')),
                ('email_on_worklogs', models.BooleanField(default=False, help_text='Send email for worklog submissions')),
                ('email_on_certificates', models.BooleanField(default=True, help_text='Send email for certificate expiry warnings')),
                ('email_on_invoices', models.BooleanField(default=False, help_text='Send email for invoice notifications')),
                ('email_on_high_priority', models.BooleanField(default=True, help_text='Always send email for high/urgent priority')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
