# Generated by Django 6.0 on 2025-12-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_notification_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='category_recipients',
            field=models.JSONField(blank=True, default=dict, help_text="Email recipients per category, e.g.:\n        {\n            'employees': ['hr@company.nl'],\n            'worklogs': ['manager@company.nl', 'admin@company.nl'],\n            'certificates': ['hr@company.nl'],\n            'invoices': ['finance@company.nl'],\n            'projects': [],\n            'system': ['admin@company.nl']\n        }"),
        ),
    ]
