# Generated by Django 6.0 on 2025-12-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_category_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='frontend_url',
            field=models.URLField(default='http://localhost:3000', help_text='Frontend base URL for email links, e.g. https://admin.prototaalservice.nl'),
        ),
    ]
