# Generated by Django 6.0 on 2025-12-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_frontend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='firebase_enabled',
            field=models.BooleanField(default=False, help_text='Enable Firebase Cloud Messaging for push notifications'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='firebase_server_key',
            field=models.TextField(blank=True, default='', help_text='Firebase Server Key from Firebase Console → Project Settings → Cloud Messaging'),
        ),
    ]
