# Generated by Django 6.0 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_firebase_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='company_address',
            field=models.TextField(default='Rotterdam, Netherlands'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='company_name',
            field=models.CharField(default='CKM Services', max_length=200),
        ),
    ]
