# Generated by Django 6.0 on 2026-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_systemconfig_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='site_url',
            field=models.URLField(blank=True, default='', help_text='Base URL of the dashboard, used to build links in outgoing email (e.g. https://dashboard.ckmservices.nl). Leave blank to disable emailed password-reset links.', max_length=300, verbose_name='Public site URL'),
        ),
    ]
