# Generated by Django 6.0 on 2026-08-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemconfig_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='firebase_credentials_json',
            field=models.TextField(blank=True, default='', help_text='Contents of the service-account key file downloaded from Firebase Console → Project settings → Service accounts. Required for FCM HTTP v1.', verbose_name='Firebase Service Account JSON'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='firebase_project_id',
            field=models.CharField(blank=True, default='', help_text='The Firebase project id, e.g. "ckm-services-1234". Required for FCM HTTP v1.', max_length=200, verbose_name='Firebase Project ID'),
        ),
    ]
