# Generated by Django 6.0 on 2026-08-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_systemconfig_firebase_credentials_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='site_url',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='frontend_url',
            field=models.URLField(default='http://localhost:3000', help_text='Public base URL of the dashboard, e.g. https://dashboard.ckmservices.nl. Used for links in notification and password-reset emails.', verbose_name='Dashboard URL'),
        ),
    ]
