# Generated by Django 6.0 on 2026-09-01 22:19

import apps.core.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_duplicate_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='company_bic',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_btw_number',
            field=models.CharField(blank=True, default='', help_text='e.g. NL869591071B01. Printed on every invoice.', max_length=20, verbose_name='BTW-identificatienummer'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_country',
            field=models.CharField(blank=True, default='Nederland', max_length=100),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_iban',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', help_text='Encrypted at rest; printed on invoices so customers can pay.', max_length=512, plaintext_max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_kvk_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='KvK number'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', help_text="As registered with the KvK, e.g. 'CKMcleaning VOF'.", max_length=200, verbose_name='Legal name'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Shown on invoices and credit notes.', null=True, upload_to='company/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_postal_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='credit_note_number_prefix',
            field=models.CharField(default='CN', help_text='Credit notes are numbered <prefix><year>-<sequence>.', max_length=10),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='invoice_footer_text',
            field=models.TextField(blank=True, default='', help_text='Printed at the foot of every invoice.'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='invoice_number_prefix',
            field=models.CharField(default='F', help_text='Outgoing invoices are numbered <prefix><year>-<sequence>.', max_length=10),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='invoice_payment_terms_days',
            field=models.PositiveIntegerField(default=14, help_text='Due date = issue date + this many days.', verbose_name='Payment terms (days)'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='invoice_reverse_charge_text',
            field=models.CharField(default='Btw verlegd', help_text='Wording required on a reverse-charged invoice.', max_length=200),
        ),
    ]
