# Generated by Django 6.0 on 2026-09-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_systemconfig_company_bic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['id'], 'verbose_name': 'System Configuration', 'verbose_name_plural': 'System Configuration'},
        ),
    ]
