# Generated by Django 6.0 on 2026-08-16 21:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0004_agencyinvoice_agencyinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
                ('name_nl', models.CharField(blank=True, default='', help_text='Dutch translation for reports', max_length=200, verbose_name='Dutch Name')),
                ('code', models.CharField(help_text='Short code, e.g. RENT, SOFTWARE', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category_type', models.CharField(choices=[('fixed', 'Fixed (Recurring)'), ('variable', 'Variable (One-time)')], default='variable', max_length=20, verbose_name='Type')),
                ('icon', models.CharField(blank=True, default='receipt', help_text='Lucide icon name for UI display', max_length=50, verbose_name='Icon Name')),
                ('color', models.CharField(blank=True, default='#6B7280', max_length=10, verbose_name='Color')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('vendor_name', models.CharField(help_text='Who you paid (e.g., KPN, Ziggo, Albert Heijn)', max_length=300, verbose_name='Vendor / Supplier')),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (excl. BTW)')),
                ('vat_rate', models.DecimalField(choices=[('0.00', '0% (Vrijgesteld)'), ('9.00', '9% (Laag tarief)'), ('21.00', '21% (Standaard)')], decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='BTW Rate (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='BTW Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount (incl. BTW)')),
                ('expense_date', models.DateField(db_index=True, verbose_name='Expense Date')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pin', 'Pin / Debit Card'), ('credit_card', 'Credit Card'), ('direct_debit', 'Automatische Incasso'), ('ideal', 'iDEAL'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('is_paid', models.BooleanField(default=True, help_text='Whether this expense has been paid', verbose_name='Is Paid')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('reference_number', models.CharField(blank=True, default='', help_text="Vendor's invoice or reference number", max_length=100, verbose_name='Reference / Invoice Number')),
                ('receipt_file', models.FileField(blank=True, help_text='Upload receipt image or PDF', null=True, upload_to='expenses/receipts/%Y/%m/', verbose_name='Receipt / Bill')),
                ('ocr_extracted_data', models.JSONField(blank=True, help_text='Raw OCR extraction result for reference', null=True, verbose_name='OCR Extracted Data')),
                ('ocr_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OCR Confidence (%)')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring Expense')),
                ('recurring_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='', max_length=20, verbose_name='Recurring Frequency')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('source', models.CharField(choices=[('customer_invoice', 'Customer Invoice'), ('agency_invoice', 'Agency Invoice (Incoming)'), ('other', 'Other Income')], default='other', max_length=20, verbose_name='Source')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('payer_name', models.CharField(blank=True, default='', help_text='Who paid you', max_length=300, verbose_name='Payer / Source')),
                ('amount_excl_vat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (excl. BTW)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='BTW Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount (incl. BTW)')),
                ('received_date', models.DateField(db_index=True, verbose_name='Received Date')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pin', 'Pin / Debit Card'), ('credit_card', 'Credit Card'), ('direct_debit', 'Automatische Incasso'), ('ideal', 'iDEAL'), ('other', 'Other')], default='bank_transfer', max_length=20, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Reference Number')),
                ('payment_proof', models.FileField(blank=True, help_text='Bank transfer confirmation', null=True, upload_to='income/proofs/%Y/%m/', verbose_name='Payment Proof')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='invoices.invoice', verbose_name='Customer Invoice')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Income Record',
                'verbose_name_plural': 'Income Records',
                'ordering': ['-received_date'],
            },
        ),
    ]
