# Generated by Django 6.0 on 2026-09-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ancillary_to_goods_sold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='deductible_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Null means not established — full deduction is never assumed.', max_digits=5, null=True, verbose_name='Deductible VAT (%)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_states_reverse_charge',
            field=models.BooleanField(blank=True, help_text='Evidence, not a conclusion: wording alone does not decide the treatment.', null=True, verbose_name='Invoice states "btw verlegd"?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_design_work',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_guarding_or_rental',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_physical_work_on_immovable_property',
            field=models.BooleanField(blank=True, help_text='The condition the Dutch reverse-charge scheme turns on.', null=True, verbose_name='Physical work on immovable property?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_staff_lending_or_subcontracting',
            field=models.BooleanField(blank=True, help_text='Leave unset if unknown; the transaction is then held for review.', null=True, verbose_name='Staff lending or subcontracting?'),
        ),
        migrations.AddField(
            model_name='expense',
            name='lent_to_subcontractor_working_own_premises',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='majority_work_in_own_workshop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_notes',
            field=models.TextField(blank=True, default='', help_text='Evidence for the classification: invoice wording, what the work was.'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='UNKNOWN', help_text='Defaults to UNKNOWN. Nothing is assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='ancillary_to_goods_sold',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='deductible_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Null means not established — full deduction is never assumed.', max_digits=5, null=True, verbose_name='Deductible VAT (%)'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='invoice_states_reverse_charge',
            field=models.BooleanField(blank=True, help_text='Evidence, not a conclusion: wording alone does not decide the treatment.', null=True, verbose_name='Invoice states "btw verlegd"?'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_design_work',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_guarding_or_rental',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_physical_work_on_immovable_property',
            field=models.BooleanField(blank=True, help_text='The condition the Dutch reverse-charge scheme turns on.', null=True, verbose_name='Physical work on immovable property?'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_staff_lending_or_subcontracting',
            field=models.BooleanField(blank=True, help_text='Leave unset if unknown; the transaction is then held for review.', null=True, verbose_name='Staff lending or subcontracting?'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='lent_to_subcontractor_working_own_premises',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='majority_work_in_own_workshop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='vat_notes',
            field=models.TextField(blank=True, default='', help_text='Evidence for the classification: invoice wording, what the work was.'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='vat_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='UNKNOWN', help_text='Defaults to UNKNOWN. Nothing is assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
    ]
