# Generated by Django 6.0 on 2026-09-01 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_vat_classification_facts'),
        ('expenses', '0002_vat_classification_facts'),
        ('invoices', '0012_backfill_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='incoming_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='invoices.incominginvoice', verbose_name='Supplier invoice'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by_employee',
            field=models.ForeignKey(blank=True, help_text='Set when an employee paid this out of pocket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='employees.employeeprofile', verbose_name='Paid by employee'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursement_status',
            field=models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'To be reimbursed'), ('reimbursed', 'Reimbursed')], db_index=True, default='not_applicable', max_length=20, verbose_name='Reimbursement'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date', 'category'], name='expense_date_category_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['reimbursement_status', 'paid_by_employee'], name='expense_reimbursement_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vendor_name', 'expense_date'], name='expense_vendor_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('reference_number', ''), _negated=True)), fields=('vendor_name', 'reference_number', 'total_amount'), name='unique_expense_per_vendor_reference'),
        ),
    ]
