# Generated by Django 6.0 on 2025-12-14 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Certificate Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_required', models.BooleanField(default=False, help_text='If true, employees must have this certificate', verbose_name='Is Required')),
                ('has_expiry', models.BooleanField(default=True, help_text='If true, certificate has an expiration date', verbose_name='Has Expiry Date')),
                ('has_diploma_number', models.BooleanField(default=True, help_text='If true, certificate has a diploma/certificate number', verbose_name='Has Diploma Number')),
                ('ocr_field_name', models.CharField(blank=True, default='', help_text='Field name for OCR extraction (e.g., diploma_number)', max_length=50, verbose_name='OCR Field Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCertificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Certificate File')),
                ('diploma_number', models.CharField(blank=True, default='', help_text='Extracted via OCR, employee can manually correct', max_length=100, verbose_name='Diploma Number')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, default='', verbose_name='Admin Notes')),
                ('ocr_extracted_data', models.JSONField(blank=True, null=True, verbose_name='OCR Extracted Data')),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_certificates', to='certificates.certificatetype', verbose_name='Certificate Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employeeprofile', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Employee Certificate',
                'verbose_name_plural': 'Employee Certificates',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'certificate_type')},
            },
        ),
        migrations.CreateModel(
            name='VCAInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('has_vca_basis', models.BooleanField(default=False, verbose_name='Has VCA Basis')),
                ('has_vca_vol', models.BooleanField(default=False, verbose_name='Has VCA VOL (V.O.L.)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vca_info', to='employees.employeeprofile', verbose_name='Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('vca_basis_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vca_basis_for', to='certificates.employeecertificate', verbose_name='VCA Basis Certificate')),
                ('vca_vol_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vca_vol_for', to='certificates.employeecertificate', verbose_name='VCA VOL Certificate')),
            ],
            options={
                'verbose_name': 'VCA Information',
                'verbose_name_plural': 'VCA Information',
            },
        ),
    ]
