# Generated by Django 6.0 on 2025-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecertificate',
            name='certificate_file_back',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate File (Back)'),
        ),
        migrations.AlterField(
            model_name='employeecertificate',
            name='certificate_file',
            field=models.FileField(upload_to='certificates/', verbose_name='Certificate File (Front/PDF)'),
        ),
    ]
