# Generated by Django 6.0 on 2026-09-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_employeecertificate_certificate_file_back_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcainfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'VCA Information', 'verbose_name_plural': 'VCA Information'},
        ),
    ]
