# Generated by Django 6.0 on 2026-09-01 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'reference_type', 'reference_id'], name='wallet_txn_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_txn_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('reference_type', ''), _negated=True)), fields=('wallet', 'transaction_type', 'reference_type', 'reference_id'), name='unique_wallet_movement_per_source'),
        ),
    ]
