# Generated by Django 6.0 on 2026-09-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_agencywallet_options'),
        ('wallet', '0002_wallettransaction_wallet_txn_reference_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['employee_id'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterField(
            model_name='advancerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_requests', to='employees.employeeprofile', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='employees.employeeprofile', verbose_name='Employee'),
        ),
    ]
