# Generated by Django 6.0 on 2025-12-14 22:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Document Type Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Primary login identifier (set by admin, not editable by employee)', max_length=254, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('finance', 'Finance Manager'), ('operations', 'Operations Coordinator')], default='employee', max_length=20, verbose_name='Role')),
                ('is_first_login', models.BooleanField(default=True, help_text='True until employee completes profile', verbose_name='First Login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='incomplete', max_length=20, verbose_name='Profile Status')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('prefix_name', models.CharField(blank=True, default='', help_text='Optional prefix (e.g., van, de, van der)', max_length=20, verbose_name='Prefix Name')),
                ('initials', models.CharField(help_text='First letter(s) of name', max_length=10, verbose_name='Initials')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('birthplace', models.CharField(max_length=100, verbose_name='Birthplace')),
                ('bsn', models.CharField(help_text='Dutch national identification number (9 digits)', max_length=9, validators=[django.core.validators.RegexValidator(message='BSN must be exactly 9 digits', regex='^\\d{9}$')], verbose_name='BSN')),
                ('document_number', models.CharField(help_text='Can be extracted via OCR, employee can edit', max_length=50, verbose_name='Document Number')),
                ('document_expiry_date', models.DateField(verbose_name='Document Expiry Date (Geldig tot)')),
                ('id_document_front', models.ImageField(upload_to='employees/id_documents/front/', verbose_name='ID Document (Front)')),
                ('id_document_back', models.ImageField(upload_to='employees/id_documents/back/', verbose_name='ID Document (Back)')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[\\d\\s\\-]{10,20}$')], verbose_name='Phone Number')),
                ('address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('city', models.CharField(max_length=100, verbose_name='City (Plaats)')),
                ('iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN Number')),
                ('nationality', models.CharField(help_text='Searchable dropdown with all countries', max_length=100, verbose_name='Nationality')),
                ('contract_phase', models.CharField(blank=True, choices=[('phase_a', 'Phase A (Fase A)'), ('phase_b', 'Phase B (Fase B)'), ('phase_c', 'Phase C (Fase C)')], max_length=20, null=True, verbose_name='Contract Phase (Fase)')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Contract Start Date')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('has_drivers_license', models.BooleanField(default=False, verbose_name="Has Driver's License (Rijbewijs)")),
                ('drivers_license_front', models.ImageField(blank=True, null=True, upload_to='employees/drivers_license/front/', verbose_name="Driver's License (Front)")),
                ('drivers_license_back', models.ImageField(blank=True, null=True, upload_to='employees/drivers_license/back/', verbose_name="Driver's License (Back)")),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection Reason')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_employees', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('document_type', models.ForeignKey(help_text='Type of ID document (defined by admin)', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.documenttype', verbose_name='Document Type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee Profile',
                'verbose_name_plural': 'Employee Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
