# Generated by Django 6.0 on 2025-12-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='id_document_pdf',
            field=models.FileField(blank=True, help_text='Alternative to front+back images', null=True, upload_to='employees/id_documents/pdf/', verbose_name='ID Document (PDF)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='document_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Document Expiry Date (Geldig tot)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_document_back',
            field=models.ImageField(blank=True, null=True, upload_to='employees/id_documents/back/', verbose_name='ID Document (Back)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_document_front',
            field=models.ImageField(blank=True, null=True, upload_to='employees/id_documents/front/', verbose_name='ID Document (Front)'),
        ),
    ]
