# Generated by Django 6.0 on 2025-12-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeeprofile_id_document_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_document',
            field=models.FileField(blank=True, help_text='Signed employment contract document', null=True, upload_to='employees/contracts/', verbose_name='Contract Document'),
        ),
    ]
