# Generated by Django 6.0 on 2025-12-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_add_contract_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Agency Name')),
                ('code', models.CharField(help_text='Short code, e.g. RAND, TEMPO', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - never hard delete agencies', verbose_name='Is Deleted')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='Dutch-facing name, e.g. Onbepaalde tijd', max_length=100, unique=True, verbose_name='Contract Type Name')),
                ('code', models.CharField(help_text='Short code, e.g. NL_IND, NL_FT', max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('requires_end_date', models.BooleanField(default=False, help_text='If true, contract end date is mandatory', verbose_name='Requires End Date')),
                ('requires_agency', models.BooleanField(default=False, help_text='If true, admin must select an agency (e.g. for Uitzendkracht)', verbose_name='Requires Agency')),
                ('default_duration_months', models.PositiveIntegerField(blank=True, help_text='Optional default duration for fixed-term contracts', null=True, verbose_name='Default Duration (months)')),
                ('default_hours_type', models.CharField(blank=True, choices=[('full_time', 'Full-time (Voltijd)'), ('part_time', 'Part-time (Deeltijd)')], default='', max_length=20, verbose_name='Default Hours Type')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Contract Type',
                'verbose_name_plural': 'Contract Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='document_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Document Issue Date'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='drivers_license_categories',
            field=models.JSONField(blank=True, default=list, help_text="List of license categories, e.g. ['B', 'BE', 'C']", verbose_name="Driver's License Categories"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='drivers_license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name="Driver's License Expiry Date"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='drivers_license_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name="Driver's License Issue Date"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='drivers_license_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name="Driver's License Number"),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='has_travel_allowance',
            field=models.BooleanField(default=False, help_text='Enable travel cost tracking for this employee', verbose_name='Has Travel Allowance'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hourly Rate (€)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='travel_cost_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kilometer for travel reimbursement', max_digits=6, null=True, verbose_name='Travel Cost per KM (€)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='travel_hour_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of travel time to compensate', max_digits=5, null=True, verbose_name='Travel Hour Percentage (%)'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_agency',
            field=models.ForeignKey(blank=True, help_text='Current agency if employee is uitzendkracht', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employees', to='employees.agency', verbose_name='Current Agency'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='contract_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.contracttype', verbose_name='Contract Type'),
        ),
        migrations.CreateModel(
            name='EmployeeAgencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Null means currently active at this agency', null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Transfer Notes')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='employees.agency', verbose_name='Agency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_history', to='employees.employeeprofile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Agency History',
                'verbose_name_plural': 'Employee Agency History',
                'ordering': ['-start_date'],
            },
        ),
    ]
