# Generated by Django 6.0 on 2025-12-25 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_contract_agency_travel_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurchargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text="e.g., Weekend, Night Shift, King's Day", max_length=100, unique=True, verbose_name='Surcharge Name')),
                ('category', models.CharField(choices=[('weekend', 'Weekend'), ('night_shift', 'Night Shift'), ('holiday', 'Public Holiday'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Category')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('time_from', models.TimeField(blank=True, help_text='For time-based surcharges (e.g., night shift 22:00)', null=True, verbose_name='Start Time')),
                ('time_to', models.TimeField(blank=True, help_text='For time-based surcharges (e.g., night shift 06:00)', null=True, verbose_name='End Time')),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of days [0-6], 0=Monday, 6=Sunday. e.g., [5,6] for weekend', verbose_name='Days of Week')),
                ('specific_dates', models.JSONField(blank=True, default=list, help_text="List of dates in format ['MM-DD'] for recurring holidays, e.g., ['04-27'] for King's Day", verbose_name='Specific Dates')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Surcharge Type',
                'verbose_name_plural': 'Surcharge Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='agency',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base rate agency pays per hour', max_digits=8, verbose_name='Base Hourly Rate (€)'),
        ),
        migrations.AddField(
            model_name='agency',
            name='has_surcharges',
            field=models.BooleanField(default=False, help_text='Enable surcharge rules for weekends, nights, holidays', verbose_name='Has Percentage Surcharges'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='contract_document',
            field=models.FileField(blank=True, null=True, upload_to='employees/contracts/', verbose_name='Contract Document'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='document_expiry_date',
            field=models.DateField(verbose_name='Document Expiry Date (Geldig tot)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_document_back',
            field=models.ImageField(upload_to='employees/id_documents/back/', verbose_name='ID Document (Back)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_document_front',
            field=models.ImageField(upload_to='employees/id_documents/front/', verbose_name='ID Document (Front)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='id_document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='employees/id_documents/pdf/', verbose_name='ID Document (PDF)'),
        ),
        migrations.CreateModel(
            name='AgencyWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance (€)')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='All-time earnings', max_digits=12, verbose_name='Total Earned (€)')),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='employees.agency', verbose_name='Agency')),
            ],
            options={
                'verbose_name': 'Agency Wallet',
                'verbose_name_plural': 'Agency Wallets',
            },
        ),
        migrations.CreateModel(
            name='AgencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('work', 'Employee Work'), ('adjustment', 'Manual Adjustment'), ('invoice', 'Invoice Payment')], default='work', max_length=20, verbose_name='Transaction Type')),
                ('date', models.DateField(verbose_name='Work Date')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hours Worked')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Rate at time of work', max_digits=8, verbose_name='Base Rate (€)')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Amount (€)')),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Combined surcharges applied', max_digits=5, verbose_name='Total Surcharge (%)')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Surcharge Amount (€)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount (€)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('surcharges_applied', models.JSONField(blank=True, default=list, help_text='List of surcharge names that were applied', verbose_name='Surcharges Applied')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_transactions', to='employees.employeeprofile', verbose_name='Employee')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='employees.agencywallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Agency Transaction',
                'verbose_name_plural': 'Agency Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgencySurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='e.g., 20.00 for 20%', max_digits=5, verbose_name='Surcharge Percentage')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='employees.agency', verbose_name='Agency')),
                ('surcharge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_surcharges', to='employees.surchargetype', verbose_name='Surcharge Type')),
            ],
            options={
                'verbose_name': 'Agency Surcharge',
                'verbose_name_plural': 'Agency Surcharges',
                'ordering': ['agency', 'surcharge_type__sort_order'],
                'unique_together': {('agency', 'surcharge_type')},
            },
        ),
    ]
