# Generated by Django 6.0 on 2025-12-26 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_agency_billing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hourly Rate (€)')),
                ('effective_from', models.DateField(help_text='Date when this rate became effective', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this rate ended (null = current rate)', null=True, verbose_name='Effective To')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this rate change', verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_changes_made', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_history', to='employees.employeeprofile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee Rate History',
                'verbose_name_plural': 'Employee Rate Histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
