# Generated by Django 6.0 on 2025-12-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeratehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('contract_document', models.FileField(upload_to='employees/contracts/history/', verbose_name='Contract Document')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hourly Rate at Contract Time (€)')),
                ('effective_from', models.DateField(help_text='Date when this contract became effective', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this contract ended (null = current)', null=True, verbose_name='Effective To')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this contract', verbose_name='Notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to='employees.employeeprofile', verbose_name='Employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Employee Contract History',
                'verbose_name_plural': 'Employee Contract Histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
