# Generated by Django 6.0 on 2025-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeecontracthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(help_text='e.g., Ademlucht (mask), EPZ Toeslag, WZH Toeslag', max_length=100, unique=True, verbose_name='Allowance Name')),
                ('code', models.CharField(help_text='Short code for the allowance, e.g., MASK, EPZ, WZH', max_length=20, unique=True, verbose_name='Code')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default price per hour for this allowance', max_digits=10, verbose_name='Base Price (€)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
            ],
            options={
                'verbose_name': 'Allowance Type',
                'verbose_name_plural': 'Allowance Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
