# Generated by Django 6.0 on 2025-12-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_allowancetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_add_allowances',
            field=models.BooleanField(default=False, help_text='Allow employee to add allowances (Toeslag) to work logs', verbose_name='Can Add Allowances'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='receives_surcharges',
            field=models.BooleanField(default=False, help_text='Employee receives surcharge payments (night/weekend rates)', verbose_name='Receives Surcharges'),
        ),
    ]
