# Generated by Django 6.0 on 2025-12-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employeeprofile_can_add_allowances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_approvals',
            field=models.BooleanField(default=True, help_text='Receive notifications when worklogs are approved/rejected', verbose_name='Notify Approvals/Rejections'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_certificate_expiry',
            field=models.BooleanField(default=True, help_text='Receive notifications when certificates are expiring', verbose_name='Notify Certificate Expiry'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_contract_expiry',
            field=models.BooleanField(default=True, help_text='Receive notifications when contract is expiring', verbose_name='Notify Contract Expiry'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_shift_changes',
            field=models.BooleanField(default=True, help_text='Receive notifications about shift updates', verbose_name='Notify Shift Changes'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='notify_worklog_reminders',
            field=models.BooleanField(default=True, help_text='Receive reminders to log work hours', verbose_name='Notify WorkLog Reminders'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='push_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Master toggle for all push notifications', verbose_name='Push Notifications Enabled'),
        ),
    ]
