# Generated by Django 6.0 on 2026-01-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_add_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surchargetype',
            name='min_hours_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For overtime: surcharge applies only to hours above this threshold per day (e.g., 9.0 means hours > 9 get the surcharge)', max_digits=4, null=True, verbose_name='Minimum Hours Threshold'),
        ),
        migrations.AlterField(
            model_name='surchargetype',
            name='category',
            field=models.CharField(choices=[('weekend', 'Weekend'), ('night_shift', 'Night Shift'), ('holiday', 'Public Holiday'), ('overtime', 'Overtime (Overwerk)'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='surchargetype',
            name='name',
            field=models.CharField(help_text="e.g., Weekend, Night Shift, King's Day, Overwerk", max_length=100, unique=True, verbose_name='Surcharge Name'),
        ),
    ]
