# Generated by Django 6.0 on 2026-07-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_remove_customerallowancesurcharge_day_percentages_and_more'),
        ('employees', '0012_add_overtime_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='For customer portal users - links this account to a customer company', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='customers.customer', verbose_name='Linked Customer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('employee', 'Employee'), ('finance', 'Finance Manager'), ('operations', 'Operations Coordinator'), ('customer', 'Customer Portal User')], default='employee', max_length=20, verbose_name='Role'),
        ),
    ]
