# Generated by Django 6.0 on 2026-08-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_add_customer_role_and_work_entry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='btw_number',
            field=models.CharField(blank=True, default='', help_text='VAT identification number (e.g. NL123456789B01)', max_length=20, verbose_name='BTW Number'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Primary contact person at the agency', max_length=200, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='agency',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, default='Netherlands', max_length=100, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='house_number',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='House Number'),
        ),
        migrations.AddField(
            model_name='agency',
            name='house_number_addition',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='House Number Addition'),
        ),
        migrations.AddField(
            model_name='agency',
            name='iban',
            field=models.CharField(blank=True, default='', help_text='Bank account number for payments', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='agency',
            name='kvk_number',
            field=models.CharField(blank=True, default='', help_text='Chamber of Commerce registration number', max_length=20, verbose_name='KvK Number'),
        ),
        migrations.AddField(
            model_name='agency',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Postcode'),
        ),
        migrations.AddField(
            model_name='agency',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Street Name'),
        ),
    ]
