# Generated by Django 6.0 on 2026-09-01 21:14

import apps.core.encryption
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_surcharge_percent_of_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='iban',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', help_text='Bank account number for payments', max_length=512, plaintext_max_length=34, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='bsn',
            field=apps.core.encryption.EncryptedCharField(help_text='Dutch national identification number (9 digits)', max_length=512, plaintext_max_length=9, validators=[django.core.validators.RegexValidator(message='BSN must be exactly 9 digits', regex='^\\d{9}$')], verbose_name='BSN'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='document_number',
            field=apps.core.encryption.EncryptedCharField(help_text='Can be extracted via OCR, employee can edit', max_length=512, plaintext_max_length=50, verbose_name='Document Number'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='drivers_license_number',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', max_length=512, plaintext_max_length=50, verbose_name="Driver's License Number"),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='iban',
            field=apps.core.encryption.EncryptedCharField(max_length=512, plaintext_max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN Number'),
        ),
    ]
