# Generated by Django 6.0 on 2026-09-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_vat_classification_facts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencywallet',
            options={'ordering': ['agency_id'], 'verbose_name': 'Agency Wallet', 'verbose_name_plural': 'Agency Wallets'},
        ),
    ]
