# Generated by Django 6.0 on 2025-12-14 22:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='customers/logos/', verbose_name='Company Logo')),
                ('address', models.CharField(max_length=255, verbose_name='Street Address')),
                ('postcode', models.CharField(max_length=10, verbose_name='Postcode')),
                ('city', models.CharField(max_length=100, verbose_name='City (Plaats)')),
                ('country', models.CharField(default='Netherlands', max_length=100, verbose_name='Country')),
                ('iban', models.CharField(max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN')),
                ('g_rekening', models.CharField(blank=True, default='', help_text='Special IBAN for G-account', max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='G-Rekeningnummer')),
                ('btw_number', models.CharField(help_text='Dutch VAT number', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Dutch BTW number (e.g., NL123456789B01)', regex='^NL\\d{9}B\\d{2}$')], verbose_name='BTW Number')),
                ('kvk_number', models.CharField(help_text='Chamber of Commerce number', max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid KvK number (8 digits)', regex='^\\d{8}$')], verbose_name='KvK Number')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('fax', 'Fax'), ('mobile', 'Mobile')], max_length=20, verbose_name='Contact Type')),
                ('value', models.CharField(max_length=200, verbose_name='Contact Value')),
                ('label', models.CharField(blank=True, default='', help_text="E.g., 'Main', 'Billing', 'Support'", max_length=50, verbose_name='Label')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
                'ordering': ['-is_primary', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='Outfolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('company_name', models.CharField(help_text='Company name this outfolder works with', max_length=200, verbose_name='Company Name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfolders', to='customers.customer', verbose_name='Customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Outfolder',
                'verbose_name_plural': 'Outfolders',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OutfolderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('mobile', 'Mobile')], max_length=20, verbose_name='Contact Type')),
                ('value', models.CharField(max_length=200, verbose_name='Contact Value')),
                ('label', models.CharField(blank=True, default='', max_length=50, verbose_name='Label')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Is Primary')),
                ('outfolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.outfolder', verbose_name='Outfolder')),
            ],
            options={
                'verbose_name': 'Outfolder Contact',
                'verbose_name_plural': 'Outfolder Contacts',
                'ordering': ['-is_primary', 'contact_type'],
            },
        ),
    ]
