# Generated by Django 6.0 on 2025-12-22 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='btw_number',
            field=models.CharField(blank=True, default='', help_text='Dutch VAT number', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Dutch BTW number (e.g., NL123456789B01)', regex='^NL\\d{9}B\\d{2}$')], verbose_name='BTW Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kvk_number',
            field=models.CharField(blank=True, default='', help_text='Chamber of Commerce number', max_length=8, validators=[django.core.validators.RegexValidator(message='Enter a valid KvK number (8 digits)', regex='^\\d{8}$')], verbose_name='KvK Number'),
        ),
    ]
