# Generated by Django 6.0 on 2025-12-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_make_financial_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Service Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='customers.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_rates', to='customers.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Customer Service Rate',
                'verbose_name_plural': 'Customer Service Rates',
                'ordering': ['service__name'],
                'unique_together': {('customer', 'service')},
            },
        ),
    ]
