# Generated by Django 6.0 on 2025-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_service_customerservicerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default='SERVICE', max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Service Name'),
        ),
    ]
