# Generated by Django 6.0 on 2025-12-26 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_service_code_alter_service_name'),
        ('employees', '0005_add_agency_billing_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='base_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='Base Hourly Rate'),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_surcharges',
            field=models.BooleanField(default=False, verbose_name='Enable Percentage Surcharges'),
        ),
        migrations.CreateModel(
            name='CustomerSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('percentage', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Percentage (%)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='customers.customer', verbose_name='Customer')),
                ('surcharge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_surcharges', to='employees.surchargetype', verbose_name='Surcharge Type')),
            ],
            options={
                'verbose_name': 'Customer Surcharge',
                'verbose_name_plural': 'Customer Surcharges',
                'ordering': ['surcharge_type__name'],
                'unique_together': {('customer', 'surcharge_type')},
            },
        ),
    ]
