# Generated by Django 6.0 on 2025-12-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_employeecertificate_certificate_file_back_and_more'),
        ('customers', '0005_customer_base_hourly_rate_customer_has_surcharges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='required_certificates',
            field=models.ManyToManyField(blank=True, help_text='Certificates that employees must have to perform this service', related_name='required_for_services', to='certificates.certificatetype', verbose_name='Required Certificates'),
        ),
    ]
