# Generated by Django 6.0 on 2025-12-26 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_service_required_certificates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('contract_document', models.FileField(upload_to='customers/contracts/history/', verbose_name='Contract Document')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Hourly Rate (€)')),
                ('effective_from', models.DateField(help_text='Date when this contract becomes effective', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this contract ended (null = current)', null=True, verbose_name='Effective To')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_history', to='customers.customer', verbose_name='Customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_contracts_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Customer Contract History',
                'verbose_name_plural': 'Customer Contract Histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (€)')),
                ('effective_from', models.DateField(help_text='Date when this rate becomes effective', verbose_name='Effective From')),
                ('effective_to', models.DateField(blank=True, help_text='Date when this rate ended (null = current)', null=True, verbose_name='Effective To')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_rates_changed', to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rate_history', to='customers.customer', verbose_name='Customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_rate_history', to='customers.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Customer Service Rate History',
                'verbose_name_plural': 'Customer Service Rate Histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
    ]
