# Generated by Django 6.0 on 2025-12-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customercontracthistory_customerserviceratehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontracthistory',
            name='service_rates_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot of all service rates at the time of this contract', verbose_name='Service Rates Snapshot'),
        ),
    ]
