# Generated by Django 6.0 on 2025-12-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customercontracthistory_service_rates_snapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='base_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='customercontracthistory',
            name='base_hourly_rate',
        ),
    ]
