# Generated by Django 6.0 on 2025-12-26 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_customer_base_hourly_rate_and_more'),
        ('employees', '0008_allowancetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use default price from allowance type', max_digits=10, null=True, verbose_name='Custom Price (€)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('apply_surcharges', models.BooleanField(default=True, help_text='Whether surcharges (weekend, holiday) apply to this allowance', verbose_name='Apply Surcharges')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_allowances', to='employees.allowancetype', verbose_name='Allowance Type')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='customers.customer', verbose_name='Customer')),
                ('enabled_surcharges', models.ManyToManyField(blank=True, help_text='Specific surcharges that apply to this allowance (if apply_surcharges is True)', related_name='customer_allowances_enabled', to='employees.surchargetype', verbose_name='Enabled Surcharges')),
            ],
            options={
                'verbose_name': 'Customer Allowance',
                'verbose_name_plural': 'Customer Allowances',
                'ordering': ['allowance_type__name'],
                'unique_together': {('customer', 'allowance_type')},
            },
        ),
    ]
