# Generated by Django 6.0 on 2025-12-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerallowance'),
        ('employees', '0008_allowancetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gratuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (€)')),
                ('date_received', models.DateField(help_text='Date when admin received the gratuity from customer', verbose_name='Date Received')),
                ('date_work_done', models.DateField(blank=True, help_text='Optional: Date when the work was performed', null=True, verbose_name='Date Work Done')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment to Employee'), ('paid', 'Paid to Employee')], default='pending', max_length=20, verbose_name='Status')),
                ('paid_to_employee_date', models.DateField(blank=True, help_text='Date when the gratuity was paid to the employee', null=True, verbose_name='Paid to Employee Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratuities', to='customers.customer', verbose_name='Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratuities', to='employees.employeeprofile', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Gratuity',
                'verbose_name_plural': 'Gratuities',
                'ordering': ['-date_received'],
            },
        ),
    ]
