# Generated by Django 6.0 on 2025-12-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_gratuity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Holiday Date')),
                ('name', models.CharField(max_length=100, verbose_name='Holiday Name')),
                ('country', models.CharField(default='NL', max_length=10, verbose_name='Country Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
    ]
