# Generated by Django 6.0 on 2025-12-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_add_holiday_calendar'),
        ('employees', '0009_employeeprofile_can_add_allowances_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerallowance',
            options={'ordering': ['custom_name', 'allowance_type__name'], 'verbose_name': 'Customer Allowance', 'verbose_name_plural': 'Customer Allowances'},
        ),
        migrations.AlterUniqueTogether(
            name='customerallowance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customerallowance',
            name='custom_name',
            field=models.CharField(blank=True, default='', help_text='Custom allowance name specific to this customer (used if allowance_type is empty)', max_length=100, verbose_name='Custom Name'),
        ),
        migrations.AddField(
            model_name='customerallowance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per hour for this allowance', max_digits=10, verbose_name='Price (€/hr)'),
        ),
        migrations.AddField(
            model_name='customerservicerate',
            name='apply_surcharges',
            field=models.BooleanField(default=True, help_text='Whether weekend/night/holiday surcharges apply to this service', verbose_name='Apply Surcharges'),
        ),
        migrations.AlterField(
            model_name='customerallowance',
            name='allowance_type',
            field=models.ForeignKey(blank=True, help_text='Select a global allowance type OR use custom_name for customer-specific allowance', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_allowances', to='employees.allowancetype', verbose_name='Allowance Type'),
        ),
        migrations.AlterField(
            model_name='customerallowance',
            name='apply_surcharges',
            field=models.BooleanField(default=False, help_text='Whether surcharges (weekend, holiday) apply to this allowance', verbose_name='Apply Surcharges'),
        ),
        migrations.RemoveField(
            model_name='customerallowance',
            name='custom_price',
        ),
        migrations.CreateModel(
            name='CustomerServiceSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Custom surcharge percentage for this service', max_digits=5, verbose_name='Percentage (%)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('customer_service_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_surcharges', to='customers.customerservicerate', verbose_name='Customer Service Rate')),
                ('surcharge_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_service_surcharges', to='employees.surchargetype', verbose_name='Surcharge Type')),
            ],
            options={
                'verbose_name': 'Customer Service Surcharge',
                'verbose_name_plural': 'Customer Service Surcharges',
                'ordering': ['surcharge_type__name'],
                'unique_together': {('customer_service_rate', 'surcharge_type')},
            },
        ),
    ]
