# Generated by Django 6.0 on 2025-12-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_reorganize_surcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerallowance',
            name='custom_code',
            field=models.CharField(blank=True, default='', help_text="Short code for this allowance (e.g., 'MASK', 'HAZ')", max_length=20, verbose_name='Custom Code'),
        ),
        migrations.AlterField(
            model_name='customerallowancesurcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customerallowancesurcharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customerservicesurcharge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customerservicesurcharge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At'),
        ),
    ]
