# Generated by Django 6.0 on 2025-12-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_add_custom_code_to_customerallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='manager_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manager First Name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='manager_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Manager Last Name'),
        ),
    ]
