# Generated by Django 6.0 on 2026-09-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_remove_customerallowancesurcharge_day_percentages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerallowancesurcharge',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=125.0, help_text='Percentage OF the hourly rate, not on top of it. 150 means the rate for those hours becomes 1.5x base (EUR 10/h -> EUR 15/h). 100 means no uplift.', max_digits=6, verbose_name='Percentage of hourly rate (%)'),
        ),
        migrations.AlterField(
            model_name='customerservicesurcharge',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=125.0, help_text='Percentage OF the hourly rate, not on top of it. 150 means the rate for those hours becomes 1.5x base (EUR 10/h -> EUR 15/h). 100 means no uplift.', max_digits=6, verbose_name='Percentage of hourly rate (%)'),
        ),
        migrations.AlterField(
            model_name='customersurcharge',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=125.0, help_text='Percentage OF the hourly rate, not on top of it. 150 means the rate for those hours becomes 1.5x base (EUR 10/h -> EUR 15/h). 100 means no uplift.', max_digits=6, verbose_name='Percentage of hourly rate (%)'),
        ),
    ]
