# Generated by Django 6.0 on 2026-09-01 21:14

import apps.core.encryption
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_convert_surcharge_to_rate_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='g_rekening',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', help_text='Special IBAN for G-account', max_length=512, plaintext_max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='G-Rekeningnummer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iban',
            field=apps.core.encryption.EncryptedCharField(blank=True, default='', max_length=512, plaintext_max_length=34, validators=[django.core.validators.RegexValidator(message='Enter a valid IBAN', regex='^[A-Z]{2}\\d{2}[A-Z0-9]{1,30}$')], verbose_name='IBAN'),
        ),
    ]
