# Generated by Django 6.0 on 2025-12-14 22:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cost Type Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('code', models.CharField(help_text='Short code for invoicing (e.g., TRANS, CLOTH)', max_length=20, unique=True, verbose_name='Code')),
                ('default_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Default Unit Price')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('is_billable_to_customer', models.BooleanField(default=True, verbose_name='Billable to Customer')),
                ('is_deductible_from_employee', models.BooleanField(default=False, verbose_name='Deductible from Employee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost Type',
                'verbose_name_plural': 'Cost Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('quantity_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hours')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Rate (€)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Invoice Line',
                'verbose_name_plural': 'Invoice Lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('role', models.CharField(blank=True, default='', help_text='Leave empty for default rate', max_length=20, verbose_name='Role')),
                ('employee_rate', models.DecimalField(decimal_places=2, help_text='What we pay the employee', max_digits=10, verbose_name='Employee Rate (€/hour)')),
                ('customer_rate', models.DecimalField(decimal_places=2, help_text='What we charge the customer', max_digits=10, verbose_name='Customer Rate (€/hour)')),
                ('effective_from', models.DateField(verbose_name='Effective From')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='Effective Until')),
            ],
            options={
                'verbose_name': 'Project Rate',
                'verbose_name_plural': 'Project Rates',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Invoice Number')),
                ('week_year', models.PositiveIntegerField(verbose_name='Year')),
                ('week_number', models.PositiveIntegerField(verbose_name='Week Number')),
                ('week_start_date', models.DateField(verbose_name='Week Start Date')),
                ('week_end_date', models.DateField(verbose_name='Week End Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('total_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Costs')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='VAT Rate (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('sent', 'Sent'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount Paid')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer', verbose_name='Customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-week_year', '-week_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price (€)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_costs', to='invoices.costtype', verbose_name='Cost Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_costs', to='employees.employeeprofile', verbose_name='Employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='invoices.invoice', verbose_name='Invoice')),
            ],
            options={
                'verbose_name': 'Invoice Cost',
                'verbose_name_plural': 'Invoice Costs',
                'ordering': ['created_at'],
            },
        ),
    ]
