# Generated by Django 6.0 on 2025-12-26 20:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_gratuity'),
        ('employees', '0008_allowancetype'),
        ('invoices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Allowances'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_gratuities',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Gratuities'),
        ),
        migrations.CreateModel(
            name='InvoiceAllowance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('custom_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Custom Allowance Name')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('quantity_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hours')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Rate (€)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('allowance_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allowances', to='employees.allowancetype', verbose_name='Allowance Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allowances', to='employees.employeeprofile', verbose_name='Employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_lines', to='invoices.invoice', verbose_name='Invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Invoice Allowance',
                'verbose_name_plural': 'Invoice Allowances',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceGratuity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (€)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_gratuities', to='employees.employeeprofile', verbose_name='Employee')),
                ('gratuity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_entries', to='customers.gratuity', verbose_name='Gratuity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity_lines', to='invoices.invoice', verbose_name='Invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Invoice Gratuity',
                'verbose_name_plural': 'Invoice Gratuities',
                'ordering': ['created_at'],
            },
        ),
    ]
