# Generated by Django 6.0 on 2026-08-16 17:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_agency_btw_number_agency_city_agency_contact_email_and_more'),
        ('invoices', '0003_invoice_total_allowances_invoice_total_gratuities_and_more'),
        ('projects', '0004_delete_shiftassignment'),
        ('worklogs', '0016_add_customer_role_and_work_entry_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('invoice_number', models.CharField(help_text='Auto-generated: AG-YYYY-NNNN', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('period_start', models.DateField(help_text='First day of the billing period', verbose_name='Period Start')),
                ('period_end', models.DateField(help_text='Last day of the billing period', verbose_name='Period End')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Hours')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (excl. VAT)')),
                ('total_surcharges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Surcharges')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='VAT Rate (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (incl. VAT)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('sent', 'Sent to Agency'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Amount Paid')),
                ('bank_proof', models.FileField(blank=True, help_text='Upload bank transfer confirmation when marking as paid', null=True, upload_to='agency_invoices/bank_proofs/', verbose_name='Bank Payment Proof')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('internal_notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='employees.agency', verbose_name='Agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Agency Invoice',
                'verbose_name_plural': 'Agency Invoices',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AgencyInvoiceLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('work_date', models.DateField(verbose_name='Work Date')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Hours Worked')),
                ('base_rate', models.DecimalField(decimal_places=2, help_text="Agency's base hourly rate at time of invoicing", max_digits=8, verbose_name='Base Rate (€/hr)')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base Amount (€)')),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Surcharge (%)')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Surcharge Amount (€)')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Line Total (€)')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_invoice_lines', to='employees.employeeprofile', verbose_name='Employee')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.agencyinvoice', verbose_name='Agency Invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_invoice_lines', to='projects.project', verbose_name='Project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('work_entry', models.OneToOneField(help_text='Each work entry can only appear on one agency invoice (prevents double-billing)', on_delete=django.db.models.deletion.PROTECT, related_name='agency_invoice_line', to='worklogs.workentry', verbose_name='Work Entry')),
            ],
            options={
                'verbose_name': 'Agency Invoice Line',
                'verbose_name_plural': 'Agency Invoice Lines',
                'ordering': ['work_date', 'employee'],
            },
        ),
    ]
