# Generated by Django 6.0 on 2026-08-30 18:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_agency_btw_number_agency_city_agency_contact_email_and_more'),
        ('expenses', '0001_initial'),
        ('invoices', '0004_agencyinvoice_agencyinvoiceline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('invoice_number', models.CharField(help_text="The number as printed on the supplier's invoice.", max_length=100, verbose_name='Invoice Number')),
                ('vendor_name', models.CharField(max_length=200, verbose_name='Vendor Name')),
                ('vendor_vat_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Vendor VAT Number')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid Date')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, verbose_name='VAT Rate (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT Amount')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('document', models.FileField(blank=True, help_text='Scan or PDF of the received invoice.', null=True, upload_to='incoming_invoices/%Y/%m/', verbose_name='Document')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('agency', models.ForeignKey(blank=True, help_text='Set when the supplier is one of the employment agencies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoices', to='employees.agency', verbose_name='Agency')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoices', to='expenses.expensecategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Incoming Invoice',
                'verbose_name_plural': 'Incoming Invoices',
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='invoices_in_status_e4027a_idx'), models.Index(fields=['vendor_name'], name='invoices_in_vendor__bba586_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vendor_name', 'invoice_number'), name='invoices_incominginvoice_unique_per_vendor')],
            },
        ),
    ]
