# Generated by Django 6.0 on 2026-09-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_incominginvoice'),
        ('worklogs', '0016_add_customer_role_and_work_entry_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='price_mode',
            field=models.CharField(default='EXCLUDING_VAT', help_text='Whether `total` includes VAT. Stated, never inferred.', max_length=20, verbose_name='Price mode'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_classification_status',
            field=models.CharField(db_index=True, default='REQUIRES_REVIEW', max_length=20, verbose_name='VAT classification status'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Derived from the treatment; null until classified.', max_digits=5, null=True, verbose_name='VAT rate (%)'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_return_box',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='vat_treatment_code',
            field=models.CharField(default='UNKNOWN', help_text='Defaults to UNKNOWN. A line is never assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='work_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='worklogs.workentry', verbose_name='Work entry'),
        ),
    ]
