# Generated by Django 6.0 on 2026-09-01 22:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_customer_ancillary_to_goods_sold_and_more'),
        ('employees', '0017_vat_classification_facts'),
        ('invoices', '0008_invoice_vat_facts'),
        ('projects', '0005_project_ancillary_to_goods_sold_and_more'),
        ('worklogs', '0016_add_customer_role_and_work_entry_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['work_date', 'created_at'], 'verbose_name': 'Invoice Line', 'verbose_name_plural': 'Invoice Lines'},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_mode',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('period', 'Period')], default='weekly', help_text='Weekly invoices are one per customer per week; period invoices cover an arbitrary date range.', max_length=10, verbose_name='Billing mode'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='correction_reason',
            field=models.TextField(blank=True, default='', verbose_name='Reason for correction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoices.invoice', verbose_name='Corrects'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note')], db_index=True, default='invoice', max_length=20, verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/%Y/', verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Period end'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Period start'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='allowance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Allowance amount'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours at the plain rate, before surcharges and allowances.', max_digits=12, null=True, verbose_name='Base amount'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('service', 'Service'), ('credit', 'Credit'), ('manual', 'Manual')], default='service', max_length=10, verbose_name='Line type'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Surcharge amount'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='surcharge_breakdown',
            field=models.JSONField(blank=True, default=list, verbose_name='Surcharge breakdown'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='total_is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='work_date',
            field=models.DateField(blank=True, help_text='The day the work was done; drives the sort order on the PDF.', null=True, verbose_name='Work date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_type', 'status'], name='invoice_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-issue_date'], name='invoice_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['period_start', 'period_end'], name='invoice_period_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'work_date'], name='line_invoice_date_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['work_entry'], name='line_work_entry_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_mode', 'weekly'), ('document_type', 'invoice'), ('is_deleted', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('customer', 'week_year', 'week_number'), name='unique_active_weekly_invoice_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('line_type', 'service'), ('work_entry__isnull', False)), fields=('work_entry',), name='unique_billed_work_entry'),
        ),
    ]
