# Generated by Django 6.0 on 2026-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('series', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Invoice sequence',
                'verbose_name_plural': 'Invoice sequences',
                'ordering': ['-year', 'series'],
                'constraints': [models.UniqueConstraint(fields=('series', 'year'), name='unique_sequence_per_series_year')],
            },
        ),
    ]
