# Generated by Django 6.0 on 2026-09-01 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_backfill_billing_fields'),
        ('projects', '0006_alter_projectrequiredcertificate_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='projects.project', verbose_name='Project'),
        ),
    ]
