# Generated by Django 6.0 on 2026-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_alter_projectrate_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyinvoice',
            name='vat_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='UNKNOWN', help_text='Defaults to UNKNOWN. Nothing is assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
        migrations.AlterField(
            model_name='incominginvoice',
            name='vat_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='UNKNOWN', help_text='Defaults to UNKNOWN. Nothing is assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], default='UNKNOWN', help_text='Defaults to UNKNOWN. Nothing is assumed to be 21%.', max_length=30, verbose_name='VAT treatment'),
        ),
    ]
