# Generated by Django 6.0 on 2026-09-01 21:29

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatReturnBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Rubriek')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('direction', models.CharField(choices=[('OUTPUT', 'Output VAT (sales)'), ('INPUT', 'Input VAT (purchases)')], max_length=10)),
                ('is_computed', models.BooleanField(default=False, help_text='Derived from other boxes (5a, 5b) rather than fed by transactions.')),
                ('is_active', models.BooleanField(default=True, help_text='Boxes that do not apply to this company stay inactive but present, so enabling them later needs no schema change.')),
            ],
            options={
                'verbose_name': 'VAT return box',
                'verbose_name_plural': 'VAT return boxes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VatLedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('source_type', models.CharField(db_index=True, max_length=50)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('source_line_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_reference', models.CharField(blank=True, default='', help_text='Human-readable, e.g. the invoice number.', max_length=120)),
                ('kind', models.CharField(choices=[('SALE', 'Sale (output)'), ('PURCHASE', 'Purchase (input)'), ('RC_OUTPUT', 'Reverse-charge VAT declared'), ('RC_INPUT', 'Reverse-charge VAT deducted'), ('CORRECTION', 'Correction')], db_index=True, max_length=20)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('tax_point_date', models.DateField(db_index=True, help_text='The date that decides the period. Under factuurstelsel this is the invoice date, never the payment date.')),
                ('treatment_code', models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30)),
                ('price_mode', models.CharField(choices=[('EXCLUDING_VAT', 'Price excludes VAT'), ('INCLUDING_VAT', 'Price includes VAT')], default='EXCLUDING_VAT', max_length=20)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxable_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('output_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('input_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('deductible_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('non_deductible_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('classification_status', models.CharField(choices=[('CLASSIFIED', 'Classified'), ('REQUIRES_REVIEW', 'Requires review'), ('MANUALLY_RESOLVED', 'Manually resolved')], db_index=True, default='CLASSIFIED', max_length=20)),
                ('review_reason', models.TextField(blank=True, default='', help_text='Why a human is needed. Always populated when review is required.')),
                ('calculation_method', models.TextField(blank=True, default='', help_text='Plain-language record of how the figures were reached.')),
                ('rules_version', models.CharField(blank=True, default='', max_length=20)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'VAT ledger entry',
                'verbose_name_plural': 'VAT ledger entries',
                'ordering': ['tax_point_date', 'source_reference'],
            },
        ),
        migrations.CreateModel(
            name='VatClassificationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('original_treatment_code', models.CharField(max_length=30)),
                ('original_status', models.CharField(max_length=20)),
                ('original_vat_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_treatment_code', models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30)),
                ('new_vat_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vat_overrides', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='vat.vatledgerentry')),
            ],
            options={
                'verbose_name': 'VAT classification override',
                'ordering': ['-resolved_at'],
            },
        ),
        migrations.CreateModel(
            name='VatPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never truly deleted', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(blank=True, help_text='1-4. Null for a yearly period.', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('REVIEW_REQUIRED', 'Review required'), ('REVIEWED', 'Reviewed'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked')], db_index=True, default='DRAFT', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('filed_snapshot', models.JSONField(blank=True, null=True)),
                ('rules_version', models.CharField(blank=True, default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_vat_periods', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'VAT period',
                'ordering': ['-year', '-quarter'],
            },
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='vat.vatperiod'),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='return_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='vat.vatreturnbox'),
        ),
        migrations.CreateModel(
            name='VatTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('code', models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='VAT rate (%)')),
                ('creates_output_vat', models.BooleanField(default=False)),
                ('creates_input_vat', models.BooleanField(default=False)),
                ('is_reverse_charge', models.BooleanField(default=False)),
                ('default_deductible_percentage', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Portion of input VAT normally deductible under this rule.', max_digits=5)),
                ('requires_review', models.BooleanField(default=False, help_text='Anything classified under this rule is held for a human.')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='Null means still in force.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('input_box', models.ForeignKey(blank=True, help_text='Deduction box, normally 5b.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatments_input', to='vat.vatreturnbox')),
                ('output_box', models.ForeignKey(blank=True, help_text='Sales box, or the box the recipient declares reverse-charged VAT in.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatments_output', to='vat.vatreturnbox')),
            ],
            options={
                'verbose_name': 'VAT treatment',
                'ordering': ['code', '-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='vat.vattreatment'),
        ),
        migrations.AddConstraint(
            model_name='vatperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('year', 'quarter'), name='vat_period_unique_year_quarter'),
        ),
        migrations.AddConstraint(
            model_name='vatperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='vat_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='vattreatment',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='vat_treatment_effective_range'),
        ),
        migrations.AddIndex(
            model_name='vatledgerentry',
            index=models.Index(fields=['period', 'kind'], name='vat_vatledg_period__ae7125_idx'),
        ),
        migrations.AddIndex(
            model_name='vatledgerentry',
            index=models.Index(fields=['period', 'classification_status'], name='vat_vatledg_period__72e434_idx'),
        ),
        migrations.AddIndex(
            model_name='vatledgerentry',
            index=models.Index(fields=['source_type', 'source_id'], name='vat_vatledg_source__ac80f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='vatledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('source_type', 'source_id', 'source_line_id', 'kind'), name='vat_ledger_unique_source'),
        ),
    ]
