# Generated by Django 6.0 on 2026-09-01 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0002_seed_boxes_and_treatments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vatperiod',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatperiod',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_vat_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatperiod',
            name='reopen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vatperiod',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatperiod',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_vat_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vatperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REVIEW_REQUIRED', 'Review required'), ('READY_TO_FINALIZE', 'Ready to finalize'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked'), ('DRAFT', 'Draft (legacy)'), ('CALCULATED', 'Calculated (legacy)'), ('REVIEWED', 'Reviewed (legacy)')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='VatPeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated', verbose_name='Updated At')),
                ('event', models.CharField(choices=[('CREATED', 'Period created'), ('RECALCULATED', 'Recalculated'), ('RECONCILED', 'Reconciliation run'), ('FINALIZED', 'Finalized'), ('LOCKED', 'Locked'), ('REOPENED', 'Reopened'), ('CORRECTION_POSTED', 'Correction posted'), ('BLOCKED', 'Action blocked')], db_index=True, max_length=30)),
                ('detail', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, help_text='Totals or findings at the time, so an event is explainable later.', null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_period_events', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vat.vatperiod')),
            ],
            options={
                'verbose_name': 'VAT period event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['period', 'event'], name='vat_vatperi_period__fe36cf_idx')],
            },
        ),
    ]
