# Generated by Django 6.0 on 2026-09-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat', '0004_seed_eu_purchase_treatments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatclassificationoverride',
            name='new_treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vatledgerentry',
            name='treatment_code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vattreatment',
            name='code',
            field=models.CharField(choices=[('NORMAL', 'Normal (VAT charged)'), ('VAT_INCLUDED', 'Normal, price includes VAT'), ('REVERSE_CHARGE', 'Reverse charge (btw verlegd)'), ('EU_ACQUISITION', 'Purchase from within the EU (rubriek 4b)'), ('IMPORT_ACQUISITION', 'Purchase from outside the EU (rubriek 4a)'), ('ZERO_RATE', 'Zero rated (0%)'), ('EXEMPT', 'Exempt (vrijgesteld)'), ('OUT_OF_SCOPE', 'Outside the scope of VAT'), ('UNKNOWN', 'Unknown — requires review'), ('MANUAL_ADJUSTMENT', 'Manual adjustment')], max_length=30),
        ),
    ]
