/**
 * Phrase-keyed translations.
 *
 * The camelCase table in `i18n.tsx` covers the dashboard home and navigation.
 * Everywhere else the UI was written as literal English in JSX, so switching
 * language changed nothing. Keying on the English phrase itself lets those
 * screens be wrapped in `t(...)` without inventing a key name for each of the
 * ~860 strings, and anything not yet listed here falls back to the English it
 * already displayed rather than to a raw key.
 */

export type PhraseTable = Record<string, string>;

/** English is the key space, so it needs no table of its own. */
const nl: PhraseTable = {
    // Navigation
    'Weekly Board': 'Weekoverzicht',
    'Contract Types': 'Contracttypen',
    'Day Payment Types': 'Dagtoeslagtypen',
    'HR': 'HR',
    'Finance': 'Financiën',
    'Outgoing Invoices': 'Uitgaande facturen',
    'Incoming Invoices': 'Inkomende facturen',
    'Financial Overview': 'Financieel overzicht',
    'BTW Aangifte': 'Btw-aangifte',
    'Expenses Summary': 'Kostenoverzicht',
    'Allowance Types': 'Toeslagtypen',

    // Actions
    'Save': 'Opslaan',
    'Cancel': 'Annuleren',
    'Delete': 'Verwijderen',
    'Edit': 'Bewerken',
    'Add': 'Toevoegen',
    'View': 'Bekijken',
    'Close': 'Sluiten',
    'Back': 'Terug',
    'Next': 'Volgende',
    'Previous': 'Vorige',
    'Prev': 'Vorige',
    'Retry': 'Opnieuw',
    'Refresh': 'Vernieuwen',
    'Select': 'Selecteren',
    'Select All': 'Alles selecteren',
    'Clear': 'Wissen',
    'Clear All': 'Alles wissen',
    'Clear all': 'Alles wissen',
    'Clear Filters': 'Filters wissen',
    'Search': 'Zoeken',
    'Filter': 'Filteren',
    'Export': 'Exporteren',
    'Export CSV': 'CSV exporteren',
    'Import': 'Importeren',
    'Download': 'Downloaden',
    'Download PDF': 'PDF downloaden',
    'Upload': 'Uploaden',
    'Print': 'Afdrukken',
    'Send': 'Versturen',
    'Submit': 'Indienen',
    'Approve': 'Goedkeuren',
    'Reject': 'Afwijzen',
    'Generate': 'Genereren',
    'Create': 'Aanmaken',
    'Update': 'Bijwerken',
    'Confirm': 'Bevestigen',
    'Done': 'Klaar',
    'Yes': 'Ja',
    'No': 'Nee',
    'Actions': 'Acties',
    'Help': 'Help',

    // Status
    'Status': 'Status',
    'Active': 'Actief',
    'Inactive': 'Inactief',
    'Pending': 'In afwachting',
    'Approved': 'Goedgekeurd',
    'Rejected': 'Afgewezen',
    'Paid': 'Betaald',
    'Unpaid': 'Onbetaald',
    'Draft': 'Concept',
    'Sent': 'Verstuurd',
    'Overdue': 'Achterstallig',
    'Cancelled': 'Geannuleerd',
    'Completed': 'Afgerond',
    'Submitted': 'Ingediend',
    'Incomplete': 'Onvolledig',
    'Required': 'Verplicht',
    'Optional': 'Optioneel',
    'Current': 'Huidig',
    'Not set': 'Niet ingesteld',
    'Loading...': 'Laden...',
    'Loading': 'Laden',

    // Entities
    'Dashboard': 'Dashboard',
    'Employee': 'Medewerker',
    'Employees': 'Medewerkers',
    'Customer': 'Klant',
    'Customers': 'Klanten',
    'Project': 'Project',
    'Projects': 'Projecten',
    'Work Logs': 'Werkuren',
    'Worklogs': 'Werkuren',
    'Invoice': 'Factuur',
    'Invoices': 'Facturen',
    'Agency': 'Bureau',
    'Agencies': 'Bureaus',
    'Agency Invoices': 'Bureaufacturen',
    'Expenses': 'Kosten',
    'Expense': 'Kostenpost',
    'Wallet': 'Portemonnee',
    'Settings': 'Instellingen',
    'Notifications': 'Meldingen',
    'Reports': 'Rapporten',
    'Certificates': 'Certificaten',
    'Payslips': 'Loonstroken',
    'Payroll': 'Salarisadministratie',
    'Attendance': 'Aanwezigheid',
    'Leave Requests': 'Verlofaanvragen',
    'Contracts': 'Contracten',
    'Services': 'Diensten',
    'Service': 'Dienst',
    'Supervisor': 'Leidinggevende',
    'Supervisors': 'Leidinggevenden',
    'Allowances': 'Toeslagen',
    'Allowance': 'Toeslag',
    'Gratuities': 'Fooien',
    'Shifts': 'Diensten',
    'Shift': 'Dienst',
    'Document': 'Document',
    'Documents': 'Documenten',
    'Administrator': 'Beheerder',
    'Logout': 'Uitloggen',
    'Logout Account': 'Account uitloggen',

    // Fields
    'Name': 'Naam',
    'First Name': 'Voornaam',
    'First name': 'Voornaam',
    'Last Name': 'Achternaam',
    'Last name': 'Achternaam',
    'Email': 'E-mail',
    'Email Address': 'E-mailadres',
    'Email Addresses': 'E-mailadressen',
    'Phone': 'Telefoon',
    'Phone Numbers': 'Telefoonnummers',
    'Address': 'Adres',
    'City': 'Plaats',
    'Postcode': 'Postcode',
    'Street Name': 'Straatnaam',
    'House Nr.': 'Huisnr.',
    'Add.': 'Toev.',
    'Country': 'Land',
    'Nationality': 'Nationaliteit',
    'Gender': 'Geslacht',
    'Date of Birth': 'Geboortedatum',
    'Birthplace': 'Geboorteplaats',
    'Password': 'Wachtwoord',
    'Description': 'Omschrijving',
    'Notes': 'Notities',
    'Notes (Optional)': 'Notities (optioneel)',
    'Code': 'Code',
    'Type': 'Type',
    'Category': 'Categorie',
    'Amount': 'Bedrag',
    'Price': 'Prijs',
    'Rate': 'Tarief',
    'Hourly Rate': 'Uurtarief',
    'Base Price': 'Basisprijs',
    'Total': 'Totaal',
    'Subtotal': 'Subtotaal',
    'Date': 'Datum',
    'Time': 'Tijd',
    'Date & Time': 'Datum & tijd',
    'Start': 'Start',
    'End': 'Einde',
    'Start Date': 'Startdatum',
    'End Date': 'Einddatum',
    'Start Time': 'Starttijd',
    'End Time': 'Eindtijd',
    'Start Date/Time': 'Startdatum/-tijd',
    'End Date/Time': 'Einddatum/-tijd',
    'Expiry Date': 'Vervaldatum',
    'Issue Date': 'Factuurdatum',
    'Effective From': 'Geldig vanaf',
    'Effective To': 'Geldig tot',
    'From': 'Van',
    'To': 'Tot',
    'From Time': 'Van tijd',
    'To Time': 'Tot tijd',
    'From Week': 'Van week',
    'To Week': 'Tot week',
    'Period': 'Periode',
    'Day': 'Dag',
    'Days': 'Dagen',
    'Hours': 'Uren',
    'Total Hours': 'Totaal uren',
    'Normal Hours': 'Normale uren',
    'Pause': 'Pauze',
    'Breaks': 'Pauzes',
    'Location': 'Locatie',
    'Company Name': 'Bedrijfsnaam',
    'Company Information': 'Bedrijfsgegevens',
    'Contact Information': 'Contactgegevens',
    'Financial Information': 'Financiële gegevens',
    'Personal Information': 'Persoonlijke gegevens',
    'Contract Information': 'Contractgegevens',
    'Contract Type': 'Contracttype',
    'Contract History': 'Contracthistorie',
    'Document Type': 'Documenttype',
    'Document Number': 'Documentnummer',
    'ID Document': 'Identiteitsbewijs',
    "Driver's License": 'Rijbewijs',
    'Front Side': 'Voorzijde',
    'Back Side': 'Achterzijde',
    'PDF Document': 'PDF-document',
    'Uploaded By': 'Geüpload door',
    'Sort Order': 'Sorteervolgorde',
    'Is Active': 'Is actief',
    'Reference #': 'Referentienr.',
    'Payment Method': 'Betaalmethode',
    'Vendor Name': 'Leveranciersnaam',
    'Prefix': 'Voorvoegsel',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'KvK-nummer',
    'BTW Number': 'Btw-nummer',
    'G-Rekening': 'G-rekening',

    // Empty and helper states
    'No data': 'Geen gegevens',
    'No data available': 'Geen gegevens beschikbaar',
    'No customers found': 'Geen klanten gevonden',
    'No employees found': 'Geen medewerkers gevonden',
    'No projects found': 'Geen projecten gevonden',
    'No services found': 'Geen diensten gevonden',
    'No supervisors found': 'Geen leidinggevenden gevonden',
    'No supervisors added yet': 'Nog geen leidinggevenden toegevoegd',
    'No phone numbers available': 'Geen telefoonnummers beschikbaar',
    'No email addresses available': 'Geen e-mailadressen beschikbaar',
    'No nationality found': 'Geen nationaliteit gevonden',
    'Search customers...': 'Klanten zoeken...',
    'Search employees...': 'Medewerkers zoeken...',
    'Search employee...': 'Medewerker zoeken...',
    'Search nationality...': 'Nationaliteit zoeken...',
    'Search allowance types...': 'Toeslagtypen zoeken...',
    'Select...': 'Selecteren...',
    'Select customer...': 'Klant selecteren...',
    'Select project...': 'Project selecteren...',
    'Select service...': 'Dienst selecteren...',
    'Select supervisor...': 'Leidinggevende selecteren...',
    'Select category...': 'Categorie selecteren...',
    'Select nationality...': 'Nationaliteit selecteren...',
    'Select email...': 'E-mail selecteren...',
    'Select phone...': 'Telefoon selecteren...',
    'Today': 'Vandaag',
    'Toggle menu': 'Menu wisselen',
};

const ar: PhraseTable = {
    // Navigation
    'Weekly Board': 'اللوحة الأسبوعية',
    'Contract Types': 'أنواع العقود',
    'Day Payment Types': 'أنواع بدلات اليوم',
    'HR': 'الموارد البشرية',
    'Finance': 'المالية',
    'Outgoing Invoices': 'الفواتير الصادرة',
    'Incoming Invoices': 'الفواتير الواردة',
    'Financial Overview': 'نظرة عامة مالية',
    'BTW Aangifte': 'إقرار ضريبة القيمة المضافة',
    'Expenses Summary': 'ملخص المصروفات',
    'Allowance Types': 'أنواع البدلات',

    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Delete': 'حذف',
    'Edit': 'تعديل',
    'Add': 'إضافة',
    'View': 'عرض',
    'Close': 'إغلاق',
    'Back': 'رجوع',
    'Next': 'التالي',
    'Previous': 'السابق',
    'Prev': 'السابق',
    'Retry': 'إعادة المحاولة',
    'Refresh': 'تحديث',
    'Select': 'اختيار',
    'Select All': 'تحديد الكل',
    'Clear': 'مسح',
    'Clear All': 'مسح الكل',
    'Clear all': 'مسح الكل',
    'Clear Filters': 'مسح عوامل التصفية',
    'Search': 'بحث',
    'Filter': 'تصفية',
    'Export': 'تصدير',
    'Export CSV': 'تصدير CSV',
    'Import': 'استيراد',
    'Download': 'تنزيل',
    'Download PDF': 'تنزيل PDF',
    'Upload': 'رفع',
    'Print': 'طباعة',
    'Send': 'إرسال',
    'Submit': 'إرسال',
    'Approve': 'اعتماد',
    'Reject': 'رفض',
    'Generate': 'إنشاء',
    'Create': 'إنشاء',
    'Update': 'تحديث',
    'Confirm': 'تأكيد',
    'Done': 'تم',
    'Yes': 'نعم',
    'No': 'لا',
    'Actions': 'إجراءات',
    'Help': 'مساعدة',

    'Status': 'الحالة',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Pending': 'قيد الانتظار',
    'Approved': 'معتمد',
    'Rejected': 'مرفوض',
    'Paid': 'مدفوع',
    'Unpaid': 'غير مدفوع',
    'Draft': 'مسودة',
    'Sent': 'مُرسل',
    'Overdue': 'متأخر',
    'Cancelled': 'ملغى',
    'Completed': 'مكتمل',
    'Submitted': 'مُقدَّم',
    'Incomplete': 'غير مكتمل',
    'Required': 'مطلوب',
    'Optional': 'اختياري',
    'Current': 'الحالي',
    'Not set': 'غير محدد',
    'Loading...': 'جارٍ التحميل...',
    'Loading': 'جارٍ التحميل',

    'Dashboard': 'لوحة التحكم',
    'Employee': 'موظف',
    'Employees': 'الموظفون',
    'Customer': 'عميل',
    'Customers': 'العملاء',
    'Project': 'مشروع',
    'Projects': 'المشاريع',
    'Work Logs': 'سجلات العمل',
    'Worklogs': 'سجلات العمل',
    'Invoice': 'فاتورة',
    'Invoices': 'الفواتير',
    'Agency': 'وكالة',
    'Agencies': 'الوكالات',
    'Agency Invoices': 'فواتير الوكالات',
    'Expenses': 'المصروفات',
    'Expense': 'مصروف',
    'Wallet': 'المحفظة',
    'Settings': 'الإعدادات',
    'Notifications': 'الإشعارات',
    'Reports': 'التقارير',
    'Certificates': 'الشهادات',
    'Payslips': 'كشوف الرواتب',
    'Payroll': 'الرواتب',
    'Attendance': 'الحضور',
    'Leave Requests': 'طلبات الإجازة',
    'Contracts': 'العقود',
    'Services': 'الخدمات',
    'Service': 'خدمة',
    'Supervisor': 'المشرف',
    'Supervisors': 'المشرفون',
    'Allowances': 'البدلات',
    'Allowance': 'بدل',
    'Gratuities': 'الإكراميات',
    'Shifts': 'المناوبات',
    'Shift': 'مناوبة',
    'Document': 'مستند',
    'Documents': 'المستندات',
    'Administrator': 'المسؤول',
    'Logout': 'تسجيل الخروج',
    'Logout Account': 'تسجيل خروج الحساب',

    'Name': 'الاسم',
    'First Name': 'الاسم الأول',
    'First name': 'الاسم الأول',
    'Last Name': 'اسم العائلة',
    'Last name': 'اسم العائلة',
    'Email': 'البريد الإلكتروني',
    'Email Address': 'عنوان البريد الإلكتروني',
    'Email Addresses': 'عناوين البريد الإلكتروني',
    'Phone': 'الهاتف',
    'Phone Numbers': 'أرقام الهاتف',
    'Address': 'العنوان',
    'City': 'المدينة',
    'Postcode': 'الرمز البريدي',
    'Street Name': 'اسم الشارع',
    'House Nr.': 'رقم المنزل',
    'Add.': 'إضافة',
    'Country': 'الدولة',
    'Nationality': 'الجنسية',
    'Gender': 'الجنس',
    'Date of Birth': 'تاريخ الميلاد',
    'Birthplace': 'مكان الميلاد',
    'Password': 'كلمة المرور',
    'Description': 'الوصف',
    'Notes': 'ملاحظات',
    'Notes (Optional)': 'ملاحظات (اختياري)',
    'Code': 'الرمز',
    'Type': 'النوع',
    'Category': 'الفئة',
    'Amount': 'المبلغ',
    'Price': 'السعر',
    'Rate': 'التعرفة',
    'Hourly Rate': 'الأجر بالساعة',
    'Base Price': 'السعر الأساسي',
    'Total': 'الإجمالي',
    'Subtotal': 'المجموع الفرعي',
    'Date': 'التاريخ',
    'Time': 'الوقت',
    'Date & Time': 'التاريخ والوقت',
    'Start': 'البداية',
    'End': 'النهاية',
    'Start Date': 'تاريخ البداية',
    'End Date': 'تاريخ النهاية',
    'Start Time': 'وقت البداية',
    'End Time': 'وقت النهاية',
    'Start Date/Time': 'تاريخ/وقت البداية',
    'End Date/Time': 'تاريخ/وقت النهاية',
    'Expiry Date': 'تاريخ الانتهاء',
    'Issue Date': 'تاريخ الإصدار',
    'Effective From': 'ساري من',
    'Effective To': 'ساري حتى',
    'From': 'من',
    'To': 'إلى',
    'From Time': 'من وقت',
    'To Time': 'إلى وقت',
    'From Week': 'من أسبوع',
    'To Week': 'إلى أسبوع',
    'Period': 'الفترة',
    'Day': 'يوم',
    'Days': 'أيام',
    'Hours': 'الساعات',
    'Total Hours': 'إجمالي الساعات',
    'Normal Hours': 'الساعات العادية',
    'Pause': 'استراحة',
    'Breaks': 'الاستراحات',
    'Location': 'الموقع',
    'Company Name': 'اسم الشركة',
    'Company Information': 'معلومات الشركة',
    'Contact Information': 'معلومات الاتصال',
    'Financial Information': 'المعلومات المالية',
    'Personal Information': 'المعلومات الشخصية',
    'Contract Information': 'معلومات العقد',
    'Contract Type': 'نوع العقد',
    'Contract History': 'سجل العقود',
    'Document Type': 'نوع المستند',
    'Document Number': 'رقم المستند',
    'ID Document': 'وثيقة الهوية',
    "Driver's License": 'رخصة القيادة',
    'Front Side': 'الوجه الأمامي',
    'Back Side': 'الوجه الخلفي',
    'PDF Document': 'مستند PDF',
    'Uploaded By': 'رفع بواسطة',
    'Sort Order': 'ترتيب الفرز',
    'Is Active': 'نشط',
    'Reference #': 'الرقم المرجعي',
    'Payment Method': 'طريقة الدفع',
    'Vendor Name': 'اسم المورّد',
    'Prefix': 'البادئة',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'رقم KvK',
    'BTW Number': 'رقم ضريبة القيمة المضافة',
    'G-Rekening': 'حساب G',

    'No data': 'لا توجد بيانات',
    'No data available': 'لا توجد بيانات متاحة',
    'No customers found': 'لم يتم العثور على عملاء',
    'No employees found': 'لم يتم العثور على موظفين',
    'No projects found': 'لم يتم العثور على مشاريع',
    'No services found': 'لم يتم العثور على خدمات',
    'No supervisors found': 'لم يتم العثور على مشرفين',
    'No supervisors added yet': 'لم تتم إضافة مشرفين بعد',
    'No phone numbers available': 'لا توجد أرقام هاتف متاحة',
    'No email addresses available': 'لا توجد عناوين بريد متاحة',
    'No nationality found': 'لم يتم العثور على جنسية',
    'Search customers...': 'ابحث عن العملاء...',
    'Search employees...': 'ابحث عن الموظفين...',
    'Search employee...': 'ابحث عن موظف...',
    'Search nationality...': 'ابحث عن الجنسية...',
    'Search allowance types...': 'ابحث عن أنواع البدلات...',
    'Select...': 'اختر...',
    'Select customer...': 'اختر عميلاً...',
    'Select project...': 'اختر مشروعاً...',
    'Select service...': 'اختر خدمة...',
    'Select supervisor...': 'اختر مشرفاً...',
    'Select category...': 'اختر فئة...',
    'Select nationality...': 'اختر الجنسية...',
    'Select email...': 'اختر البريد الإلكتروني...',
    'Select phone...': 'اختر الهاتف...',
    'Today': 'اليوم',
    'Toggle menu': 'تبديل القائمة',
};

const ru: PhraseTable = {
    // Navigation
    'Weekly Board': 'Недельная доска',
    'Contract Types': 'Типы договоров',
    'Day Payment Types': 'Типы дневных надбавок',
    'HR': 'Кадры',
    'Finance': 'Финансы',
    'Outgoing Invoices': 'Исходящие счета',
    'Incoming Invoices': 'Входящие счета',
    'Financial Overview': 'Финансовый обзор',
    'BTW Aangifte': 'Декларация НДС',
    'Expenses Summary': 'Сводка расходов',
    'Allowance Types': 'Типы надбавок',

    'Save': 'Сохранить',
    'Cancel': 'Отмена',
    'Delete': 'Удалить',
    'Edit': 'Изменить',
    'Add': 'Добавить',
    'View': 'Просмотр',
    'Close': 'Закрыть',
    'Back': 'Назад',
    'Next': 'Далее',
    'Previous': 'Назад',
    'Prev': 'Назад',
    'Retry': 'Повторить',
    'Refresh': 'Обновить',
    'Select': 'Выбрать',
    'Select All': 'Выбрать все',
    'Clear': 'Очистить',
    'Clear All': 'Очистить все',
    'Clear all': 'Очистить все',
    'Clear Filters': 'Сбросить фильтры',
    'Search': 'Поиск',
    'Filter': 'Фильтр',
    'Export': 'Экспорт',
    'Export CSV': 'Экспорт CSV',
    'Import': 'Импорт',
    'Download': 'Скачать',
    'Download PDF': 'Скачать PDF',
    'Upload': 'Загрузить',
    'Print': 'Печать',
    'Send': 'Отправить',
    'Submit': 'Отправить',
    'Approve': 'Утвердить',
    'Reject': 'Отклонить',
    'Generate': 'Создать',
    'Create': 'Создать',
    'Update': 'Обновить',
    'Confirm': 'Подтвердить',
    'Done': 'Готово',
    'Yes': 'Да',
    'No': 'Нет',
    'Actions': 'Действия',
    'Help': 'Помощь',

    'Status': 'Статус',
    'Active': 'Активен',
    'Inactive': 'Неактивен',
    'Pending': 'В ожидании',
    'Approved': 'Утверждено',
    'Rejected': 'Отклонено',
    'Paid': 'Оплачено',
    'Unpaid': 'Не оплачено',
    'Draft': 'Черновик',
    'Sent': 'Отправлено',
    'Overdue': 'Просрочено',
    'Cancelled': 'Отменено',
    'Completed': 'Завершено',
    'Submitted': 'Подано',
    'Incomplete': 'Не заполнено',
    'Required': 'Обязательно',
    'Optional': 'Необязательно',
    'Current': 'Текущий',
    'Not set': 'Не задано',
    'Loading...': 'Загрузка...',
    'Loading': 'Загрузка',

    'Dashboard': 'Панель',
    'Employee': 'Сотрудник',
    'Employees': 'Сотрудники',
    'Customer': 'Клиент',
    'Customers': 'Клиенты',
    'Project': 'Проект',
    'Projects': 'Проекты',
    'Work Logs': 'Учёт часов',
    'Worklogs': 'Учёт часов',
    'Invoice': 'Счёт',
    'Invoices': 'Счета',
    'Agency': 'Агентство',
    'Agencies': 'Агентства',
    'Agency Invoices': 'Счета агентств',
    'Expenses': 'Расходы',
    'Expense': 'Расход',
    'Wallet': 'Кошелёк',
    'Settings': 'Настройки',
    'Notifications': 'Уведомления',
    'Reports': 'Отчёты',
    'Certificates': 'Сертификаты',
    'Payslips': 'Расчётные листы',
    'Payroll': 'Расчёт зарплаты',
    'Attendance': 'Посещаемость',
    'Leave Requests': 'Заявки на отпуск',
    'Contracts': 'Договоры',
    'Services': 'Услуги',
    'Service': 'Услуга',
    'Supervisor': 'Руководитель',
    'Supervisors': 'Руководители',
    'Allowances': 'Надбавки',
    'Allowance': 'Надбавка',
    'Gratuities': 'Чаевые',
    'Shifts': 'Смены',
    'Shift': 'Смена',
    'Document': 'Документ',
    'Documents': 'Документы',
    'Administrator': 'Администратор',
    'Logout': 'Выйти',
    'Logout Account': 'Выйти из аккаунта',

    'Name': 'Имя',
    'First Name': 'Имя',
    'First name': 'Имя',
    'Last Name': 'Фамилия',
    'Last name': 'Фамилия',
    'Email': 'Эл. почта',
    'Email Address': 'Адрес эл. почты',
    'Email Addresses': 'Адреса эл. почты',
    'Phone': 'Телефон',
    'Phone Numbers': 'Номера телефонов',
    'Address': 'Адрес',
    'City': 'Город',
    'Postcode': 'Почтовый индекс',
    'Street Name': 'Улица',
    'House Nr.': 'Дом №',
    'Add.': 'Доп.',
    'Country': 'Страна',
    'Nationality': 'Гражданство',
    'Gender': 'Пол',
    'Date of Birth': 'Дата рождения',
    'Birthplace': 'Место рождения',
    'Password': 'Пароль',
    'Description': 'Описание',
    'Notes': 'Заметки',
    'Notes (Optional)': 'Заметки (необязательно)',
    'Code': 'Код',
    'Type': 'Тип',
    'Category': 'Категория',
    'Amount': 'Сумма',
    'Price': 'Цена',
    'Rate': 'Ставка',
    'Hourly Rate': 'Почасовая ставка',
    'Base Price': 'Базовая цена',
    'Total': 'Итого',
    'Subtotal': 'Промежуточный итог',
    'Date': 'Дата',
    'Time': 'Время',
    'Date & Time': 'Дата и время',
    'Start': 'Начало',
    'End': 'Конец',
    'Start Date': 'Дата начала',
    'End Date': 'Дата окончания',
    'Start Time': 'Время начала',
    'End Time': 'Время окончания',
    'Start Date/Time': 'Дата/время начала',
    'End Date/Time': 'Дата/время окончания',
    'Expiry Date': 'Срок действия',
    'Issue Date': 'Дата выставления',
    'Effective From': 'Действует с',
    'Effective To': 'Действует по',
    'From': 'С',
    'To': 'По',
    'From Time': 'С какого времени',
    'To Time': 'По какое время',
    'From Week': 'С недели',
    'To Week': 'По неделю',
    'Period': 'Период',
    'Day': 'День',
    'Days': 'Дни',
    'Hours': 'Часы',
    'Total Hours': 'Всего часов',
    'Normal Hours': 'Обычные часы',
    'Pause': 'Перерыв',
    'Breaks': 'Перерывы',
    'Location': 'Местоположение',
    'Company Name': 'Название компании',
    'Company Information': 'Данные компании',
    'Contact Information': 'Контактные данные',
    'Financial Information': 'Финансовые данные',
    'Personal Information': 'Личные данные',
    'Contract Information': 'Данные договора',
    'Contract Type': 'Тип договора',
    'Contract History': 'История договоров',
    'Document Type': 'Тип документа',
    'Document Number': 'Номер документа',
    'ID Document': 'Удостоверение личности',
    "Driver's License": 'Водительское удостоверение',
    'Front Side': 'Лицевая сторона',
    'Back Side': 'Обратная сторона',
    'PDF Document': 'PDF-документ',
    'Uploaded By': 'Загрузил',
    'Sort Order': 'Порядок сортировки',
    'Is Active': 'Активен',
    'Reference #': 'Номер ссылки',
    'Payment Method': 'Способ оплаты',
    'Vendor Name': 'Поставщик',
    'Prefix': 'Префикс',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'Номер KvK',
    'BTW Number': 'НДС-номер',
    'G-Rekening': 'G-счёт',

    'No data': 'Нет данных',
    'No data available': 'Данные отсутствуют',
    'No customers found': 'Клиенты не найдены',
    'No employees found': 'Сотрудники не найдены',
    'No projects found': 'Проекты не найдены',
    'No services found': 'Услуги не найдены',
    'No supervisors found': 'Руководители не найдены',
    'No supervisors added yet': 'Руководители ещё не добавлены',
    'No phone numbers available': 'Нет доступных телефонов',
    'No email addresses available': 'Нет доступных адресов',
    'No nationality found': 'Гражданство не найдено',
    'Search customers...': 'Поиск клиентов...',
    'Search employees...': 'Поиск сотрудников...',
    'Search employee...': 'Поиск сотрудника...',
    'Search nationality...': 'Поиск гражданства...',
    'Search allowance types...': 'Поиск типов надбавок...',
    'Select...': 'Выберите...',
    'Select customer...': 'Выберите клиента...',
    'Select project...': 'Выберите проект...',
    'Select service...': 'Выберите услугу...',
    'Select supervisor...': 'Выберите руководителя...',
    'Select category...': 'Выберите категорию...',
    'Select nationality...': 'Выберите гражданство...',
    'Select email...': 'Выберите эл. почту...',
    'Select phone...': 'Выберите телефон...',
    'Today': 'Сегодня',
    'Toggle menu': 'Переключить меню',
};

const uk: PhraseTable = {
    // Navigation
    'Weekly Board': 'Тижнева дошка',
    'Contract Types': 'Типи договорів',
    'Day Payment Types': 'Типи денних надбавок',
    'HR': 'Кадри',
    'Finance': 'Фінанси',
    'Outgoing Invoices': 'Вихідні рахунки',
    'Incoming Invoices': 'Вхідні рахунки',
    'Financial Overview': 'Фінансовий огляд',
    'BTW Aangifte': 'Декларація ПДВ',
    'Expenses Summary': 'Зведення витрат',
    'Allowance Types': 'Типи надбавок',

    'Save': 'Зберегти',
    'Cancel': 'Скасувати',
    'Delete': 'Видалити',
    'Edit': 'Редагувати',
    'Add': 'Додати',
    'View': 'Переглянути',
    'Close': 'Закрити',
    'Back': 'Назад',
    'Next': 'Далі',
    'Previous': 'Назад',
    'Prev': 'Назад',
    'Retry': 'Повторити',
    'Refresh': 'Оновити',
    'Select': 'Вибрати',
    'Select All': 'Вибрати все',
    'Clear': 'Очистити',
    'Clear All': 'Очистити все',
    'Clear all': 'Очистити все',
    'Clear Filters': 'Скинути фільтри',
    'Search': 'Пошук',
    'Filter': 'Фільтр',
    'Export': 'Експорт',
    'Export CSV': 'Експорт CSV',
    'Import': 'Імпорт',
    'Download': 'Завантажити',
    'Download PDF': 'Завантажити PDF',
    'Upload': 'Вивантажити',
    'Print': 'Друк',
    'Send': 'Надіслати',
    'Submit': 'Надіслати',
    'Approve': 'Затвердити',
    'Reject': 'Відхилити',
    'Generate': 'Створити',
    'Create': 'Створити',
    'Update': 'Оновити',
    'Confirm': 'Підтвердити',
    'Done': 'Готово',
    'Yes': 'Так',
    'No': 'Ні',
    'Actions': 'Дії',
    'Help': 'Довідка',

    'Status': 'Статус',
    'Active': 'Активний',
    'Inactive': 'Неактивний',
    'Pending': 'В очікуванні',
    'Approved': 'Затверджено',
    'Rejected': 'Відхилено',
    'Paid': 'Сплачено',
    'Unpaid': 'Не сплачено',
    'Draft': 'Чернетка',
    'Sent': 'Надіслано',
    'Overdue': 'Прострочено',
    'Cancelled': 'Скасовано',
    'Completed': 'Завершено',
    'Submitted': 'Подано',
    'Incomplete': 'Не заповнено',
    'Required': "Обов'язково",
    'Optional': "Необов'язково",
    'Current': 'Поточний',
    'Not set': 'Не задано',
    'Loading...': 'Завантаження...',
    'Loading': 'Завантаження',

    'Dashboard': 'Панель',
    'Employee': 'Працівник',
    'Employees': 'Працівники',
    'Customer': 'Клієнт',
    'Customers': 'Клієнти',
    'Project': 'Проєкт',
    'Projects': 'Проєкти',
    'Work Logs': 'Облік годин',
    'Worklogs': 'Облік годин',
    'Invoice': 'Рахунок',
    'Invoices': 'Рахунки',
    'Agency': 'Агенція',
    'Agencies': 'Агенції',
    'Agency Invoices': 'Рахунки агенцій',
    'Expenses': 'Витрати',
    'Expense': 'Витрата',
    'Wallet': 'Гаманець',
    'Settings': 'Налаштування',
    'Notifications': 'Сповіщення',
    'Reports': 'Звіти',
    'Certificates': 'Сертифікати',
    'Payslips': 'Розрахункові листи',
    'Payroll': 'Нарахування зарплати',
    'Attendance': 'Відвідуваність',
    'Leave Requests': 'Заявки на відпустку',
    'Contracts': 'Договори',
    'Services': 'Послуги',
    'Service': 'Послуга',
    'Supervisor': 'Керівник',
    'Supervisors': 'Керівники',
    'Allowances': 'Надбавки',
    'Allowance': 'Надбавка',
    'Gratuities': 'Чайові',
    'Shifts': 'Зміни',
    'Shift': 'Зміна',
    'Document': 'Документ',
    'Documents': 'Документи',
    'Administrator': 'Адміністратор',
    'Logout': 'Вийти',
    'Logout Account': 'Вийти з облікового запису',

    'Name': "Ім'я",
    'First Name': "Ім'я",
    'First name': "Ім'я",
    'Last Name': 'Прізвище',
    'Last name': 'Прізвище',
    'Email': 'Ел. пошта',
    'Email Address': 'Адреса ел. пошти',
    'Email Addresses': 'Адреси ел. пошти',
    'Phone': 'Телефон',
    'Phone Numbers': 'Номери телефонів',
    'Address': 'Адреса',
    'City': 'Місто',
    'Postcode': 'Поштовий індекс',
    'Street Name': 'Вулиця',
    'House Nr.': 'Будинок №',
    'Add.': 'Дод.',
    'Country': 'Країна',
    'Nationality': 'Громадянство',
    'Gender': 'Стать',
    'Date of Birth': 'Дата народження',
    'Birthplace': 'Місце народження',
    'Password': 'Пароль',
    'Description': 'Опис',
    'Notes': 'Нотатки',
    'Notes (Optional)': "Нотатки (необов'язково)",
    'Code': 'Код',
    'Type': 'Тип',
    'Category': 'Категорія',
    'Amount': 'Сума',
    'Price': 'Ціна',
    'Rate': 'Ставка',
    'Hourly Rate': 'Погодинна ставка',
    'Base Price': 'Базова ціна',
    'Total': 'Разом',
    'Subtotal': 'Проміжний підсумок',
    'Date': 'Дата',
    'Time': 'Час',
    'Date & Time': 'Дата й час',
    'Start': 'Початок',
    'End': 'Кінець',
    'Start Date': 'Дата початку',
    'End Date': 'Дата завершення',
    'Start Time': 'Час початку',
    'End Time': 'Час завершення',
    'Start Date/Time': 'Дата/час початку',
    'End Date/Time': 'Дата/час завершення',
    'Expiry Date': 'Термін дії',
    'Issue Date': 'Дата виставлення',
    'Effective From': 'Діє з',
    'Effective To': 'Діє до',
    'From': 'З',
    'To': 'До',
    'From Time': 'З якого часу',
    'To Time': 'До якого часу',
    'From Week': 'З тижня',
    'To Week': 'До тижня',
    'Period': 'Період',
    'Day': 'День',
    'Days': 'Дні',
    'Hours': 'Години',
    'Total Hours': 'Усього годин',
    'Normal Hours': 'Звичайні години',
    'Pause': 'Перерва',
    'Breaks': 'Перерви',
    'Location': 'Розташування',
    'Company Name': 'Назва компанії',
    'Company Information': 'Дані компанії',
    'Contact Information': 'Контактні дані',
    'Financial Information': 'Фінансові дані',
    'Personal Information': 'Особисті дані',
    'Contract Information': 'Дані договору',
    'Contract Type': 'Тип договору',
    'Contract History': 'Історія договорів',
    'Document Type': 'Тип документа',
    'Document Number': 'Номер документа',
    'ID Document': 'Посвідчення особи',
    "Driver's License": 'Посвідчення водія',
    'Front Side': 'Лицьовий бік',
    'Back Side': 'Зворотний бік',
    'PDF Document': 'PDF-документ',
    'Uploaded By': 'Завантажив',
    'Sort Order': 'Порядок сортування',
    'Is Active': 'Активний',
    'Reference #': 'Номер посилання',
    'Payment Method': 'Спосіб оплати',
    'Vendor Name': 'Постачальник',
    'Prefix': 'Префікс',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'Номер KvK',
    'BTW Number': 'Номер ПДВ',
    'G-Rekening': 'G-рахунок',

    'No data': 'Немає даних',
    'No data available': 'Дані відсутні',
    'No customers found': 'Клієнтів не знайдено',
    'No employees found': 'Працівників не знайдено',
    'No projects found': 'Проєктів не знайдено',
    'No services found': 'Послуг не знайдено',
    'No supervisors found': 'Керівників не знайдено',
    'No supervisors added yet': 'Керівників ще не додано',
    'No phone numbers available': 'Немає доступних телефонів',
    'No email addresses available': 'Немає доступних адрес',
    'No nationality found': 'Громадянство не знайдено',
    'Search customers...': 'Пошук клієнтів...',
    'Search employees...': 'Пошук працівників...',
    'Search employee...': 'Пошук працівника...',
    'Search nationality...': 'Пошук громадянства...',
    'Search allowance types...': 'Пошук типів надбавок...',
    'Select...': 'Виберіть...',
    'Select customer...': 'Виберіть клієнта...',
    'Select project...': 'Виберіть проєкт...',
    'Select service...': 'Виберіть послугу...',
    'Select supervisor...': 'Виберіть керівника...',
    'Select category...': 'Виберіть категорію...',
    'Select nationality...': 'Виберіть громадянство...',
    'Select email...': 'Виберіть ел. пошту...',
    'Select phone...': 'Виберіть телефон...',
    'Today': 'Сьогодні',
    'Toggle menu': 'Перемкнути меню',
};

/** Phrase tables per language. English is the key space and needs no table. */
export const phrases: Record<string, PhraseTable> = { nl, ar, ru, uk };
