/**
 * Phrase-keyed translations.
 *
 * The camelCase table in `i18n.tsx` covers the dashboard home and navigation.
 * Everywhere else the UI was written as literal English in JSX, so switching
 * language changed nothing. Keying on the English phrase itself lets those
 * screens be wrapped in `t(...)` without inventing a key name for each of the
 * ~860 strings, and anything not yet listed here falls back to the English it
 * already displayed rather than to a raw key.
 */

export type PhraseTable = Record<string, string>;

/** English is the key space, so it needs no table of its own. */
const nl: PhraseTable = {
    // Reports date ranges
    'This month': 'Deze maand',
    'This year': 'Dit jaar',
    'Last 12 months': 'Laatste 12 maanden',
    'No approved hours between': 'Geen goedgekeurde uren tussen',
    'Widen the range to see earlier work': 'Verruim de periode om eerder werk te zien',
    'and': 'en',
    'to': 'tot',

    // Wallet page
    'Total Balance': 'Totaal saldo',
    'Balance': 'Saldo',
    'Advances': 'Voorschotten',
    'Pending Advances': 'Openstaande voorschotten',
    'Employee Wallets': 'Portemonnees medewerkers',
    'Advance requests waiting for a decision': 'Voorschotaanvragen die op een besluit wachten',
    'No pending advance requests': 'Geen openstaande voorschotaanvragen',
    'Select a wallet to see its recent transactions': 'Selecteer een portemonnee om de recente transacties te zien',
    'No wallets yet': 'Nog geen portemonnees',
    'A wallet appears once an employee has approved hours': 'Een portemonnee verschijnt zodra een medewerker goedgekeurde uren heeft',
    'No transactions yet': 'Nog geen transacties',
    'Employee balances and advance requests': 'Saldi van medewerkers en voorschotaanvragen',

    // Reports warnings
    'Earnings are incomplete': 'Verdiensten zijn onvolledig',
    'These employees have no hourly rate on their profile, so their pay cannot be calculated': 'Deze medewerkers hebben geen uurtarief in hun profiel, dus hun loon kan niet worden berekend',

    // Remaining page copy
    'Allowances (Toeslag)': 'Toeslagen',
    'Gratuities (Fooi)': 'Fooien',
    'Enable Percentage Surcharges': 'Procentuele toeslagen inschakelen',
    'TOTAL': 'TOTAAL',
    'Are you sure you want to delete': 'Weet u zeker dat u dit wilt verwijderen',
    'Enter custom allowance name...': 'Naam aangepaste toeslag invoeren...',
    'Search and select employees...': 'Medewerkers zoeken en selecteren...',
    'Search employees…': 'Medewerkers zoeken…',
    'Upload front and back, or a single PDF': 'Upload voor- en achterzijde, of één pdf',
    'Optional description...': 'Optionele omschrijving...',
    'Optional notes...': 'Optionele notities...',
    'Select a customer...': 'Selecteer een klant...',
    'Loading supervisors...': 'Leidinggevenden laden...',
    'No supervisors found for this customer': 'Geen leidinggevenden voor deze klant',
    'Supervisor (Rayon)': 'Leidinggevende (rayon)',
    'Rayon Name': 'Rayonnaam',
    'Location / Address Notes': 'Locatie- / adresnotities',
    'Enter address, building, floor, etc...': 'Adres, gebouw, verdieping enz. invoeren...',
    'Generate quarters': 'Kwartalen genereren',
    'HR Email (for Reports)': 'HR-e-mail (voor rapporten)',
    'This email will appear on HR export reports': 'Dit e-mailadres verschijnt op HR-exportrapporten',
    'Select services and set prices for this customer': 'Selecteer diensten en stel prijzen in voor deze klant',
    'Add extra rates for weekends, nights, holidays on services': 'Extra tarieven voor weekenden, nachten en feestdagen op diensten',
    'Add extra rates for weekends, nights, holidays on allowances': 'Extra tarieven voor weekenden, nachten en feestdagen op toeslagen',
    'Service Surcharge Types': 'Diensttoeslagtypen',
    'Allowance Surcharge Types': 'Toeslagtypen op toeslagen',
    'No services available. Add some in Services Management.': 'Geen diensten beschikbaar. Voeg ze toe bij Dienstenbeheer.',
    'Custom allowances for this customer (e.g., Mask, Hazard Pay)': 'Aangepaste toeslagen voor deze klant (bijv. masker, gevarengeld)',
    'Name...': 'Naam...',
    'Code...': 'Code...',
    'Previous slide': 'Vorige slide',
    'Next slide': 'Volgende slide',
    'Click to upload or drag and drop': 'Klik om te uploaden of sleep het bestand hierheen',
    'PDF, DOC, DOCX up to 10MB': 'PDF, DOC, DOCX tot 10 MB',
    'Contracts will be uploaded after the customer is created.': 'Contracten worden geüpload nadat de klant is aangemaakt.',
    'Admin User': 'Beheerder',
    'Main': 'Hoofd',
    'Loading worklogs...': 'Werkuren laden...',
    'No worklogs found. Please select filters first.': 'Geen werkuren gevonden. Selecteer eerst filters.',
    'Export for HR': 'Export voor HR',
    'Export for Finance': 'Export voor financiën',
    'Export for Employee (Simple)': 'Export voor medewerker (eenvoudig)',
    'Generate invoice record from these': 'Factuurregistratie hieruit genereren',
    'Receipt (Photo/PDF)': 'Bon (foto/pdf)',
    'Invoice / receipt number': 'Factuur- / bonnummer',
    'Add your first expense to start tracking': 'Voeg uw eerste kostenpost toe om te beginnen',
    'Nothing is unresolved in this period': 'Er is niets onopgelost in deze periode',
    'Deductible input VAT': 'Aftrekbare voorbelasting',
    'Must be resolved before filing': 'Moet vóór indienen worden opgelost',
    'Click a rubriek to see the transactions': 'Klik op een rubriek om de transacties te zien',
    'Contact Information': 'Contactgegevens',

    // Headings, modals and actions
    'Add Certificate': 'Certificaat toevoegen',
    'Add New Customer': 'Nieuwe klant toevoegen',
    'Add Customer': 'Klant toevoegen',
    'Add Supervisor': 'Leidinggevende toevoegen',
    'Add Contract': 'Contract toevoegen',
    'Add Allowance': 'Toeslag toevoegen',
    'Add Allowance Type': 'Toeslagtype toevoegen',
    'Add Work Log': 'Werkuren toevoegen',
    'Add Email': 'E-mail toevoegen',
    'Add Break': 'Pauze toevoegen',
    'Additional Costs': 'Bijkomende kosten',
    'Allowances Configuration': 'Toeslaginstellingen',
    'Services Configuration': 'Dienstinstellingen',
    'Approve Employee': 'Medewerker goedkeuren',
    'Reject Employee': 'Medewerker afwijzen',
    'Certificate Details': 'Certificaatgegevens',
    'Create New Project': 'Nieuw project aanmaken',
    'Project Details': 'Projectgegevens',
    'Project Not Found': 'Project niet gevonden',
    'Customer Not Found': 'Klant niet gevonden',
    'No Projects Found': 'Geen projecten gevonden',
    'Delete Customer': 'Klant verwijderen',
    'Delete Employee': 'Medewerker verwijderen',
    'Delete Project': 'Project verwijderen',
    'Edit Customer': 'Klant bewerken',
    'Edit Employee Profile': 'Medewerkersprofiel bewerken',
    'Employee Created!': 'Medewerker aangemaakt!',
    'Extract Documents': 'Documenten exporteren',
    'General Manager': 'Algemeen directeur',
    'Labor Hours': 'Arbeidsuren',
    'New Portal Login': 'Nieuwe portaallogin',
    'Portal Access': 'Portaaltoegang',
    'Rate Change Detected': 'Tariefwijziging gedetecteerd',
    'Shift Scheduling': 'Dienstplanning',
    'Schedule Shifts': 'Diensten inplannen',
    'Schedule New Shift': 'Nieuwe dienst inplannen',
    'Upload New Contract': 'Nieuw contract uploaden',
    'Wallet Management': 'Portemonneebeheer',
    'Contract Documents': 'Contractdocumenten',
    'Assignment Details': 'Toewijzingsgegevens',
    'Rejection Reason': 'Reden van afwijzing',
    'Worklog Status': 'Status werkuren',
    'Generate Invoice': 'Factuur genereren',
    'Create Invoice': 'Factuur aanmaken',
    'Export Timesheet': 'Urenstaat exporteren',
    'Time Window': 'Tijdvenster',
    'Service Type': 'Diensttype',
    'Allowance Type': 'Toeslagtype',
    'Custom / Other': 'Aangepast / overig',
    'Custom Allowance Name': 'Naam aangepaste toeslag',
    'Total Types': 'Totaal typen',
    'Back to Customers': 'Terug naar klanten',
    'Back to Work Logs': 'Terug naar werkuren',
    'Back to Projects': 'Terug naar projecten',
    'Specific Dates': 'Specifieke datums',
    'Active Days': 'Actieve dagen',
    'Active Customer': 'Actieve klant',
    'Is Active': 'Is actief',
    'Requires Agency': 'Bureau vereist',
    'Requires End Date': 'Einddatum vereist',
    'Special Instructions': 'Bijzondere instructies',
    'Work location': 'Werklocatie',
    'Supervisor Phone': 'Telefoon leidinggevende',
    'Supervisor Email': 'E-mail leidinggevende',
    'To Pay Employees': 'Aan medewerkers te betalen',
    'To Charge Customer': 'Aan klant te factureren',
    'To Charge': 'Te factureren',
    'Save Expense': 'Kosten opslaan',
    'Vendor Name': 'Leveranciersnaam',
    'Payment Method': 'Betaalmethode',
    'Total (incl. BTW)': 'Totaal (incl. btw)',
    'Amount (excl. BTW)': 'Bedrag (excl. btw)',
    'BTW Rate': 'Btw-tarief',
    'BTW Paid': 'Betaalde btw',
    'Clear Filters': 'Filters wissen',
    'Refresh': 'Vernieuwen',
    'Close': 'Sluiten',

    // Navigation
    'Weekly Board': 'Weekoverzicht',
    'Contract Types': 'Contracttypen',
    'Day Payment Types': 'Dagtoeslagtypen',
    'HR': 'HR',
    'Finance': 'Financiën',
    'Outgoing Invoices': 'Uitgaande facturen',
    'Incoming Invoices': 'Inkomende facturen',
    'Financial Overview': 'Financieel overzicht',
    'BTW Aangifte': 'Btw-aangifte',
    'Expenses Summary': 'Kostenoverzicht',
    'Allowance Types': 'Toeslagtypen',

    // Actions
    'Save': 'Opslaan',
    'Cancel': 'Annuleren',
    'Delete': 'Verwijderen',
    'Edit': 'Bewerken',
    'Add': 'Toevoegen',
    'View': 'Bekijken',
    'Back': 'Terug',
    'Next': 'Volgende',
    'Previous': 'Vorige',
    'Prev': 'Vorige',
    'Retry': 'Opnieuw',
    'Select': 'Selecteren',
    'Select All': 'Alles selecteren',
    'Clear': 'Wissen',
    'Clear All': 'Alles wissen',
    'Clear all': 'Alles wissen',
    'Search': 'Zoeken',
    'Filter': 'Filteren',
    'Export': 'Exporteren',
    'Export CSV': 'CSV exporteren',
    'Import': 'Importeren',
    'Download': 'Downloaden',
    'Download PDF': 'PDF downloaden',
    'Upload': 'Uploaden',
    'Print': 'Afdrukken',
    'Send': 'Versturen',
    'Submit': 'Indienen',
    'Approve': 'Goedkeuren',
    'Reject': 'Afwijzen',
    'Generate': 'Genereren',
    'Create': 'Aanmaken',
    'Update': 'Bijwerken',
    'Confirm': 'Bevestigen',
    'Done': 'Klaar',
    'Yes': 'Ja',
    'No': 'Nee',
    'Actions': 'Acties',
    'Help': 'Help',

    // Status
    'Status': 'Status',
    'Active': 'Actief',
    'Inactive': 'Inactief',
    'Pending': 'In afwachting',
    'Approved': 'Goedgekeurd',
    'Rejected': 'Afgewezen',
    'Paid': 'Betaald',
    'Unpaid': 'Onbetaald',
    'Draft': 'Concept',
    'Sent': 'Verstuurd',
    'Overdue': 'Achterstallig',
    'Cancelled': 'Geannuleerd',
    'Completed': 'Afgerond',
    'Submitted': 'Ingediend',
    'Incomplete': 'Onvolledig',
    'Required': 'Verplicht',
    'Optional': 'Optioneel',
    'Current': 'Huidig',
    'Not set': 'Niet ingesteld',
    'Loading...': 'Laden...',
    'Loading': 'Laden',

    // Entities
    'Dashboard': 'Dashboard',
    'Employee': 'Medewerker',
    'Employees': 'Medewerkers',
    'Customer': 'Klant',
    'Customers': 'Klanten',
    'Project': 'Project',
    'Projects': 'Projecten',
    'Work Logs': 'Werkuren',
    'Worklogs': 'Werkuren',
    'Invoice': 'Factuur',
    'Invoices': 'Facturen',
    'Agency': 'Bureau',
    'Agencies': 'Bureaus',
    'Agency Invoices': 'Bureaufacturen',
    'Expenses': 'Kosten',
    'Expense': 'Kostenpost',
    'Wallet': 'Portemonnee',
    'Settings': 'Instellingen',
    'Notifications': 'Meldingen',
    'Reports': 'Rapporten',
    'Certificates': 'Certificaten',
    'Payslips': 'Loonstroken',
    'Payroll': 'Salarisadministratie',
    'Attendance': 'Aanwezigheid',
    'Leave Requests': 'Verlofaanvragen',
    'Contracts': 'Contracten',
    'Services': 'Diensten',
    'Service': 'Dienst',
    'Supervisor': 'Leidinggevende',
    'Supervisors': 'Leidinggevenden',
    'Allowances': 'Toeslagen',
    'Allowance': 'Toeslag',
    'Gratuities': 'Fooien',
    'Shifts': 'Diensten',
    'Shift': 'Dienst',
    'Document': 'Document',
    'Documents': 'Documenten',
    'Administrator': 'Beheerder',
    'Logout': 'Uitloggen',
    'Logout Account': 'Account uitloggen',

    // Fields
    'Name': 'Naam',
    'First Name': 'Voornaam',
    'First name': 'Voornaam',
    'Last Name': 'Achternaam',
    'Last name': 'Achternaam',
    'Email': 'E-mail',
    'Email Address': 'E-mailadres',
    'Email Addresses': 'E-mailadressen',
    'Phone': 'Telefoon',
    'Phone Numbers': 'Telefoonnummers',
    'Address': 'Adres',
    'City': 'Plaats',
    'Postcode': 'Postcode',
    'Street Name': 'Straatnaam',
    'House Nr.': 'Huisnr.',
    'Add.': 'Toev.',
    'Country': 'Land',
    'Nationality': 'Nationaliteit',
    'Gender': 'Geslacht',
    'Date of Birth': 'Geboortedatum',
    'Birthplace': 'Geboorteplaats',
    'Password': 'Wachtwoord',
    'Description': 'Omschrijving',
    'Notes': 'Notities',
    'Notes (Optional)': 'Notities (optioneel)',
    'Code': 'Code',
    'Type': 'Type',
    'Category': 'Categorie',
    'Amount': 'Bedrag',
    'Price': 'Prijs',
    'Rate': 'Tarief',
    'Hourly Rate': 'Uurtarief',
    'Base Price': 'Basisprijs',
    'Total': 'Totaal',
    'Subtotal': 'Subtotaal',
    'Date': 'Datum',
    'Time': 'Tijd',
    'Date & Time': 'Datum & tijd',
    'Start': 'Start',
    'End': 'Einde',
    'Start Date': 'Startdatum',
    'End Date': 'Einddatum',
    'Start Time': 'Starttijd',
    'End Time': 'Eindtijd',
    'Start Date/Time': 'Startdatum/-tijd',
    'End Date/Time': 'Einddatum/-tijd',
    'Expiry Date': 'Vervaldatum',
    'Issue Date': 'Factuurdatum',
    'Effective From': 'Geldig vanaf',
    'Effective To': 'Geldig tot',
    'From': 'Van',
    'To': 'Tot',
    'From Time': 'Van tijd',
    'To Time': 'Tot tijd',
    'From Week': 'Van week',
    'To Week': 'Tot week',
    'Period': 'Periode',
    'Day': 'Dag',
    'Days': 'Dagen',
    'Hours': 'Uren',
    'Total Hours': 'Totaal uren',
    'Normal Hours': 'Normale uren',
    'Pause': 'Pauze',
    'Breaks': 'Pauzes',
    'Location': 'Locatie',
    'Company Name': 'Bedrijfsnaam',
    'Company Information': 'Bedrijfsgegevens',
    'Financial Information': 'Financiële gegevens',
    'Personal Information': 'Persoonlijke gegevens',
    'Contract Information': 'Contractgegevens',
    'Contract Type': 'Contracttype',
    'Contract History': 'Contracthistorie',
    'Document Type': 'Documenttype',
    'Document Number': 'Documentnummer',
    'ID Document': 'Identiteitsbewijs',
    "Driver's License": 'Rijbewijs',
    'Front Side': 'Voorzijde',
    'Back Side': 'Achterzijde',
    'PDF Document': 'PDF-document',
    'Uploaded By': 'Geüpload door',
    'Sort Order': 'Sorteervolgorde',
    'Reference #': 'Referentienr.',
    'Prefix': 'Voorvoegsel',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'KvK-nummer',
    'BTW Number': 'Btw-nummer',
    'G-Rekening': 'G-rekening',

    // Empty and helper states
    'No data': 'Geen gegevens',
    'No data available': 'Geen gegevens beschikbaar',
    'No customers found': 'Geen klanten gevonden',
    'No employees found': 'Geen medewerkers gevonden',
    'No projects found': 'Geen projecten gevonden',
    'No services found': 'Geen diensten gevonden',
    'No supervisors found': 'Geen leidinggevenden gevonden',
    'No supervisors added yet': 'Nog geen leidinggevenden toegevoegd',
    'No phone numbers available': 'Geen telefoonnummers beschikbaar',
    'No email addresses available': 'Geen e-mailadressen beschikbaar',
    'No nationality found': 'Geen nationaliteit gevonden',
    'Search customers...': 'Klanten zoeken...',
    'Search employees...': 'Medewerkers zoeken...',
    'Search employee...': 'Medewerker zoeken...',
    'Search nationality...': 'Nationaliteit zoeken...',
    'Search allowance types...': 'Toeslagtypen zoeken...',
    'Select...': 'Selecteren...',
    'Select customer...': 'Klant selecteren...',
    'Select project...': 'Project selecteren...',
    'Select service...': 'Dienst selecteren...',
    'Select supervisor...': 'Leidinggevende selecteren...',
    'Select category...': 'Categorie selecteren...',
    'Select nationality...': 'Nationaliteit selecteren...',
    'Select email...': 'E-mail selecteren...',
    'Select phone...': 'Telefoon selecteren...',
    'Today': 'Vandaag',
    'Toggle menu': 'Menu wisselen',
};

const ar: PhraseTable = {
    // Reports date ranges
    'This month': 'هذا الشهر',
    'This year': 'هذه السنة',
    'Last 12 months': 'آخر ١٢ شهراً',
    'No approved hours between': 'لا توجد ساعات معتمدة بين',
    'Widen the range to see earlier work': 'وسّع الفترة لعرض عمل سابق',
    'and': 'و',
    'to': 'إلى',

    // Wallet page
    'Total Balance': 'إجمالي الرصيد',
    'Balance': 'الرصيد',
    'Advances': 'السلف',
    'Pending Advances': 'السلف المعلقة',
    'Employee Wallets': 'محافظ الموظفين',
    'Advance requests waiting for a decision': 'طلبات السلف بانتظار القرار',
    'No pending advance requests': 'لا توجد طلبات سلف معلقة',
    'Select a wallet to see its recent transactions': 'اختر محفظة لعرض معاملاتها الأخيرة',
    'No wallets yet': 'لا توجد محافظ بعد',
    'A wallet appears once an employee has approved hours': 'تظهر المحفظة بمجرد اعتماد ساعات الموظف',
    'No transactions yet': 'لا توجد معاملات بعد',
    'Employee balances and advance requests': 'أرصدة الموظفين وطلبات السلف',

    // Reports warnings
    'Earnings are incomplete': 'الأرباح غير مكتملة',
    'These employees have no hourly rate on their profile, so their pay cannot be calculated': 'لا يوجد أجر بالساعة في ملفات هؤلاء الموظفين، لذا لا يمكن حساب رواتبهم',

    // Remaining page copy
    'Allowances (Toeslag)': 'البدلات',
    'Gratuities (Fooi)': 'الإكراميات',
    'Enable Percentage Surcharges': 'تفعيل البدلات النسبية',
    'TOTAL': 'الإجمالي',
    'Are you sure you want to delete': 'هل أنت متأكد من الحذف',
    'Enter custom allowance name...': 'أدخل اسم البدل المخصص...',
    'Search and select employees...': 'ابحث واختر الموظفين...',
    'Search employees…': 'ابحث عن الموظفين…',
    'Upload front and back, or a single PDF': 'ارفع الوجهين أو ملف PDF واحد',
    'Optional description...': 'وصف اختياري...',
    'Optional notes...': 'ملاحظات اختيارية...',
    'Select a customer...': 'اختر عميلاً...',
    'Loading supervisors...': 'جارٍ تحميل المشرفين...',
    'No supervisors found for this customer': 'لا يوجد مشرفون لهذا العميل',
    'Supervisor (Rayon)': 'المشرف (المنطقة)',
    'Rayon Name': 'اسم المنطقة',
    'Location / Address Notes': 'ملاحظات الموقع / العنوان',
    'Enter address, building, floor, etc...': 'أدخل العنوان والمبنى والطابق...',
    'Generate quarters': 'إنشاء الأرباع',
    'HR Email (for Reports)': 'بريد الموارد البشرية (للتقارير)',
    'This email will appear on HR export reports': 'سيظهر هذا البريد في تقارير الموارد البشرية',
    'Select services and set prices for this customer': 'اختر الخدمات وحدد الأسعار لهذا العميل',
    'Add extra rates for weekends, nights, holidays on services': 'أضف تعرفات إضافية لعطلات نهاية الأسبوع والليالي والأعياد على الخدمات',
    'Add extra rates for weekends, nights, holidays on allowances': 'أضف تعرفات إضافية لعطلات نهاية الأسبوع والليالي والأعياد على البدلات',
    'Service Surcharge Types': 'أنواع بدلات الخدمة',
    'Allowance Surcharge Types': 'أنواع البدلات الإضافية',
    'No services available. Add some in Services Management.': 'لا توجد خدمات. أضفها من إدارة الخدمات.',
    'Custom allowances for this customer (e.g., Mask, Hazard Pay)': 'بدلات مخصصة لهذا العميل (مثل الكمامة، بدل الخطر)',
    'Name...': 'الاسم...',
    'Code...': 'الرمز...',
    'Previous slide': 'الشريحة السابقة',
    'Next slide': 'الشريحة التالية',
    'Click to upload or drag and drop': 'انقر للرفع أو اسحب الملف وأفلته',
    'PDF, DOC, DOCX up to 10MB': 'PDF أو DOC أو DOCX حتى ١٠ ميغابايت',
    'Contracts will be uploaded after the customer is created.': 'سيتم رفع العقود بعد إنشاء العميل.',
    'Admin User': 'مستخدم مسؤول',
    'Main': 'رئيسي',
    'Loading worklogs...': 'جارٍ تحميل سجلات العمل...',
    'No worklogs found. Please select filters first.': 'لم يتم العثور على سجلات عمل. اختر عوامل التصفية أولاً.',
    'Export for HR': 'تصدير للموارد البشرية',
    'Export for Finance': 'تصدير للمالية',
    'Export for Employee (Simple)': 'تصدير للموظف (مبسّط)',
    'Generate invoice record from these': 'إنشاء سجل فاتورة من هذه',
    'Receipt (Photo/PDF)': 'الإيصال (صورة/PDF)',
    'Invoice / receipt number': 'رقم الفاتورة / الإيصال',
    'Add your first expense to start tracking': 'أضف أول مصروف لبدء التتبع',
    'Nothing is unresolved in this period': 'لا يوجد شيء غير محلول في هذه الفترة',
    'Deductible input VAT': 'ضريبة المدخلات القابلة للخصم',
    'Must be resolved before filing': 'يجب حلها قبل التقديم',
    'Click a rubriek to see the transactions': 'انقر على بند لعرض المعاملات',
    'Contact Information': 'معلومات الاتصال',

    // Headings, modals and actions
    'Add Certificate': 'إضافة شهادة',
    'Add New Customer': 'إضافة عميل جديد',
    'Add Customer': 'إضافة عميل',
    'Add Supervisor': 'إضافة مشرف',
    'Add Contract': 'إضافة عقد',
    'Add Allowance': 'إضافة بدل',
    'Add Allowance Type': 'إضافة نوع بدل',
    'Add Work Log': 'إضافة سجل عمل',
    'Add Email': 'إضافة بريد إلكتروني',
    'Add Break': 'إضافة استراحة',
    'Additional Costs': 'تكاليف إضافية',
    'Allowances Configuration': 'إعدادات البدلات',
    'Services Configuration': 'إعدادات الخدمات',
    'Approve Employee': 'اعتماد الموظف',
    'Reject Employee': 'رفض الموظف',
    'Certificate Details': 'تفاصيل الشهادة',
    'Create New Project': 'إنشاء مشروع جديد',
    'Project Details': 'تفاصيل المشروع',
    'Project Not Found': 'المشروع غير موجود',
    'Customer Not Found': 'العميل غير موجود',
    'No Projects Found': 'لم يتم العثور على مشاريع',
    'Delete Customer': 'حذف العميل',
    'Delete Employee': 'حذف الموظف',
    'Delete Project': 'حذف المشروع',
    'Edit Customer': 'تعديل العميل',
    'Edit Employee Profile': 'تعديل ملف الموظف',
    'Employee Created!': 'تم إنشاء الموظف!',
    'Extract Documents': 'استخراج المستندات',
    'General Manager': 'المدير العام',
    'Labor Hours': 'ساعات العمل',
    'New Portal Login': 'تسجيل دخول جديد للبوابة',
    'Portal Access': 'الوصول إلى البوابة',
    'Rate Change Detected': 'تم رصد تغيير في التعرفة',
    'Shift Scheduling': 'جدولة المناوبات',
    'Schedule Shifts': 'جدولة المناوبات',
    'Schedule New Shift': 'جدولة مناوبة جديدة',
    'Upload New Contract': 'رفع عقد جديد',
    'Wallet Management': 'إدارة المحفظة',
    'Contract Documents': 'مستندات العقد',
    'Assignment Details': 'تفاصيل التكليف',
    'Rejection Reason': 'سبب الرفض',
    'Worklog Status': 'حالة سجل العمل',
    'Generate Invoice': 'إنشاء فاتورة',
    'Create Invoice': 'إنشاء فاتورة',
    'Export Timesheet': 'تصدير سجل الساعات',
    'Time Window': 'النافذة الزمنية',
    'Service Type': 'نوع الخدمة',
    'Allowance Type': 'نوع البدل',
    'Custom / Other': 'مخصص / أخرى',
    'Custom Allowance Name': 'اسم البدل المخصص',
    'Total Types': 'إجمالي الأنواع',
    'Back to Customers': 'العودة إلى العملاء',
    'Back to Work Logs': 'العودة إلى سجلات العمل',
    'Back to Projects': 'العودة إلى المشاريع',
    'Specific Dates': 'تواريخ محددة',
    'Active Days': 'الأيام النشطة',
    'Active Customer': 'عميل نشط',
    'Is Active': 'نشط',
    'Requires Agency': 'يتطلب وكالة',
    'Requires End Date': 'يتطلب تاريخ انتهاء',
    'Special Instructions': 'تعليمات خاصة',
    'Work location': 'موقع العمل',
    'Supervisor Phone': 'هاتف المشرف',
    'Supervisor Email': 'بريد المشرف',
    'To Pay Employees': 'المستحق للموظفين',
    'To Charge Customer': 'المستحق على العميل',
    'To Charge': 'للفوترة',
    'Save Expense': 'حفظ المصروف',
    'Vendor Name': 'اسم المورّد',
    'Payment Method': 'طريقة الدفع',
    'Total (incl. BTW)': 'الإجمالي (شامل الضريبة)',
    'Amount (excl. BTW)': 'المبلغ (بدون ضريبة)',
    'BTW Rate': 'نسبة الضريبة',
    'BTW Paid': 'الضريبة المدفوعة',
    'Clear Filters': 'مسح عوامل التصفية',
    'Refresh': 'تحديث',
    'Close': 'إغلاق',

    // Dutch-source screens (finance, VAT, invoices)
    'Annuleren': 'إلغاء',
    'Versturen': 'إرسال',
    'Sluiten': 'إغلاق',
    'Bedrag': 'المبلغ',
    'Datum': 'التاريخ',
    'Uren': 'الساعات',
    'Tarief': 'التعرفة',
    'Omzet': 'الإيرادات',
    'Kosten': 'التكاليف',
    'Regels': 'البنود',
    'Totalen': 'الإجماليات',
    'Posten': 'القيود',
    'Rubriek': 'البند',
    'Rubrieken': 'البنود',
    'Creditnota': 'إشعار دائن',
    'Creditnota\'s': 'إشعارات دائنة',
    'Creditnota maken': 'إنشاء إشعار دائن',
    'Verlegd': 'ضريبة معكوسة',
    'Btw verlegd': 'ضريبة القيمة المضافة معكوسة',
    'Btw-behandeling': 'معالجة ضريبة القيمة المضافة',
    'Onderbouwing': 'التبرير',
    'Vast te stellen': 'قيد التحديد',
    'Eerst oplossen': 'يجب الحل أولاً',
    'Voorwaarden voor verlegging': 'شروط عكس الضريبة',
    'Uitzonderingen': 'الاستثناءات',
    'Audit trail': 'سجل التدقيق',
    'Omzetbelasting': 'ضريبة المبيعات',
    'Terug naar facturen': 'العودة إلى الفواتير',
    'Open volledige factuur': 'فتح الفاتورة كاملة',
    'Factuur e-mailen': 'إرسال الفاتورة بالبريد',
    'Ontvangen bedrag (€)': 'المبلغ المستلم (€)',
    'Waarom wordt deze factuur gecrediteerd?': 'لماذا يتم إصدار إشعار دائن لهذه الفاتورة؟',
    'Deze factuur kan worden verstuurd.': 'هذه الفاتورة جاهزة للإرسال.',
    'Omzet (excl. btw)': 'الإيرادات (بدون ضريبة)',
    'Kosten (excl. btw)': 'التكاليف (بدون ضريبة)',
    'Brutomarge': 'هامش الربح الإجمالي',
    'Btw per kwartaal': 'ضريبة القيمة المضافة لكل ربع',
    'Berekend uit het btw-grootboek': 'محسوب من دفتر ضريبة القيمة المضافة',
    'Omzet en kosten per maand': 'الإيرادات والتكاليف شهرياً',
    'Grootste klanten': 'أكبر العملاء',
    'Te ontvangen': 'مستحق القبض',
    'Te betalen': 'مستحق الدفع',
    'Nog niet vervallen': 'لم يستحق بعد',
    '1–30 dagen': '١–٣٠ يوماً',
    '31–60 dagen': '٣١–٦٠ يوماً',
    '61–90 dagen': '٦١–٩٠ يوماً',
    '90+ dagen': '٩٠+ يوماً',
    'Uitzendbureaus': 'وكالات التوظيف',
    'Inkoopfacturen': 'فواتير المشتريات',
    'Medewerkers (wallet)': 'الموظفون (المحفظة)',
    'Facturatie en bedrijfsgegevens': 'الفوترة وبيانات الشركة',
    'Btw-identificatienummer': 'رقم تعريف ضريبة القيمة المضافة',
    'Betaaltermijn (dagen)': 'مدة السداد (أيام)',
    'Voettekst op de factuur': 'تذييل الفاتورة',
    'Facturen worden genummerd als': 'ترقّم الفواتير على النحو',

    // Navigation
    'Weekly Board': 'اللوحة الأسبوعية',
    'Contract Types': 'أنواع العقود',
    'Day Payment Types': 'أنواع بدلات اليوم',
    'HR': 'الموارد البشرية',
    'Finance': 'المالية',
    'Outgoing Invoices': 'الفواتير الصادرة',
    'Incoming Invoices': 'الفواتير الواردة',
    'Financial Overview': 'نظرة عامة مالية',
    'BTW Aangifte': 'إقرار ضريبة القيمة المضافة',
    'Expenses Summary': 'ملخص المصروفات',
    'Allowance Types': 'أنواع البدلات',

    'Save': 'حفظ',
    'Cancel': 'إلغاء',
    'Delete': 'حذف',
    'Edit': 'تعديل',
    'Add': 'إضافة',
    'View': 'عرض',
    'Back': 'رجوع',
    'Next': 'التالي',
    'Previous': 'السابق',
    'Prev': 'السابق',
    'Retry': 'إعادة المحاولة',
    'Select': 'اختيار',
    'Select All': 'تحديد الكل',
    'Clear': 'مسح',
    'Clear All': 'مسح الكل',
    'Clear all': 'مسح الكل',
    'Search': 'بحث',
    'Filter': 'تصفية',
    'Export': 'تصدير',
    'Export CSV': 'تصدير CSV',
    'Import': 'استيراد',
    'Download': 'تنزيل',
    'Download PDF': 'تنزيل PDF',
    'Upload': 'رفع',
    'Print': 'طباعة',
    'Send': 'إرسال',
    'Submit': 'إرسال',
    'Approve': 'اعتماد',
    'Reject': 'رفض',
    'Generate': 'إنشاء',
    'Create': 'إنشاء',
    'Update': 'تحديث',
    'Confirm': 'تأكيد',
    'Done': 'تم',
    'Yes': 'نعم',
    'No': 'لا',
    'Actions': 'إجراءات',
    'Help': 'مساعدة',

    'Status': 'الحالة',
    'Active': 'نشط',
    'Inactive': 'غير نشط',
    'Pending': 'قيد الانتظار',
    'Approved': 'معتمد',
    'Rejected': 'مرفوض',
    'Paid': 'مدفوع',
    'Unpaid': 'غير مدفوع',
    'Draft': 'مسودة',
    'Sent': 'مُرسل',
    'Overdue': 'متأخر',
    'Cancelled': 'ملغى',
    'Completed': 'مكتمل',
    'Submitted': 'مُقدَّم',
    'Incomplete': 'غير مكتمل',
    'Required': 'مطلوب',
    'Optional': 'اختياري',
    'Current': 'الحالي',
    'Not set': 'غير محدد',
    'Loading...': 'جارٍ التحميل...',
    'Loading': 'جارٍ التحميل',

    'Dashboard': 'لوحة التحكم',
    'Employee': 'موظف',
    'Employees': 'الموظفون',
    'Customer': 'عميل',
    'Customers': 'العملاء',
    'Project': 'مشروع',
    'Projects': 'المشاريع',
    'Work Logs': 'سجلات العمل',
    'Worklogs': 'سجلات العمل',
    'Invoice': 'فاتورة',
    'Invoices': 'الفواتير',
    'Agency': 'وكالة',
    'Agencies': 'الوكالات',
    'Agency Invoices': 'فواتير الوكالات',
    'Expenses': 'المصروفات',
    'Expense': 'مصروف',
    'Wallet': 'المحفظة',
    'Settings': 'الإعدادات',
    'Notifications': 'الإشعارات',
    'Reports': 'التقارير',
    'Certificates': 'الشهادات',
    'Payslips': 'كشوف الرواتب',
    'Payroll': 'الرواتب',
    'Attendance': 'الحضور',
    'Leave Requests': 'طلبات الإجازة',
    'Contracts': 'العقود',
    'Services': 'الخدمات',
    'Service': 'خدمة',
    'Supervisor': 'المشرف',
    'Supervisors': 'المشرفون',
    'Allowances': 'البدلات',
    'Allowance': 'بدل',
    'Gratuities': 'الإكراميات',
    'Shifts': 'المناوبات',
    'Shift': 'مناوبة',
    'Document': 'مستند',
    'Documents': 'المستندات',
    'Administrator': 'المسؤول',
    'Logout': 'تسجيل الخروج',
    'Logout Account': 'تسجيل خروج الحساب',

    'Name': 'الاسم',
    'First Name': 'الاسم الأول',
    'First name': 'الاسم الأول',
    'Last Name': 'اسم العائلة',
    'Last name': 'اسم العائلة',
    'Email': 'البريد الإلكتروني',
    'Email Address': 'عنوان البريد الإلكتروني',
    'Email Addresses': 'عناوين البريد الإلكتروني',
    'Phone': 'الهاتف',
    'Phone Numbers': 'أرقام الهاتف',
    'Address': 'العنوان',
    'City': 'المدينة',
    'Postcode': 'الرمز البريدي',
    'Street Name': 'اسم الشارع',
    'House Nr.': 'رقم المنزل',
    'Add.': 'إضافة',
    'Country': 'الدولة',
    'Nationality': 'الجنسية',
    'Gender': 'الجنس',
    'Date of Birth': 'تاريخ الميلاد',
    'Birthplace': 'مكان الميلاد',
    'Password': 'كلمة المرور',
    'Description': 'الوصف',
    'Notes': 'ملاحظات',
    'Notes (Optional)': 'ملاحظات (اختياري)',
    'Code': 'الرمز',
    'Type': 'النوع',
    'Category': 'الفئة',
    'Amount': 'المبلغ',
    'Price': 'السعر',
    'Rate': 'التعرفة',
    'Hourly Rate': 'الأجر بالساعة',
    'Base Price': 'السعر الأساسي',
    'Total': 'الإجمالي',
    'Subtotal': 'المجموع الفرعي',
    'Date': 'التاريخ',
    'Time': 'الوقت',
    'Date & Time': 'التاريخ والوقت',
    'Start': 'البداية',
    'End': 'النهاية',
    'Start Date': 'تاريخ البداية',
    'End Date': 'تاريخ النهاية',
    'Start Time': 'وقت البداية',
    'End Time': 'وقت النهاية',
    'Start Date/Time': 'تاريخ/وقت البداية',
    'End Date/Time': 'تاريخ/وقت النهاية',
    'Expiry Date': 'تاريخ الانتهاء',
    'Issue Date': 'تاريخ الإصدار',
    'Effective From': 'ساري من',
    'Effective To': 'ساري حتى',
    'From': 'من',
    'To': 'إلى',
    'From Time': 'من وقت',
    'To Time': 'إلى وقت',
    'From Week': 'من أسبوع',
    'To Week': 'إلى أسبوع',
    'Period': 'الفترة',
    'Day': 'يوم',
    'Days': 'أيام',
    'Hours': 'الساعات',
    'Total Hours': 'إجمالي الساعات',
    'Normal Hours': 'الساعات العادية',
    'Pause': 'استراحة',
    'Breaks': 'الاستراحات',
    'Location': 'الموقع',
    'Company Name': 'اسم الشركة',
    'Company Information': 'معلومات الشركة',
    'Financial Information': 'المعلومات المالية',
    'Personal Information': 'المعلومات الشخصية',
    'Contract Information': 'معلومات العقد',
    'Contract Type': 'نوع العقد',
    'Contract History': 'سجل العقود',
    'Document Type': 'نوع المستند',
    'Document Number': 'رقم المستند',
    'ID Document': 'وثيقة الهوية',
    "Driver's License": 'رخصة القيادة',
    'Front Side': 'الوجه الأمامي',
    'Back Side': 'الوجه الخلفي',
    'PDF Document': 'مستند PDF',
    'Uploaded By': 'رفع بواسطة',
    'Sort Order': 'ترتيب الفرز',
    'Reference #': 'الرقم المرجعي',
    'Prefix': 'البادئة',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'رقم KvK',
    'BTW Number': 'رقم ضريبة القيمة المضافة',
    'G-Rekening': 'حساب G',

    'No data': 'لا توجد بيانات',
    'No data available': 'لا توجد بيانات متاحة',
    'No customers found': 'لم يتم العثور على عملاء',
    'No employees found': 'لم يتم العثور على موظفين',
    'No projects found': 'لم يتم العثور على مشاريع',
    'No services found': 'لم يتم العثور على خدمات',
    'No supervisors found': 'لم يتم العثور على مشرفين',
    'No supervisors added yet': 'لم تتم إضافة مشرفين بعد',
    'No phone numbers available': 'لا توجد أرقام هاتف متاحة',
    'No email addresses available': 'لا توجد عناوين بريد متاحة',
    'No nationality found': 'لم يتم العثور على جنسية',
    'Search customers...': 'ابحث عن العملاء...',
    'Search employees...': 'ابحث عن الموظفين...',
    'Search employee...': 'ابحث عن موظف...',
    'Search nationality...': 'ابحث عن الجنسية...',
    'Search allowance types...': 'ابحث عن أنواع البدلات...',
    'Select...': 'اختر...',
    'Select customer...': 'اختر عميلاً...',
    'Select project...': 'اختر مشروعاً...',
    'Select service...': 'اختر خدمة...',
    'Select supervisor...': 'اختر مشرفاً...',
    'Select category...': 'اختر فئة...',
    'Select nationality...': 'اختر الجنسية...',
    'Select email...': 'اختر البريد الإلكتروني...',
    'Select phone...': 'اختر الهاتف...',
    'Today': 'اليوم',
    'Toggle menu': 'تبديل القائمة',
};

const ru: PhraseTable = {
    // Reports date ranges
    'This month': 'Этот месяц',
    'This year': 'Этот год',
    'Last 12 months': 'Последние 12 месяцев',
    'No approved hours between': 'Нет утверждённых часов между',
    'Widen the range to see earlier work': 'Расширьте период, чтобы увидеть более раннюю работу',
    'and': 'и',
    'to': 'по',

    // Wallet page
    'Total Balance': 'Общий баланс',
    'Balance': 'Баланс',
    'Advances': 'Авансы',
    'Pending Advances': 'Ожидающие авансы',
    'Employee Wallets': 'Кошельки сотрудников',
    'Advance requests waiting for a decision': 'Заявки на аванс, ожидающие решения',
    'No pending advance requests': 'Нет ожидающих заявок на аванс',
    'Select a wallet to see its recent transactions': 'Выберите кошелёк, чтобы увидеть последние операции',
    'No wallets yet': 'Кошельков пока нет',
    'A wallet appears once an employee has approved hours': 'Кошелёк появляется после утверждения часов сотрудника',
    'No transactions yet': 'Операций пока нет',
    'Employee balances and advance requests': 'Балансы сотрудников и заявки на аванс',

    // Reports warnings
    'Earnings are incomplete': 'Данные о заработке неполны',
    'These employees have no hourly rate on their profile, so their pay cannot be calculated': 'У этих сотрудников не указана почасовая ставка, поэтому оплату рассчитать нельзя',

    // Remaining page copy
    'Allowances (Toeslag)': 'Надбавки',
    'Gratuities (Fooi)': 'Чаевые',
    'Enable Percentage Surcharges': 'Включить процентные надбавки',
    'TOTAL': 'ИТОГО',
    'Are you sure you want to delete': 'Вы уверены, что хотите удалить',
    'Enter custom allowance name...': 'Введите название надбавки...',
    'Search and select employees...': 'Найдите и выберите сотрудников...',
    'Search employees…': 'Поиск сотрудников…',
    'Upload front and back, or a single PDF': 'Загрузите обе стороны или один PDF',
    'Optional description...': 'Описание (необязательно)...',
    'Optional notes...': 'Заметки (необязательно)...',
    'Select a customer...': 'Выберите клиента...',
    'Loading supervisors...': 'Загрузка руководителей...',
    'No supervisors found for this customer': 'Для этого клиента руководители не найдены',
    'Supervisor (Rayon)': 'Руководитель (район)',
    'Rayon Name': 'Название района',
    'Location / Address Notes': 'Заметки о месте / адресе',
    'Enter address, building, floor, etc...': 'Укажите адрес, здание, этаж...',
    'Generate quarters': 'Создать кварталы',
    'HR Email (for Reports)': 'Эл. почта отдела кадров (для отчётов)',
    'This email will appear on HR export reports': 'Этот адрес появится в отчётах отдела кадров',
    'Select services and set prices for this customer': 'Выберите услуги и задайте цены для этого клиента',
    'Add extra rates for weekends, nights, holidays on services': 'Добавьте надбавки за выходные, ночи и праздники к услугам',
    'Add extra rates for weekends, nights, holidays on allowances': 'Добавьте надбавки за выходные, ночи и праздники к надбавкам',
    'Service Surcharge Types': 'Типы надбавок к услугам',
    'Allowance Surcharge Types': 'Типы надбавок к надбавкам',
    'No services available. Add some in Services Management.': 'Услуг нет. Добавьте их в разделе управления услугами.',
    'Custom allowances for this customer (e.g., Mask, Hazard Pay)': 'Особые надбавки для этого клиента (например, маска, за вредность)',
    'Name...': 'Имя...',
    'Code...': 'Код...',
    'Previous slide': 'Предыдущий слайд',
    'Next slide': 'Следующий слайд',
    'Click to upload or drag and drop': 'Нажмите для загрузки или перетащите файл',
    'PDF, DOC, DOCX up to 10MB': 'PDF, DOC, DOCX до 10 МБ',
    'Contracts will be uploaded after the customer is created.': 'Договоры будут загружены после создания клиента.',
    'Admin User': 'Администратор',
    'Main': 'Основной',
    'Loading worklogs...': 'Загрузка учёта часов...',
    'No worklogs found. Please select filters first.': 'Записи не найдены. Сначала выберите фильтры.',
    'Export for HR': 'Экспорт для отдела кадров',
    'Export for Finance': 'Экспорт для финансов',
    'Export for Employee (Simple)': 'Экспорт для сотрудника (простой)',
    'Generate invoice record from these': 'Создать счёт на основе этих записей',
    'Receipt (Photo/PDF)': 'Чек (фото/PDF)',
    'Invoice / receipt number': 'Номер счёта / чека',
    'Add your first expense to start tracking': 'Добавьте первый расход, чтобы начать учёт',
    'Nothing is unresolved in this period': 'В этом периоде нет нерешённых позиций',
    'Deductible input VAT': 'Вычитаемый входной НДС',
    'Must be resolved before filing': 'Необходимо устранить до подачи',
    'Click a rubriek to see the transactions': 'Нажмите на раздел, чтобы увидеть операции',
    'Contact Information': 'Контактные данные',

    // Headings, modals and actions
    'Add Certificate': 'Добавить сертификат',
    'Add New Customer': 'Добавить нового клиента',
    'Add Customer': 'Добавить клиента',
    'Add Supervisor': 'Добавить руководителя',
    'Add Contract': 'Добавить договор',
    'Add Allowance': 'Добавить надбавку',
    'Add Allowance Type': 'Добавить тип надбавки',
    'Add Work Log': 'Добавить учёт часов',
    'Add Email': 'Добавить эл. почту',
    'Add Break': 'Добавить перерыв',
    'Additional Costs': 'Дополнительные расходы',
    'Allowances Configuration': 'Настройка надбавок',
    'Services Configuration': 'Настройка услуг',
    'Approve Employee': 'Утвердить сотрудника',
    'Reject Employee': 'Отклонить сотрудника',
    'Certificate Details': 'Данные сертификата',
    'Create New Project': 'Создать новый проект',
    'Project Details': 'Данные проекта',
    'Project Not Found': 'Проект не найден',
    'Customer Not Found': 'Клиент не найден',
    'No Projects Found': 'Проекты не найдены',
    'Delete Customer': 'Удалить клиента',
    'Delete Employee': 'Удалить сотрудника',
    'Delete Project': 'Удалить проект',
    'Edit Customer': 'Изменить клиента',
    'Edit Employee Profile': 'Изменить профиль сотрудника',
    'Employee Created!': 'Сотрудник создан!',
    'Extract Documents': 'Выгрузить документы',
    'General Manager': 'Генеральный директор',
    'Labor Hours': 'Трудовые часы',
    'New Portal Login': 'Новый вход в портал',
    'Portal Access': 'Доступ к порталу',
    'Rate Change Detected': 'Обнаружено изменение ставки',
    'Shift Scheduling': 'Планирование смен',
    'Schedule Shifts': 'Запланировать смены',
    'Schedule New Shift': 'Запланировать новую смену',
    'Upload New Contract': 'Загрузить новый договор',
    'Wallet Management': 'Управление кошельком',
    'Contract Documents': 'Документы договора',
    'Assignment Details': 'Данные назначения',
    'Rejection Reason': 'Причина отклонения',
    'Worklog Status': 'Статус учёта часов',
    'Generate Invoice': 'Создать счёт',
    'Create Invoice': 'Создать счёт',
    'Export Timesheet': 'Экспорт табеля',
    'Time Window': 'Временное окно',
    'Service Type': 'Тип услуги',
    'Allowance Type': 'Тип надбавки',
    'Custom / Other': 'Другое',
    'Custom Allowance Name': 'Название надбавки',
    'Total Types': 'Всего типов',
    'Back to Customers': 'Назад к клиентам',
    'Back to Work Logs': 'Назад к учёту часов',
    'Back to Projects': 'Назад к проектам',
    'Specific Dates': 'Конкретные даты',
    'Active Days': 'Активные дни',
    'Active Customer': 'Активный клиент',
    'Is Active': 'Активен',
    'Requires Agency': 'Требуется агентство',
    'Requires End Date': 'Требуется дата окончания',
    'Special Instructions': 'Особые указания',
    'Work location': 'Место работы',
    'Supervisor Phone': 'Телефон руководителя',
    'Supervisor Email': 'Эл. почта руководителя',
    'To Pay Employees': 'К выплате сотрудникам',
    'To Charge Customer': 'К выставлению клиенту',
    'To Charge': 'К выставлению',
    'Save Expense': 'Сохранить расход',
    'Vendor Name': 'Поставщик',
    'Payment Method': 'Способ оплаты',
    'Total (incl. BTW)': 'Итого (с НДС)',
    'Amount (excl. BTW)': 'Сумма (без НДС)',
    'BTW Rate': 'Ставка НДС',
    'BTW Paid': 'Уплаченный НДС',
    'Clear Filters': 'Сбросить фильтры',
    'Refresh': 'Обновить',
    'Close': 'Закрыть',

    // Dutch-source screens (finance, VAT, invoices)
    'Annuleren': 'Отмена',
    'Versturen': 'Отправить',
    'Sluiten': 'Закрыть',
    'Bedrag': 'Сумма',
    'Datum': 'Дата',
    'Uren': 'Часы',
    'Tarief': 'Ставка',
    'Omzet': 'Выручка',
    'Kosten': 'Расходы',
    'Regels': 'Строки',
    'Totalen': 'Итоги',
    'Posten': 'Проводки',
    'Rubriek': 'Раздел',
    'Rubrieken': 'Разделы',
    'Creditnota': 'Кредит-нота',
    'Creditnota\'s': 'Кредит-ноты',
    'Creditnota maken': 'Создать кредит-ноту',
    'Verlegd': 'НДС перенесён',
    'Btw verlegd': 'НДС перенесён',
    'Btw-behandeling': 'Режим НДС',
    'Onderbouwing': 'Обоснование',
    'Vast te stellen': 'Требует уточнения',
    'Eerst oplossen': 'Сначала устранить',
    'Voorwaarden voor verlegging': 'Условия переноса НДС',
    'Uitzonderingen': 'Исключения',
    'Audit trail': 'Журнал аудита',
    'Omzetbelasting': 'Налог с оборота',
    'Terug naar facturen': 'Назад к счетам',
    'Open volledige factuur': 'Открыть счёт полностью',
    'Factuur e-mailen': 'Отправить счёт по почте',
    'Ontvangen bedrag (€)': 'Полученная сумма (€)',
    'Waarom wordt deze factuur gecrediteerd?': 'Почему по этому счёту выставляется кредит-нота?',
    'Deze factuur kan worden verstuurd.': 'Этот счёт готов к отправке.',
    'Omzet (excl. btw)': 'Выручка (без НДС)',
    'Kosten (excl. btw)': 'Расходы (без НДС)',
    'Brutomarge': 'Валовая маржа',
    'Btw per kwartaal': 'НДС по кварталам',
    'Berekend uit het btw-grootboek': 'Рассчитано по книге НДС',
    'Omzet en kosten per maand': 'Выручка и расходы по месяцам',
    'Grootste klanten': 'Крупнейшие клиенты',
    'Te ontvangen': 'К получению',
    'Te betalen': 'К оплате',
    'Nog niet vervallen': 'Срок не наступил',
    '1–30 dagen': '1–30 дней',
    '31–60 dagen': '31–60 дней',
    '61–90 dagen': '61–90 дней',
    '90+ dagen': '90+ дней',
    'Uitzendbureaus': 'Агентства',
    'Inkoopfacturen': 'Счета поставщиков',
    'Medewerkers (wallet)': 'Сотрудники (кошелёк)',
    'Facturatie en bedrijfsgegevens': 'Выставление счетов и данные компании',
    'Btw-identificatienummer': 'ИНН по НДС',
    'Betaaltermijn (dagen)': 'Срок оплаты (дней)',
    'Voettekst op de factuur': 'Нижний колонтитул счёта',
    'Facturen worden genummerd als': 'Счета нумеруются как',

    // Navigation
    'Weekly Board': 'Недельная доска',
    'Contract Types': 'Типы договоров',
    'Day Payment Types': 'Типы дневных надбавок',
    'HR': 'Кадры',
    'Finance': 'Финансы',
    'Outgoing Invoices': 'Исходящие счета',
    'Incoming Invoices': 'Входящие счета',
    'Financial Overview': 'Финансовый обзор',
    'BTW Aangifte': 'Декларация НДС',
    'Expenses Summary': 'Сводка расходов',
    'Allowance Types': 'Типы надбавок',

    'Save': 'Сохранить',
    'Cancel': 'Отмена',
    'Delete': 'Удалить',
    'Edit': 'Изменить',
    'Add': 'Добавить',
    'View': 'Просмотр',
    'Back': 'Назад',
    'Next': 'Далее',
    'Previous': 'Назад',
    'Prev': 'Назад',
    'Retry': 'Повторить',
    'Select': 'Выбрать',
    'Select All': 'Выбрать все',
    'Clear': 'Очистить',
    'Clear All': 'Очистить все',
    'Clear all': 'Очистить все',
    'Search': 'Поиск',
    'Filter': 'Фильтр',
    'Export': 'Экспорт',
    'Export CSV': 'Экспорт CSV',
    'Import': 'Импорт',
    'Download': 'Скачать',
    'Download PDF': 'Скачать PDF',
    'Upload': 'Загрузить',
    'Print': 'Печать',
    'Send': 'Отправить',
    'Submit': 'Отправить',
    'Approve': 'Утвердить',
    'Reject': 'Отклонить',
    'Generate': 'Создать',
    'Create': 'Создать',
    'Update': 'Обновить',
    'Confirm': 'Подтвердить',
    'Done': 'Готово',
    'Yes': 'Да',
    'No': 'Нет',
    'Actions': 'Действия',
    'Help': 'Помощь',

    'Status': 'Статус',
    'Active': 'Активен',
    'Inactive': 'Неактивен',
    'Pending': 'В ожидании',
    'Approved': 'Утверждено',
    'Rejected': 'Отклонено',
    'Paid': 'Оплачено',
    'Unpaid': 'Не оплачено',
    'Draft': 'Черновик',
    'Sent': 'Отправлено',
    'Overdue': 'Просрочено',
    'Cancelled': 'Отменено',
    'Completed': 'Завершено',
    'Submitted': 'Подано',
    'Incomplete': 'Не заполнено',
    'Required': 'Обязательно',
    'Optional': 'Необязательно',
    'Current': 'Текущий',
    'Not set': 'Не задано',
    'Loading...': 'Загрузка...',
    'Loading': 'Загрузка',

    'Dashboard': 'Панель',
    'Employee': 'Сотрудник',
    'Employees': 'Сотрудники',
    'Customer': 'Клиент',
    'Customers': 'Клиенты',
    'Project': 'Проект',
    'Projects': 'Проекты',
    'Work Logs': 'Учёт часов',
    'Worklogs': 'Учёт часов',
    'Invoice': 'Счёт',
    'Invoices': 'Счета',
    'Agency': 'Агентство',
    'Agencies': 'Агентства',
    'Agency Invoices': 'Счета агентств',
    'Expenses': 'Расходы',
    'Expense': 'Расход',
    'Wallet': 'Кошелёк',
    'Settings': 'Настройки',
    'Notifications': 'Уведомления',
    'Reports': 'Отчёты',
    'Certificates': 'Сертификаты',
    'Payslips': 'Расчётные листы',
    'Payroll': 'Расчёт зарплаты',
    'Attendance': 'Посещаемость',
    'Leave Requests': 'Заявки на отпуск',
    'Contracts': 'Договоры',
    'Services': 'Услуги',
    'Service': 'Услуга',
    'Supervisor': 'Руководитель',
    'Supervisors': 'Руководители',
    'Allowances': 'Надбавки',
    'Allowance': 'Надбавка',
    'Gratuities': 'Чаевые',
    'Shifts': 'Смены',
    'Shift': 'Смена',
    'Document': 'Документ',
    'Documents': 'Документы',
    'Administrator': 'Администратор',
    'Logout': 'Выйти',
    'Logout Account': 'Выйти из аккаунта',

    'Name': 'Имя',
    'First Name': 'Имя',
    'First name': 'Имя',
    'Last Name': 'Фамилия',
    'Last name': 'Фамилия',
    'Email': 'Эл. почта',
    'Email Address': 'Адрес эл. почты',
    'Email Addresses': 'Адреса эл. почты',
    'Phone': 'Телефон',
    'Phone Numbers': 'Номера телефонов',
    'Address': 'Адрес',
    'City': 'Город',
    'Postcode': 'Почтовый индекс',
    'Street Name': 'Улица',
    'House Nr.': 'Дом №',
    'Add.': 'Доп.',
    'Country': 'Страна',
    'Nationality': 'Гражданство',
    'Gender': 'Пол',
    'Date of Birth': 'Дата рождения',
    'Birthplace': 'Место рождения',
    'Password': 'Пароль',
    'Description': 'Описание',
    'Notes': 'Заметки',
    'Notes (Optional)': 'Заметки (необязательно)',
    'Code': 'Код',
    'Type': 'Тип',
    'Category': 'Категория',
    'Amount': 'Сумма',
    'Price': 'Цена',
    'Rate': 'Ставка',
    'Hourly Rate': 'Почасовая ставка',
    'Base Price': 'Базовая цена',
    'Total': 'Итого',
    'Subtotal': 'Промежуточный итог',
    'Date': 'Дата',
    'Time': 'Время',
    'Date & Time': 'Дата и время',
    'Start': 'Начало',
    'End': 'Конец',
    'Start Date': 'Дата начала',
    'End Date': 'Дата окончания',
    'Start Time': 'Время начала',
    'End Time': 'Время окончания',
    'Start Date/Time': 'Дата/время начала',
    'End Date/Time': 'Дата/время окончания',
    'Expiry Date': 'Срок действия',
    'Issue Date': 'Дата выставления',
    'Effective From': 'Действует с',
    'Effective To': 'Действует по',
    'From': 'С',
    'To': 'По',
    'From Time': 'С какого времени',
    'To Time': 'По какое время',
    'From Week': 'С недели',
    'To Week': 'По неделю',
    'Period': 'Период',
    'Day': 'День',
    'Days': 'Дни',
    'Hours': 'Часы',
    'Total Hours': 'Всего часов',
    'Normal Hours': 'Обычные часы',
    'Pause': 'Перерыв',
    'Breaks': 'Перерывы',
    'Location': 'Местоположение',
    'Company Name': 'Название компании',
    'Company Information': 'Данные компании',
    'Financial Information': 'Финансовые данные',
    'Personal Information': 'Личные данные',
    'Contract Information': 'Данные договора',
    'Contract Type': 'Тип договора',
    'Contract History': 'История договоров',
    'Document Type': 'Тип документа',
    'Document Number': 'Номер документа',
    'ID Document': 'Удостоверение личности',
    "Driver's License": 'Водительское удостоверение',
    'Front Side': 'Лицевая сторона',
    'Back Side': 'Обратная сторона',
    'PDF Document': 'PDF-документ',
    'Uploaded By': 'Загрузил',
    'Sort Order': 'Порядок сортировки',
    'Reference #': 'Номер ссылки',
    'Prefix': 'Префикс',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'Номер KvK',
    'BTW Number': 'НДС-номер',
    'G-Rekening': 'G-счёт',

    'No data': 'Нет данных',
    'No data available': 'Данные отсутствуют',
    'No customers found': 'Клиенты не найдены',
    'No employees found': 'Сотрудники не найдены',
    'No projects found': 'Проекты не найдены',
    'No services found': 'Услуги не найдены',
    'No supervisors found': 'Руководители не найдены',
    'No supervisors added yet': 'Руководители ещё не добавлены',
    'No phone numbers available': 'Нет доступных телефонов',
    'No email addresses available': 'Нет доступных адресов',
    'No nationality found': 'Гражданство не найдено',
    'Search customers...': 'Поиск клиентов...',
    'Search employees...': 'Поиск сотрудников...',
    'Search employee...': 'Поиск сотрудника...',
    'Search nationality...': 'Поиск гражданства...',
    'Search allowance types...': 'Поиск типов надбавок...',
    'Select...': 'Выберите...',
    'Select customer...': 'Выберите клиента...',
    'Select project...': 'Выберите проект...',
    'Select service...': 'Выберите услугу...',
    'Select supervisor...': 'Выберите руководителя...',
    'Select category...': 'Выберите категорию...',
    'Select nationality...': 'Выберите гражданство...',
    'Select email...': 'Выберите эл. почту...',
    'Select phone...': 'Выберите телефон...',
    'Today': 'Сегодня',
    'Toggle menu': 'Переключить меню',
};

const uk: PhraseTable = {
    // Reports date ranges
    'This month': 'Цей місяць',
    'This year': 'Цей рік',
    'Last 12 months': 'Останні 12 місяців',
    'No approved hours between': 'Немає затверджених годин між',
    'Widen the range to see earlier work': 'Розширте період, щоб побачити ранішу роботу',
    'and': 'і',
    'to': 'до',

    // Wallet page
    'Total Balance': 'Загальний баланс',
    'Balance': 'Баланс',
    'Advances': 'Аванси',
    'Pending Advances': 'Аванси в очікуванні',
    'Employee Wallets': 'Гаманці працівників',
    'Advance requests waiting for a decision': 'Заявки на аванс, що очікують рішення',
    'No pending advance requests': 'Немає заявок на аванс',
    'Select a wallet to see its recent transactions': 'Виберіть гаманець, щоб побачити останні операції',
    'No wallets yet': 'Гаманців поки немає',
    'A wallet appears once an employee has approved hours': 'Гаманець з\'являється після затвердження годин працівника',
    'No transactions yet': 'Операцій поки немає',
    'Employee balances and advance requests': 'Баланси працівників і заявки на аванс',

    // Reports warnings
    'Earnings are incomplete': 'Дані про заробіток неповні',
    'These employees have no hourly rate on their profile, so their pay cannot be calculated': 'У цих працівників не вказано погодинну ставку, тому оплату розрахувати неможливо',

    // Remaining page copy
    'Allowances (Toeslag)': 'Надбавки',
    'Gratuities (Fooi)': 'Чайові',
    'Enable Percentage Surcharges': 'Увімкнути відсоткові надбавки',
    'TOTAL': 'РАЗОМ',
    'Are you sure you want to delete': 'Ви впевнені, що хочете видалити',
    'Enter custom allowance name...': 'Введіть назву надбавки...',
    'Search and select employees...': 'Знайдіть і виберіть працівників...',
    'Search employees…': 'Пошук працівників…',
    'Upload front and back, or a single PDF': 'Завантажте обидві сторони або один PDF',
    'Optional description...': 'Опис (необов\'язково)...',
    'Optional notes...': 'Нотатки (необов\'язково)...',
    'Select a customer...': 'Виберіть клієнта...',
    'Loading supervisors...': 'Завантаження керівників...',
    'No supervisors found for this customer': 'Для цього клієнта керівників не знайдено',
    'Supervisor (Rayon)': 'Керівник (район)',
    'Rayon Name': 'Назва району',
    'Location / Address Notes': 'Нотатки про місце / адресу',
    'Enter address, building, floor, etc...': 'Вкажіть адресу, будівлю, поверх...',
    'Generate quarters': 'Створити квартали',
    'HR Email (for Reports)': 'Ел. пошта кадрів (для звітів)',
    'This email will appear on HR export reports': 'Ця адреса з\'явиться у звітах кадрів',
    'Select services and set prices for this customer': 'Виберіть послуги та задайте ціни для цього клієнта',
    'Add extra rates for weekends, nights, holidays on services': 'Додайте надбавки за вихідні, ночі та свята до послуг',
    'Add extra rates for weekends, nights, holidays on allowances': 'Додайте надбавки за вихідні, ночі та свята до надбавок',
    'Service Surcharge Types': 'Типи надбавок до послуг',
    'Allowance Surcharge Types': 'Типи надбавок до надбавок',
    'No services available. Add some in Services Management.': 'Послуг немає. Додайте їх у розділі керування послугами.',
    'Custom allowances for this customer (e.g., Mask, Hazard Pay)': 'Особливі надбавки для цього клієнта (напр. маска, за шкідливість)',
    'Name...': 'Ім\'я...',
    'Code...': 'Код...',
    'Previous slide': 'Попередній слайд',
    'Next slide': 'Наступний слайд',
    'Click to upload or drag and drop': 'Натисніть для завантаження або перетягніть файл',
    'PDF, DOC, DOCX up to 10MB': 'PDF, DOC, DOCX до 10 МБ',
    'Contracts will be uploaded after the customer is created.': 'Договори буде завантажено після створення клієнта.',
    'Admin User': 'Адміністратор',
    'Main': 'Основний',
    'Loading worklogs...': 'Завантаження обліку годин...',
    'No worklogs found. Please select filters first.': 'Записів не знайдено. Спершу виберіть фільтри.',
    'Export for HR': 'Експорт для кадрів',
    'Export for Finance': 'Експорт для фінансів',
    'Export for Employee (Simple)': 'Експорт для працівника (простий)',
    'Generate invoice record from these': 'Створити рахунок на основі цих записів',
    'Receipt (Photo/PDF)': 'Чек (фото/PDF)',
    'Invoice / receipt number': 'Номер рахунка / чека',
    'Add your first expense to start tracking': 'Додайте першу витрату, щоб почати облік',
    'Nothing is unresolved in this period': 'У цьому періоді немає невирішених позицій',
    'Deductible input VAT': 'Вхідний ПДВ до відрахування',
    'Must be resolved before filing': 'Потрібно усунути до подання',
    'Click a rubriek to see the transactions': 'Натисніть на розділ, щоб побачити операції',
    'Contact Information': 'Контактні дані',

    // Headings, modals and actions
    'Add Certificate': 'Додати сертифікат',
    'Add New Customer': 'Додати нового клієнта',
    'Add Customer': 'Додати клієнта',
    'Add Supervisor': 'Додати керівника',
    'Add Contract': 'Додати договір',
    'Add Allowance': 'Додати надбавку',
    'Add Allowance Type': 'Додати тип надбавки',
    'Add Work Log': 'Додати облік годин',
    'Add Email': 'Додати ел. пошту',
    'Add Break': 'Додати перерву',
    'Additional Costs': 'Додаткові витрати',
    'Allowances Configuration': 'Налаштування надбавок',
    'Services Configuration': 'Налаштування послуг',
    'Approve Employee': 'Затвердити працівника',
    'Reject Employee': 'Відхилити працівника',
    'Certificate Details': 'Дані сертифіката',
    'Create New Project': 'Створити новий проєкт',
    'Project Details': 'Дані проєкту',
    'Project Not Found': 'Проєкт не знайдено',
    'Customer Not Found': 'Клієнта не знайдено',
    'No Projects Found': 'Проєктів не знайдено',
    'Delete Customer': 'Видалити клієнта',
    'Delete Employee': 'Видалити працівника',
    'Delete Project': 'Видалити проєкт',
    'Edit Customer': 'Редагувати клієнта',
    'Edit Employee Profile': 'Редагувати профіль працівника',
    'Employee Created!': 'Працівника створено!',
    'Extract Documents': 'Вивантажити документи',
    'General Manager': 'Генеральний директор',
    'Labor Hours': 'Трудові години',
    'New Portal Login': 'Новий вхід до порталу',
    'Portal Access': 'Доступ до порталу',
    'Rate Change Detected': 'Виявлено зміну ставки',
    'Shift Scheduling': 'Планування змін',
    'Schedule Shifts': 'Запланувати зміни',
    'Schedule New Shift': 'Запланувати нову зміну',
    'Upload New Contract': 'Завантажити новий договір',
    'Wallet Management': 'Керування гаманцем',
    'Contract Documents': 'Документи договору',
    'Assignment Details': 'Дані призначення',
    'Rejection Reason': 'Причина відхилення',
    'Worklog Status': 'Статус обліку годин',
    'Generate Invoice': 'Створити рахунок',
    'Create Invoice': 'Створити рахунок',
    'Export Timesheet': 'Експорт табеля',
    'Time Window': 'Часове вікно',
    'Service Type': 'Тип послуги',
    'Allowance Type': 'Тип надбавки',
    'Custom / Other': 'Інше',
    'Custom Allowance Name': 'Назва надбавки',
    'Total Types': 'Усього типів',
    'Back to Customers': 'Назад до клієнтів',
    'Back to Work Logs': 'Назад до обліку годин',
    'Back to Projects': 'Назад до проєктів',
    'Specific Dates': 'Конкретні дати',
    'Active Days': 'Активні дні',
    'Active Customer': 'Активний клієнт',
    'Is Active': 'Активний',
    'Requires Agency': 'Потрібна агенція',
    'Requires End Date': 'Потрібна дата завершення',
    'Special Instructions': 'Особливі вказівки',
    'Work location': 'Місце роботи',
    'Supervisor Phone': 'Телефон керівника',
    'Supervisor Email': 'Ел. пошта керівника',
    'To Pay Employees': 'До виплати працівникам',
    'To Charge Customer': 'До виставлення клієнту',
    'To Charge': 'До виставлення',
    'Save Expense': 'Зберегти витрату',
    'Vendor Name': 'Постачальник',
    'Payment Method': 'Спосіб оплати',
    'Total (incl. BTW)': 'Разом (з ПДВ)',
    'Amount (excl. BTW)': 'Сума (без ПДВ)',
    'BTW Rate': 'Ставка ПДВ',
    'BTW Paid': 'Сплачений ПДВ',
    'Clear Filters': 'Скинути фільтри',
    'Refresh': 'Оновити',
    'Close': 'Закрити',

    // Dutch-source screens (finance, VAT, invoices)
    'Annuleren': 'Скасувати',
    'Versturen': 'Надіслати',
    'Sluiten': 'Закрити',
    'Bedrag': 'Сума',
    'Datum': 'Дата',
    'Uren': 'Години',
    'Tarief': 'Ставка',
    'Omzet': 'Дохід',
    'Kosten': 'Витрати',
    'Regels': 'Рядки',
    'Totalen': 'Підсумки',
    'Posten': 'Проводки',
    'Rubriek': 'Розділ',
    'Rubrieken': 'Розділи',
    'Creditnota': 'Кредит-нота',
    'Creditnota\'s': 'Кредит-ноти',
    'Creditnota maken': 'Створити кредит-ноту',
    'Verlegd': 'ПДВ перенесено',
    'Btw verlegd': 'ПДВ перенесено',
    'Btw-behandeling': 'Режим ПДВ',
    'Onderbouwing': 'Обґрунтування',
    'Vast te stellen': 'Потребує уточнення',
    'Eerst oplossen': 'Спершу усунути',
    'Voorwaarden voor verlegging': 'Умови перенесення ПДВ',
    'Uitzonderingen': 'Винятки',
    'Audit trail': 'Журнал аудиту',
    'Omzetbelasting': 'Податок з обороту',
    'Terug naar facturen': 'Назад до рахунків',
    'Open volledige factuur': 'Відкрити рахунок повністю',
    'Factuur e-mailen': 'Надіслати рахунок поштою',
    'Ontvangen bedrag (€)': 'Отримана сума (€)',
    'Waarom wordt deze factuur gecrediteerd?': 'Чому за цим рахунком виставляється кредит-нота?',
    'Deze factuur kan worden verstuurd.': 'Цей рахунок готовий до надсилання.',
    'Omzet (excl. btw)': 'Дохід (без ПДВ)',
    'Kosten (excl. btw)': 'Витрати (без ПДВ)',
    'Brutomarge': 'Валова маржа',
    'Btw per kwartaal': 'ПДВ поквартально',
    'Berekend uit het btw-grootboek': 'Розраховано за книгою ПДВ',
    'Omzet en kosten per maand': 'Дохід і витрати помісячно',
    'Grootste klanten': 'Найбільші клієнти',
    'Te ontvangen': 'До отримання',
    'Te betalen': 'До сплати',
    'Nog niet vervallen': 'Термін не настав',
    '1–30 dagen': '1–30 днів',
    '31–60 dagen': '31–60 днів',
    '61–90 dagen': '61–90 днів',
    '90+ dagen': '90+ днів',
    'Uitzendbureaus': 'Агенції',
    'Inkoopfacturen': 'Рахунки постачальників',
    'Medewerkers (wallet)': 'Працівники (гаманець)',
    'Facturatie en bedrijfsgegevens': 'Виставлення рахунків і дані компанії',
    'Btw-identificatienummer': 'Номер платника ПДВ',
    'Betaaltermijn (dagen)': 'Термін оплати (днів)',
    'Voettekst op de factuur': 'Нижній колонтитул рахунка',
    'Facturen worden genummerd als': 'Рахунки нумеруються як',

    // Navigation
    'Weekly Board': 'Тижнева дошка',
    'Contract Types': 'Типи договорів',
    'Day Payment Types': 'Типи денних надбавок',
    'HR': 'Кадри',
    'Finance': 'Фінанси',
    'Outgoing Invoices': 'Вихідні рахунки',
    'Incoming Invoices': 'Вхідні рахунки',
    'Financial Overview': 'Фінансовий огляд',
    'BTW Aangifte': 'Декларація ПДВ',
    'Expenses Summary': 'Зведення витрат',
    'Allowance Types': 'Типи надбавок',

    'Save': 'Зберегти',
    'Cancel': 'Скасувати',
    'Delete': 'Видалити',
    'Edit': 'Редагувати',
    'Add': 'Додати',
    'View': 'Переглянути',
    'Back': 'Назад',
    'Next': 'Далі',
    'Previous': 'Назад',
    'Prev': 'Назад',
    'Retry': 'Повторити',
    'Select': 'Вибрати',
    'Select All': 'Вибрати все',
    'Clear': 'Очистити',
    'Clear All': 'Очистити все',
    'Clear all': 'Очистити все',
    'Search': 'Пошук',
    'Filter': 'Фільтр',
    'Export': 'Експорт',
    'Export CSV': 'Експорт CSV',
    'Import': 'Імпорт',
    'Download': 'Завантажити',
    'Download PDF': 'Завантажити PDF',
    'Upload': 'Вивантажити',
    'Print': 'Друк',
    'Send': 'Надіслати',
    'Submit': 'Надіслати',
    'Approve': 'Затвердити',
    'Reject': 'Відхилити',
    'Generate': 'Створити',
    'Create': 'Створити',
    'Update': 'Оновити',
    'Confirm': 'Підтвердити',
    'Done': 'Готово',
    'Yes': 'Так',
    'No': 'Ні',
    'Actions': 'Дії',
    'Help': 'Довідка',

    'Status': 'Статус',
    'Active': 'Активний',
    'Inactive': 'Неактивний',
    'Pending': 'В очікуванні',
    'Approved': 'Затверджено',
    'Rejected': 'Відхилено',
    'Paid': 'Сплачено',
    'Unpaid': 'Не сплачено',
    'Draft': 'Чернетка',
    'Sent': 'Надіслано',
    'Overdue': 'Прострочено',
    'Cancelled': 'Скасовано',
    'Completed': 'Завершено',
    'Submitted': 'Подано',
    'Incomplete': 'Не заповнено',
    'Required': "Обов'язково",
    'Optional': "Необов'язково",
    'Current': 'Поточний',
    'Not set': 'Не задано',
    'Loading...': 'Завантаження...',
    'Loading': 'Завантаження',

    'Dashboard': 'Панель',
    'Employee': 'Працівник',
    'Employees': 'Працівники',
    'Customer': 'Клієнт',
    'Customers': 'Клієнти',
    'Project': 'Проєкт',
    'Projects': 'Проєкти',
    'Work Logs': 'Облік годин',
    'Worklogs': 'Облік годин',
    'Invoice': 'Рахунок',
    'Invoices': 'Рахунки',
    'Agency': 'Агенція',
    'Agencies': 'Агенції',
    'Agency Invoices': 'Рахунки агенцій',
    'Expenses': 'Витрати',
    'Expense': 'Витрата',
    'Wallet': 'Гаманець',
    'Settings': 'Налаштування',
    'Notifications': 'Сповіщення',
    'Reports': 'Звіти',
    'Certificates': 'Сертифікати',
    'Payslips': 'Розрахункові листи',
    'Payroll': 'Нарахування зарплати',
    'Attendance': 'Відвідуваність',
    'Leave Requests': 'Заявки на відпустку',
    'Contracts': 'Договори',
    'Services': 'Послуги',
    'Service': 'Послуга',
    'Supervisor': 'Керівник',
    'Supervisors': 'Керівники',
    'Allowances': 'Надбавки',
    'Allowance': 'Надбавка',
    'Gratuities': 'Чайові',
    'Shifts': 'Зміни',
    'Shift': 'Зміна',
    'Document': 'Документ',
    'Documents': 'Документи',
    'Administrator': 'Адміністратор',
    'Logout': 'Вийти',
    'Logout Account': 'Вийти з облікового запису',

    'Name': "Ім'я",
    'First Name': "Ім'я",
    'First name': "Ім'я",
    'Last Name': 'Прізвище',
    'Last name': 'Прізвище',
    'Email': 'Ел. пошта',
    'Email Address': 'Адреса ел. пошти',
    'Email Addresses': 'Адреси ел. пошти',
    'Phone': 'Телефон',
    'Phone Numbers': 'Номери телефонів',
    'Address': 'Адреса',
    'City': 'Місто',
    'Postcode': 'Поштовий індекс',
    'Street Name': 'Вулиця',
    'House Nr.': 'Будинок №',
    'Add.': 'Дод.',
    'Country': 'Країна',
    'Nationality': 'Громадянство',
    'Gender': 'Стать',
    'Date of Birth': 'Дата народження',
    'Birthplace': 'Місце народження',
    'Password': 'Пароль',
    'Description': 'Опис',
    'Notes': 'Нотатки',
    'Notes (Optional)': "Нотатки (необов'язково)",
    'Code': 'Код',
    'Type': 'Тип',
    'Category': 'Категорія',
    'Amount': 'Сума',
    'Price': 'Ціна',
    'Rate': 'Ставка',
    'Hourly Rate': 'Погодинна ставка',
    'Base Price': 'Базова ціна',
    'Total': 'Разом',
    'Subtotal': 'Проміжний підсумок',
    'Date': 'Дата',
    'Time': 'Час',
    'Date & Time': 'Дата й час',
    'Start': 'Початок',
    'End': 'Кінець',
    'Start Date': 'Дата початку',
    'End Date': 'Дата завершення',
    'Start Time': 'Час початку',
    'End Time': 'Час завершення',
    'Start Date/Time': 'Дата/час початку',
    'End Date/Time': 'Дата/час завершення',
    'Expiry Date': 'Термін дії',
    'Issue Date': 'Дата виставлення',
    'Effective From': 'Діє з',
    'Effective To': 'Діє до',
    'From': 'З',
    'To': 'До',
    'From Time': 'З якого часу',
    'To Time': 'До якого часу',
    'From Week': 'З тижня',
    'To Week': 'До тижня',
    'Period': 'Період',
    'Day': 'День',
    'Days': 'Дні',
    'Hours': 'Години',
    'Total Hours': 'Усього годин',
    'Normal Hours': 'Звичайні години',
    'Pause': 'Перерва',
    'Breaks': 'Перерви',
    'Location': 'Розташування',
    'Company Name': 'Назва компанії',
    'Company Information': 'Дані компанії',
    'Financial Information': 'Фінансові дані',
    'Personal Information': 'Особисті дані',
    'Contract Information': 'Дані договору',
    'Contract Type': 'Тип договору',
    'Contract History': 'Історія договорів',
    'Document Type': 'Тип документа',
    'Document Number': 'Номер документа',
    'ID Document': 'Посвідчення особи',
    "Driver's License": 'Посвідчення водія',
    'Front Side': 'Лицьовий бік',
    'Back Side': 'Зворотний бік',
    'PDF Document': 'PDF-документ',
    'Uploaded By': 'Завантажив',
    'Sort Order': 'Порядок сортування',
    'Reference #': 'Номер посилання',
    'Prefix': 'Префікс',
    'IBAN': 'IBAN',
    'BSN': 'BSN',
    'KvK Number': 'Номер KvK',
    'BTW Number': 'Номер ПДВ',
    'G-Rekening': 'G-рахунок',

    'No data': 'Немає даних',
    'No data available': 'Дані відсутні',
    'No customers found': 'Клієнтів не знайдено',
    'No employees found': 'Працівників не знайдено',
    'No projects found': 'Проєктів не знайдено',
    'No services found': 'Послуг не знайдено',
    'No supervisors found': 'Керівників не знайдено',
    'No supervisors added yet': 'Керівників ще не додано',
    'No phone numbers available': 'Немає доступних телефонів',
    'No email addresses available': 'Немає доступних адрес',
    'No nationality found': 'Громадянство не знайдено',
    'Search customers...': 'Пошук клієнтів...',
    'Search employees...': 'Пошук працівників...',
    'Search employee...': 'Пошук працівника...',
    'Search nationality...': 'Пошук громадянства...',
    'Search allowance types...': 'Пошук типів надбавок...',
    'Select...': 'Виберіть...',
    'Select customer...': 'Виберіть клієнта...',
    'Select project...': 'Виберіть проєкт...',
    'Select service...': 'Виберіть послугу...',
    'Select supervisor...': 'Виберіть керівника...',
    'Select category...': 'Виберіть категорію...',
    'Select nationality...': 'Виберіть громадянство...',
    'Select email...': 'Виберіть ел. пошту...',
    'Select phone...': 'Виберіть телефон...',
    'Today': 'Сьогодні',
    'Toggle menu': 'Перемкнути меню',
};

/**
 * The finance, VAT and invoice screens were written in Dutch, so those
 * phrases need an English table too. Keys stay in the language the screen
 * was authored in; a key absent from a table falls through to itself.
 */
const en: PhraseTable = {
    'Annuleren': 'Cancel',
    'Versturen': 'Send',
    'Sluiten': 'Close',
    'Bedrag': 'Amount',
    'Datum': 'Date',
    'Uren': 'Hours',
    'Tarief': 'Rate',
    'Omzet': 'Revenue',
    'Kosten': 'Costs',
    'Regels': 'Lines',
    'Totalen': 'Totals',
    'Posten': 'Entries',
    'Rubriek': 'Box',
    'Rubrieken': 'Boxes',
    'Creditnota': 'Credit note',
    'Creditnota\'s': 'Credit notes',
    'Creditnota maken': 'Create credit note',
    'Verlegd': 'Reverse-charged',
    'Btw verlegd': 'VAT reverse-charged',
    'Btw-behandeling': 'VAT treatment',
    'Onderbouwing': 'Basis',
    'Vast te stellen': 'To be determined',
    'Eerst oplossen': 'Resolve first',
    'Voorwaarden voor verlegging': 'Reverse-charge conditions',
    'Uitzonderingen': 'Exceptions',
    'Audit trail': 'Audit trail',
    'Omzetbelasting': 'Turnover tax',
    'Terug naar facturen': 'Back to invoices',
    'Open volledige factuur': 'Open full invoice',
    'Factuur e-mailen': 'Email invoice',
    'Ontvangen bedrag (€)': 'Amount received (€)',
    'Waarom wordt deze factuur gecrediteerd?': 'Why is this invoice being credited?',
    'Deze factuur kan worden verstuurd.': 'This invoice is ready to send.',
    'Omzet (excl. btw)': 'Revenue (excl. VAT)',
    'Kosten (excl. btw)': 'Costs (excl. VAT)',
    'Brutomarge': 'Gross margin',
    'Btw per kwartaal': 'VAT per quarter',
    'Berekend uit het btw-grootboek': 'Calculated from the VAT ledger',
    'Omzet en kosten per maand': 'Revenue and costs per month',
    'Grootste klanten': 'Largest customers',
    'Te ontvangen': 'Receivable',
    'Te betalen': 'Payable',
    'Nog niet vervallen': 'Not yet due',
    '1–30 dagen': '1–30 days',
    '31–60 dagen': '31–60 days',
    '61–90 dagen': '61–90 days',
    '90+ dagen': '90+ days',
    'Uitzendbureaus': 'Agencies',
    'Inkoopfacturen': 'Purchase invoices',
    'Medewerkers (wallet)': 'Employees (wallet)',
    'Facturatie en bedrijfsgegevens': 'Invoicing and company details',
    'Btw-identificatienummer': 'VAT identification number',
    'Betaaltermijn (dagen)': 'Payment term (days)',
    'Voettekst op de factuur': 'Invoice footer',
    'Facturen worden genummerd als': 'Invoices are numbered as',
};

/** Phrase tables per language. */
export const phrases: Record<string, PhraseTable> = { nl, en, ar, ru, uk };
